### ISSUE TITLE
Chosen option values not shown when configurable product is added to cart

### ISSUE THREAD

**Issue by jernejh** [magento/magento2#7285]
### Preconditions

1. Magento 2.1.2 
2. PHP 7.1

### Steps to reproduce

1. Prepare attributes and values
2. Prepare the configurable product with different options
3. Prepare a set of simple products which are a basis for a configurable product
4. Import products over CSV
5. Refresh indexes, cache
6. Select some options such as size, color. At this point: {1} product is dynamically changing price - according to chosen options, which is correct behaviour, but on the other hand {2} the images for different colors of a product are not changing, according to selected options, which is not correct behaviour. See picture: ![capture2](https://cloud.githubusercontent.com/assets/282687/19953176/7e8be232-a16b-11e6-8b76-ee9ab54a4ced.PNG)
7. Add configurable product into cart  

### Expected result

1. Picture of a product should be changing when selecting different colors of a product. 
2. Values of selected options (attributes) should be shown in the cart

### Actual result

1. Picture of a product is not changing when selecting different colors of a product.
2. The chosen option values are not shown in the cart (marked with yellow X)
![capture](https://cloud.githubusercontent.com/assets/282687/19953179/84b4bc60-a16b-11e6-81ca-0cf15b00e37c.PNG)
3. In case when I have different images for different colors of a product, chosen color correctly appears in the cart:
![14961576_10211319314164623_928511079_n](https://cloud.githubusercontent.com/assets/282687/19958288/641a264c-a19e-11e6-8076-40bd3b3b8fac.png)

### What I tested
1. The theme is not affecting the behaviour (I encountered the same behaviour when enabling Luma theme)
2. When I prepared product via GUI (for existing attribute Color with 3 manually added values), the chosen option value is shown in cart. I checked the attribute settings for my own attributes and they seem to be identical with those of integrated attribute Color)
3. I am 100% sure that picture of a product was changing when selecting different color of a product and 99% sure that also selected values of the attributes was showing up in the cart prior my upgrade to 2.1.2 (I upgraded from 2.1.1).

**Comment by jernejh** [comment]
ok, finally got a solution. attribute type was 'text' for my imported attributes. when i changed it to 'int' (even though the values for atributes are strings, for example blue, green, red), the chosen option values are now shown in the cart. 

product image is still not changing though, when selecting different options.

**Comment by ncaballerobol** [comment]
Recently ran into this same exact issue as well on 2.3.1 and came across the same solution except in my case it was for a Color Swatch attribute. I had to change the attribute's backend_type from VARCHAR to INT and the source model to Magento\Eav\Model\Entity\Attribute\Source\Table.   Also had to move over all of the attributes rows in the catalog_product_entity_varchar table into the catalog_product_entity_int table else the products would lose the associations. Had to run this command in the database (in our case the attribute ID was 212)

`INSERT INTO
	catalog_product_entity_int ( attribute_id, store_id, `value`, row_id)
SELECT
	attribute_id, store_id, `value`, row_id
FROM
	catalog_product_entity_varchar
WHERE
	attribute_id = 212`

After confirming that all of the rows were in the int table, then i went ahead and deleted them from the varchar table to clean it up

`DELETE
FROM
	catalog_product_entity_int
WHERE
	attribute_id = 212`

Still not sure what the actual issue is, wether the attribute was somehow created/edited wrong or some sort of import changed something (as this wasn't happening at first). We use the Magento API to import products, not sure if the API can create attributes... either way seems to have solved the issue.
