### ISSUE TITLE
Package fabpot/php-cs-fixer is abandoned

### ISSUE THREAD

**Issue by markshust** [magento/magento2#7310]
Receiving this error from composer on a fresh install of M2.1:
`Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friendsofphp/php-cs-fixer instead.`

### Preconditions
N/A

### Steps to reproduce
1. Install M2.1 via composer

### Expected result
1. This error shouldn't occur

### Actual result
`Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friendsofphp/php-cs-fixer instead.`

**Comment by quienti** [comment]
Already fixed https://github.com/magento/magento2/pull/4791

**Comment by markshust** [comment]
Why hasn't this been merged into the latest release?

**Comment by quienti** [comment]
This is merged in develop branch, so this is for Magento 2.2

**Comment by markshust** [comment]
Ok thank you

**Comment by nafisakanwal** [comment]
what is the solution to resolve this error ? I am getting the same error while executing the composer run command in magneto 2.1.6

Can anyone help 
Thanks in Advance

**Comment by shashidharg** [comment]
@nafisakanwal You will have to edit your composer.json file, as mentioned in #4791

**Comment by costel-petrescu** [comment]
Hi, @quienti 
I got the same error, when I executed the composer install -ignore-platform-reqs command in magento 2.1.6
As you mentioned, So I replaced fabpot/php-cs-fixer with friendsofphp/php-cs-fixer in composer.json.
But the error was same and it didn't work.
please, help me.
thanks.

**Comment by quienti** [comment]
Hi @costel-petrescu 
This is not really an error, it is just a message who it said fabpot/php-cs-fixer is abandoned and should be changed with friendsofphp/php-cs-fixer.
But, in Magento 2.2, this message was removed because it was fixed

Your Magento 2.1.6 will to work with no problem normally ;)

**Comment by costel-petrescu** [comment]
But when installing magento, it occurs the error like "php version check" in the first step.
I think there is problem here.
Though my php version is not required at installing condition as 7.1.1, anayway i skipped it with the command "composer install --ignore-platform-reqs".
Do you think what is the reason?
please, give me the way to solve it.
Thanks.

**Comment by quienti** [comment]
You install Magento with the interface ?

If yes, I thinks you should use a good version of php (http://devdocs.magento.com/magento-system-requirements.html)

If you use command lines for install, there are a specific command lines with Magento (http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-subcommands.html)

After install was finished, if you want upgrade your php version, you can but I think is not recommanded because Magento 2.1.6 was not compatible

**Comment by costel-petrescu** [comment]
you're right. but i'm going to install magento via a localhost on xampp. PHP version is 7.1.1 on xampp.
In this case, shall i have to change the php version or magento version?
Required version is ~5.6.5|7.0.2|7.0.4|~7.0.6. Aren't there any other methods exception changing php version? please, explain the way how to install magento 2.1.6 on xampp in detail.
Best regards.

**Comment by quienti** [comment]
Hummm, normally, you should not change php version of Magento, because there are some change to do in code.
But you can change php version of xampp with a specific install (https://sourceforge.net/projects/xampp/files/?SetFreedomCookie)
In this link, you have all php version for xampp, I hope you can find your install

And how install Magento ?
Hummm, just with the interface, you can succeed with no problem

**Comment by costel-petrescu** [comment]
thanks for your help.

**Comment by cotiga** [comment]
`cd /MAG/2/PATH`
`nano composer.json`
DELETE THE LINE (CTRL + K)
"fabpot/php-cs-fixer": "~1.2",
SAVE (CTRL + O)
CLOSE nano (CTRL + X)
`composer update`
`composer global require --dev friendsofphp/php-cs-fixer`
