### ISSUE TITLE
2.1.2 and double .html suffix problem

### ISSUE THREAD

**Issue by kunzi** [magento/magento2#7313]
Some product pages have .html suffix two times at the end or url. They also appear at the URL Rewrites section in admin.

Like this:
http://domain.com/product-url.html.html

**Comment by andidhouse** [comment]
@kunzi did you use the official data migration tool for migrating the products or did you create the products new?

**Comment by kunzi** [comment]
We imported some product data with UB data migration tool. It seems that the problem is related to that. Have to somehow fix the rewrites and hope the problem does not appear again.

**Comment by andidhouse** [comment]
I think the problem is still related to the import not to the UB data migration tool. We migrated products using the official data migration tool from magento and have the same issue. Seems like the import bug of products and URLs is still not solved 👎 ... now reported one year ago...

But you can try to export the product urls and import them again using the normal import / export magento tool. This should fix the problem i guess.

**Comment by kunzi** [comment]
Tried this with one product. 

Exporting all products and importing with only sku and url removed the extra .html, but presented another problem and product list in admin showed an unknown error and did not list any products. Tried then to remove the product via import and import all data again for that product. That resulted the .html.html problem again, but admin product list worked again... 

Also tried this: 
UPDATE url_rewrite SET request_path = REPLACE(request_path, '.html.html', '.html');
But that stopped into some duplicate entry error.

So still having this issue.

**Comment by kunzi** [comment]
The solution for us was first delete all product related rewrites in url_rewrite table, then save all products in admin's mass update functionality, then finally run the UPDATE command mentioned above to database. That removed all extra .html's from the rewrites.

Just importing did no good for us and created the .html.html just all over again so that indicates a bug in core import functionality at least in some cases.

**Comment by manV** [comment]
Thanks @kunzi for your solution. How did you save all product using mass update? I don't see that option in admin. The bulk options are delete, change status, and update attributes.

**Comment by kunzi** [comment]
@manV If I remember correctly I selected all products, selected update and set product website just to make it possible to save the products. In the end we also removed the .html suffix for products in SEO options.

**Comment by lucasvm** [comment]
I had the same problem in one of my clients site after migration from M1, do this:

`UPDATE url_rewrite SET request_path = REPLACE(request_path, '.html.html', '.htmllll');
`
`UPDATE url_rewrite SET request_path = REPLACE(request_path, '.htmllll', '.html');`

Sometimes when you run this update its possible to get duplicate entry error, thats why on first attempt im using a fake extension, then i will replace that fake extension with .html and should work!, that process has worked to me...not the ideal maybe but works.

Then run the indexer on command line  `php bin/magento indexer:reindex`

**Comment by HellgaM** [comment]
@lucasvm @kunzi 
I had the same issue because ".html" is set as a suffix for URLs and is added each time the reindex runs,
when for some reason original product url already has the ".html"

At first all ".html" has been removed from catalog tables:
`UPDATE  `catalog_product_entity_varchar` SET VALUE = REPLACE(VALUE, '.html', '') WHERE attribute_id IN(119, 120) 

UPDATE  `catalog_category_entity_varchar` SET VALUE = REPLACE(VALUE, '.html', '') WHERE attribute_id IN(117, 118) `
where 119, 120, 117, 118 are id's of "url_path" and "url_key"attributes for product/category. 

Secondly, all targets with ".html.html" has been removed with
`DELETE FROM `url_rewrite` WHERE target_path LIKE "%.html.html%"`

Then all ".html.html" in request_path where replaced with '.html'

`UPDATE IGNORE url_rewrite SET request_path = REPLACE(request_path, '.html.html', '.html');`

Important thins is **"IGNORE"** in update query above, so MySql won't stop on the first "Duplicate entry" error.

After that please select the rows which had "Duplicate error" and update them manually, checking what rewrite is correct using
`SELECT * FROM `url_rewrite` WHERE request_path LIKE "%.html.html%" `

For my 5500 products, I had to resolve manually only 2 rows and the issue was solved.
Then run the indexer on command line php bin/magento indexer:reindex
Wish you luck!
