### ISSUE TITLE
Colour swatches are being deleted and re-arrangeed after they have been created

### ISSUE THREAD

**Issue by wenpingguo** [magento/magento2#7369]
### Preconditions

1. Can reproduced in a fresh installed 2.1.1 and 2.1.2

### Steps to reproduce

1. Create 9 new swatches with colour code and save 
2. Delete top 2 colour swatches of the 9 and save 
3. create 2 new colour swatches with colour code and save

### Expected result

1. add two new colour swatches in the last with correct watches colour code
2. other swatches will not be affected

### Actual result

1. the colour swatches was re-arranged, colour code been removed
2. other colour swatches code was been changed.

here is  the video record of step2 and step3: http://take.ms/KB7zD
You can see in the video, I created new swatch '000000' with colour code is "#000000".
after save, the colour code for "000000" is been removed and colour code "#000000" was assigned to 
swatch "999999"

The situation is worse if you have over 200 colour swatches.

**Comment by sevos1984** [comment]
Internal ticket created MAGETWO-60956. Thanks for reporting

**Comment by magento-engcom-team** [comment]
@wenpingguo, thank you for your report.
We've created internal ticket(s) MAGETWO-60956 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @wenpingguo. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1230 by @serhii-balko in 2.2-develop branch
Related commit(s):
 - [07979b14d8be82ab878eaf386a3555d91efadeb2](https://github.com/magento/magento2/commit/07979b14d8be82ab878eaf386a3555d91efadeb2)
 - [2c15cea8f1c06a624b42c99a24c387d11af74333](https://github.com/magento/magento2/commit/2c15cea8f1c06a624b42c99a24c387d11af74333)

The fix will be available with the upcoming 2.2.5 release.
