### ISSUE TITLE
Product images gets removed from "Images And Videos" after validation alert.

### ISSUE THREAD

**Issue by candia** [magento/magento2#7372]
When adding a new product with an image, if a validation error occurs when trying to save the prodcut, the images gets removed from the "Images And Videos" section. If you fix the validation conflict and try to save the product again, an error will occur with "The file "/home/user/www/pub/media/tmp/catalog/product/o/r/pic.png" doesn't exist or not a file"

**Preconditions**

1. Magento CE 2.1.2
2. New Product 

### Steps to reproduce

1. Add new product
2. Add image to product
3. Force a validation error by using an already used URL Key for the product

### Expected result

Magento should remember the image that was added before validation occurred and save the product with the image. 
1. Create product with image

### Actual result

1. The file "/home/user/www/pub/media/tmp/catalog/product/o/r/pic.png" doesn't exist or not a file

I checked the pub/media/tmp and the image was added to the folder, however once I click save and validation is triggered the image gets removed from the pub/media/tmp.

**Comment by sevos1984** [comment]
Internal ticket created MAGETWO-60919. Thanks for reporting

**Comment by Ctucker9233** [comment]
I've had this same issue as well.

**Comment by 12impress** [comment]
I have the same problem as well.

**Comment by magento-engcom-team** [comment]
@candia, thank you for your report.
We've created internal ticket(s) MAGETWO-60919 to track progress on the issue.

**Comment by Rekha-periasamy** [comment]
Kindly let me know the fix for this issue.

**Comment by magento-engcom-team** [comment]
Hi @candia. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1140 by @nmalevanec in 2.2-develop branch
Related commit(s):
 - [263f71d0171171f33871344769dd20843ef6cc09](https://github.com/magento/magento2/commit/263f71d0171171f33871344769dd20843ef6cc09)
 - [4f6296ccb20cfbd5cd8814f4ba509d0e1acd4432](https://github.com/magento/magento2/commit/4f6296ccb20cfbd5cd8814f4ba509d0e1acd4432)

The fix will be available with the upcoming 2.2.5 release.

**Comment by magento-engcom-team** [comment]
Hi @candia. Thank you for your report. 
The issue has been fixed in magento/magento2#16597 by @swnsma in 2.2-develop branch
Related commit(s):
 - [d866b18757ca50bc97df4038a874a4bddf465a4c](https://github.com/magento/magento2/commit/d866b18757ca50bc97df4038a874a4bddf465a4c)
 - [bc00d8e059ba168694962249d09cd82f99e9ef46](https://github.com/magento/magento2/commit/bc00d8e059ba168694962249d09cd82f99e9ef46)

The fix will be available with the upcoming 2.2.7 release.
