### ISSUE TITLE
Pages not displayed on frontend 2.1.2

### ISSUE THREAD

**Issue by nmallepally** [magento/magento2#7392]
### Preconditions (*)
Magento 2.4-develop

### Steps to reproduce (*)
1. Make sure `Cache` is enabled
2. Go to `Content -> Pages`
3. Create new page, with _enabeld_ option
4. View page on FE (you should see page content)
5. Go back to the same page and _disable_ it and save.
6. View page on FE (it is not visible)
7. Go to that page on BE and _enable_ it and save.

### Expected result (*)
CMS page is visible on FE.

### Actual result (*)
CMS Page is not visible on FE after saving with _Disabled_ option and _Full Page Cache_ enabled.

-------------------------------------------------------------
**Additional information**
After clearing _Full Page Cache_ desired page is visible on FE.

**Comment by vasilii-b** [comment]
@nmallepally I don't see page url in admin panel neither in Front-End.Maybe you have a typo in url key ?

**Comment by nmallepally** [comment]
Hi @vasilii-b 
No i checked it, url key is right.
please find the clear images.
![pages not working](https://cloud.githubusercontent.com/assets/19605497/20268194/056d6ff6-aa76-11e6-9ef6-318af665235c.PNG)

![404 er](https://cloud.githubusercontent.com/assets/19605497/20268142/c3b61108-aa75-11e6-9387-e5508c62b3e8.PNG)

I had reindexed 5-10 times, no use. flushed static files and deployed static content.
still the page does not appear.

**Comment by vasilii-b** [comment]
@nmallepally on _2.2.0-develop_ works fine with Magento default theme and custom theme. Did you tried to use default theme ? Try to disable installed modules ( I see you have there _EMTHEMES_).

**Comment by nmallepally** [comment]
@vasilii-b Yes, I did try with it as well.
I disabled installed modules checked it. No use, the page does not appear.
Do you have any work around for the fix? it is blocking us from going live.

**Comment by vasilii-b** [comment]
@nmallepally I do not have for now, but I'll go into it deeper today.

**Comment by vasilii-b** [comment]
**I've got this issue after disabling, then re-enabling page.**
The problem was that _cache_ was enabled, especially **Full Page Cache**.
After running command `bin/magento cache:flush` page is visible in front-end.

This was done on Magento 2.1.1 and 2.1.2 versions.

@nmallepally try to do the same - clear cache.

@veloraven I think label `CMS` should be deleted and `Cache` added.

**Comment by tkacheva** [comment]
@nmallepally, @vasilii-b could you provide more detailed steps to reproduce. @vasilii-b does thew issue exist on 2.2 dev?

**Comment by vasilii-b** [comment]
@tkacheva, here you go:

### Steps to reproduce
1. Make sure `Cache` is enabled
2. Go to `Content -> Pages`
3. Create new page, with _enabeld_ option
4. View page on FE (you should see page content)
5. Go back to the same page and _disable_ it and save.
6. View page on FE (it is not visible)
7. Go to that page on BE and _enable_ it and save.

### Expected result
CMS page is visible on FE.

### Actual result
CMS Page is not visible on FE after saving with _Disabled_ option and _Full Page Cache_ enabled.

### Additional information
This was tested on Magento versions: 2.1, 2.1.2 and 2.2.0-dev.
After clearing _Full Page Cache_ desired page is visible on FE.

**Comment by mitabs** [comment]
Hello, I was experiencing some very similar issues and will share my two cents.

Magento CE 2.1.2, PHP 7, MySQL 5.6, CentOS 7
Started new at CE 2.0, recently upgraded a few times to 2.1.2.
Third party modules disabled.

I created a new page via the backend, and it would not show up on the frontend.  404s every time - even after server reboot, static compilation, upgrade to latest available dependencies (11/22/16), disable caching, manual run indexing.  New products were OK, and old CMS pages were OK.  No frontend javascript errors.  Nothing in exception.log.  I was receiving the Magento 404.

The issue ended up being what I believe is a new feature in v2.1 - allowing CMS pages to be linked to multiple storeviews (You can now assign a CMS page to multiple storeviews | v2.1 release notes).

I run a single store, so I had previously enabled Single-Store Mode (Stores->Config->General).  Because this was enabled, I wasn't getting the correct options on the Content -> Pages -> Add/Edit.  Specifically, I was missing "Pages in Websites".  Without that option, the pages were getting saved but without an entry for that field.  No insert was performed into table 'url_rewrites'.

I disabled single store mode and was able to see the correct options.  I chose the correct store view and everything works fine.

I believe this may be relevant because the OP submission also lacks the 'Store View' column.

![image](https://cloud.githubusercontent.com/assets/15962084/20550010/74c7851e-b0ff-11e6-89db-73ace02a4913.png)
![capture](https://cloud.githubusercontent.com/assets/15962084/20550071/f28440c8-b0ff-11e6-840d-673718481a81.jpg)

**Comment by nmallepally** [comment]
@vasilii-b @tkacheva @mitabs  
Same here, it worked and pages started to appear on the front end. when i chose the option to no for enabling single store mode on. pages on backend started showing as all store views.
so i had to go back on each page and save them again , then my pages started displaying on frontend.

Magento 2.1.1
![ssm](https://cloud.githubusercontent.com/assets/19605497/20562275/a52b09b2-b17a-11e6-9b00-d64bf2229069.PNG)

**Comment by CreamyG31337** [comment]
nice, disabling single store mode also fixes the bug where you can't edit the default welcome message or the copyright thing in the footer. 
this thing is so full of bugs. I can't imagine they do any testing at all.

**Comment by mattcoz** [comment]
I tried disabling single store mode and it has caused all sorts of problems. My theme is no longer being applied and I can't change it. I edit the design configuration and the edits don't persist.

**Comment by CreamyG31337** [comment]
I think I had to re apply my theme at each level before it worked. The validation is messed up for sure too. If I put "Welcome to our Canadian store!" for the welcome message it resets to default, but without the '!' it saves fine. Maybe set everything to default and change one thing at a time. Worst case you can probably figure out how to bypass this garbage and edit the database directly. That's the only way I can get my E-mail set up since the domain validation is outdated by a few years.

**Comment by mattcoz** [comment]
I tried applying it at every level, but the changes wouldn't stick. I reverted to single store mode and my theme is back, but my values for copyright, etc are not being used. This software drives me nuts.

**Comment by bluec** [comment]
Still a problem in 2.1.3 and as @mitabs pointed out it is caused by enabling single store mode. When single store mode is enabled, the "store view" for a page is not saved, and so the page will never be routed and always results in a 404 on the frontend.

**Comment by magento-engcom-team** [comment]
Updated issue description

**Comment by magento-engcom-team** [comment]
@nmallepally, thank you for your report.
We've created internal ticket(s) MAGETWO-75796 to track progress on the issue.

**Comment by avdb** [comment]
I will look into this one

**Comment by avdb** [comment]
I couldn't resolve this issue.

Reproduced on 2.2-develop branch.

This issue also occurs if you disable the single store mode.
It's also an issue for products, disable a product, visit the product page on the frontend (see a 404) and enables the product again. The 404 page is still visible on the frontend.

## Steps to reproduce

1. Disable product / page in the backend.
2. Visit product/page in frontend (get 404 page)
3. Enable product/page in the backend
4. Visit product/page in frontend (get 404 page)

Refreshing full page cache solves the issue.

**Comment by sarah-magentech** [comment]
Let's disable **Google Analytic** in the **SALES** tab, you will be able to edit page. For more information, please check this [blog post](https://www.magentech.com/case-studies/item/789-how-to-fix-magento-220-pages-showing-error) :)

**Comment by Jeeva-Rathinam** [comment]
Is your issue solved?

**Comment by sunilit42** [comment]
Helllo @avdb 

is there any solution?

**Comment by ChrHartwig** [comment]
We had the same problem and maybe I have a solution.

In our case it was the caching of 404-Pages in our varnish. After adding the following part to the vcl_backend_response of the varnish VCL, everythings works:

`if ( beresp.status == 404 ) {
set beresp.ttl = 0s;
}`

This part excludes all 404 from being cached by varnish. 

Greetings,
Christoph

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30061` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Ronak-Bhatti** [comment]
Hello 
After Enable page from Admin side go open SSH and go to your project directory
Then type the following command
          php bin/magento cache:flush

**Comment by engcom-Bravo** [comment]
Hi @nmallepally,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

<img width="1306" alt="Screenshot 2024-04-22 at 12 55 48" src="https://github.com/magento/magento2/assets/51680745/5b38a8e8-2247-43e1-9cd8-a52d8fe096c1">


<img width="1377" alt="Screenshot 2024-04-22 at 12 55 55" src="https://github.com/magento/magento2/assets/51680745/839cc467-e6ec-4be7-95e6-d4bdd3a653ad">


CMS page is visible on FE and the issue is no more reproducible.

Hence We are closing this issue.

Thanks.
