### ISSUE TITLE
Modal UI: clickableOverlay option doesn't work

### ISSUE THREAD

**Issue by thdoan** [magento/magento2#7399]
### Preconditions

1. Magento 2.1.2

### Steps to reproduce

1. Go into any template and create a modal widget with this code:

```
require(['Magento_Ui/js/modal/modal'], function(modal) {
  $('#some-element').click(function(e) {
    e.preventDefault();
    $('<p>Overlay content</p>').modal().modal('openModal');
  });
});
```

2. Click on `$('#some-element')` to show the overlay.
3. Click on the overlay (shadow).

### Expected result

1. According to the [documentation](http://devdocs.magento.com/guides/v2.0/javascript-dev-guide/widgets/widget_modal.html#modal_clickableOverlay), the default `clickableOverlay` value is `true`, which means "Close the modal window when a user clicks on the overlay".

### Actual result

1. Nothing happens (i.e., the overlay does not close). Even when you manually specify the option, it doesn't work:

`$('<p>Overlay content</p>').modal({ clickableOverlay: true }).modal('openModal');`

**Comment by BB-000** [comment]
+1 ,  The z-index of the popup is higher than the .modals-overlay, but the popup wrapper <aside> covers the whole screen area, making the overlay unclickable. 

Increasing the z-index of the .modals-overlay makes the click-to-close work, but the popup is then put behind whatever the background colour of the .modals-overlay is . . .

**Comment by erikhansen** [comment]
I've encountered this issue on multiple projects.

**Comment by erikhansen** [comment]
We created a workaround for this issue in a custom theme using a RequireJS mixin by adding the following files:

### `app/design/frontend/<VENDOR>/<THEME>/Magento_Ui/web/js/model/modal-mixin.js`

```
define([
    'jquery',
    'mage/utils/wrapper'
], function ($, wrapper) {
    'use strict';

    return function (modal) {

        modal.prototype.openModal = wrapper.wrap(modal.prototype.openModal, function(original) {

            var result = original();
            $('.' + this.options.overlayClass).appendTo('.modal-popup._show');
            //Setting z-index of inner-wrap to 900 so that it is actually clickable and not hiding behind the overlay
            $('.modal-inner-wrap').css('z-index', 900);
            return result;
        });

        return modal;
    };
});
```

### `app/design/frontend/<VENDOR>/<THEME>/requirejs-config.js`

```
var config = {
    config: {
        mixins: {
            'Magento_Ui/js/modal/modal': {
                'Magento_Ui/js/model/modal-mixin': true
            }
        }
    }
};
```

See this great article by Alan Storm for info on M2's RequireJS Mixins: http://alanstorm.com/the-curious-case-of-magento-2-mixins/

**Comment by miakusha** [comment]
Hi @thdoan thanks for report 
We've created internal ticket MAGETWO-63410 to address this issue.

**Comment by BB-000** [comment]
@erikhansen Unfortunately for me that fix works on desktop (popup) but breaks mobile (slide) modals...

**Comment by erikhansen** [comment]
@BB-000 Yeah, we discovered some issues with the code I posted previously and have since refactored and moved the code into a standalone extension called ClassyLlama_ModalEnhancements. I've attached it to this comment. Use at your own risk.

[ClassyLlama_ModalEnhancements.zip](https://github.com/magento/magento2/files/1010785/ClassyLlama_ModalEnhancements.zip)

**Comment by nntoan** [comment]
@erikhansen It's working. Please create a PR :)

**Comment by magento-engcom-team** [comment]
@thdoan, thank you for your report.
We've created internal ticket(s) MAGETWO-63410 to track progress on the issue.

**Comment by mak0605** [comment]
Hello I am looking for this issue #mm18in

**Comment by magento-engcom-team** [comment]
@mak0605 thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by SimonAnguish** [comment]
I have a quick solution for this. In a custom css file, you can add bottom: initial and overflow-y: inherit !important (or increase the specificity) to the .modal-popup class. This causes the modal to only cover the top line of the screen, but the content still shows.

**Comment by alpacode-pmakowski** [comment]
#distributed-cd hello, i am going take a look if can help a bit with that.

**Comment by magento-engcom-team** [comment]
@virtua-pmakowski thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @thdoan. Thank you for your report. 
The issue has been fixed in magento/magento2#15172 by @virtua-pmakowski in 2.2-develop branch
Related commit(s):
 - [abe727a3f74449c79f345fd1234ee2473c1fb576](https://github.com/magento/magento2/commit/abe727a3f74449c79f345fd1234ee2473c1fb576)

The fix will be available with the upcoming 2.2.5 release.

**Comment by shibinvr** [comment]
hi when upgrade with ClassyLlama_ModalEnhancements.zip module but still modal not close when click overlay. any idea why

**Comment by sidolov** [comment]
Hi @thdoan. Thank you for your report. 
The issue has been fixed in magento/magento2#16665 by @mageprince in 2.1-develop branch
Related commit(s):
 - [4c53cafc638476cdb631f38919b0b795c15db627](https://github.com/magento/magento2/commit/4c53cafc638476cdb631f38919b0b795c15db627)

The fix will be available with the upcoming 2.1.15 release.

**Comment by sidolov** [comment]
Hi @thdoan. Thank you for your report. 
The issue has been fixed in magento/magento2#16664 by @mageprince in 2.3-develop branch
Related commit(s):
 - [76ae28f82032a0af152d3285bedc1ffa46ff2055](https://github.com/magento/magento2/commit/76ae28f82032a0af152d3285bedc1ffa46ff2055)

The fix will be available with the upcoming 2.3.0 release.

**Comment by hamdrew** [comment]
I do not see this fix in the Magento 2.2.5 release

**Comment by BB-000** [comment]
.modal-popup { pointer-events: none; }

**Comment by zaximus84** [comment]
This is not fixed in 2.2. The CSS for pointer-events is present, but modal.js doesn't actually handle a click on the overlay. clickableOverlay is present in the default options, but it's not found anywhere else in the file (meaning it's not used). Comparing 2.1, 2.2, and 2.3, the _createOverlay method is lacking lines in 2.2.

**Comment by engcom-Charlie** [comment]
Hello @zaximus84 
Branch 2.2-develop was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3._
See Accepted pull requests and ported code for more details
So i close this issue.

**Comment by LiamKarlMitchell** [comment]
Still a problem in Magento 2.3.0

**Comment by sarkadiadam** [comment]
Hello, made it work correctly by applying a small css fix (if anyone is still interested):

```
.modal-popup {
    pointer-events: none;
    touch-action: none;
}
```
