### ISSUE TITLE
Multiline fields in forms have no visible label

### ISSUE THREAD

**Issue by navarr** [magento/magento2#7428]
### Preconditions

1. Magento CE 2.1.2
2. Custom \<uiComponent /> form

### Steps to reproduce

1. Create a \<field> 
2. Set it's formElement to multiline
3. Load the form in the browser

(Example \<field>):

        <field name="street">
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="label" xsi:type="string" translate="true">Street</item>
                    <item name="dataType" xsi:type="string">text</item>
                    <item name="size" xsi:type="number">2</item>
                    <item name="formElement" xsi:type="string">multiline</item>
                    <item name="visible" xsi:type="boolean">true</item>
                    <item name="source" xsi:type="string">general</item>
                    <item name="validation" xsi:type="array">
                        <item name="required-entry" xsi:type="boolean">true</item>
                    </item>
                </item>
            </argument>
        </field>

### Expected result

![](http://i.imgur.com/29uoXk9.png)

(The label "Street" to be visible to the left of the top input)

### Actual result

![](http://i.imgur.com/DxTYlsV.png)

The label ("Street" in this case) matches the following CSS rule:

    .admin__field legend.admin__field-label {
        opacity: 0;
    }

Rendering it invisible.

The less responsible for this [was added to the code in this commit](https://github.com/magento/magento2/blob/3e8aa279d3ba6d4754abd71ec404fc43921c9ec2/app/design/adminhtml/Magento/backend/web/css/source/forms/_fields.less#L258)

**Comment by tkacheva** [comment]
Internal ticket MAGETWO-61202

**Comment by magento-engcom-team** [comment]
@navarr, thank you for your report.
We've created internal ticket(s) MAGETWO-61202 to track progress on the issue.

**Comment by crisdiaz** [comment]
I´m working on it #distributed-cd

**Comment by magento-engcom-team** [comment]
@crisdiaz thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @navarr. Thank you for your report. 
The issue has been fixed in magento/magento2#14317 by @crisdiaz in 2.2-develop branch
Related commit(s):
 - [d1ea17d8371669963d9369bd6f2a5f3310a600db](https://github.com/magento/magento2/commit/d1ea17d8371669963d9369bd6f2a5f3310a600db)

The fix will be available with the upcoming 2.2.5 release.

**Comment by okorshenko** [comment]
Hi @navarr. Thank you for your report. 
The issue has been fixed in magento/magento2#14383 by @rostyslav-hymon in 2.3-develop branch
Related commit(s):
 - [8d524210dce13e544d05d534bc3d0291e83e0792](https://github.com/magento/magento2/commit/8d524210dce13e544d05d534bc3d0291e83e0792)

The fix will be available with the upcoming 2.3.0 release.
