### ISSUE TITLE
Special price on multi stores not updated on product save in product list

### ISSUE THREAD

**Issue by fchalet69** [magento/magento2#7433]
When you have multiple stores and you want to set a special price on a specific store (don't set it on default view), then the save of the product don't update the special price for the store. A workaround is to reindex all product flat data.

### Preconditions
1. Magento CE 2.1.0

### Steps to reproduce
1. Install Magento CE 2.1.0
2. Create a second website, store and store view
3. Configure price scope to be per-website
4. Enable Flat Catalog Product/Category
5. Reindex all
6. Create a simple product
7. Set a special on a store (not in default value)

### Expected result
1. Special price appear in product list

### Actual result
1. The price block is wrong on product list (it may display "as low as" but this is not the expected result)
2. Reindexing all product flat data will display the correct price block in product list

The problem is when you don't set the special price on default, then saving the product won't update the special price in the flat table.

**Comment by redelschaap** [comment]
Possible fix: #8450

**Comment by IlnitskiyArtem** [comment]
@fchalet69 Thanks for reporting this issue. 
Created internal issue MAGETWO-69943 to investigate and track this issue.

**Comment by magento-engcom-team** [comment]
@fchalet69, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by magento-engcom-team** [comment]
Hi @fchalet69. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24732` was closed as `non-reproducible` in `2.4-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.
