### ISSUE TITLE
The controller is not working

### ISSUE THREAD

**Issue by springimport** [magento/magento2#7442]
I want to add my actions to `customer/` route. [Example](http://alanstorm.com/magento_2_advanced_routing/) (URL Route Sharing).

### Steps to reproduce
1. Create a module `CustomerSurvey`.
2. Create a controller `MyVendor\CustomerSurvey\Controller\Survey\Test`
3. Create a controller `MyVendor\CustomerSurvey\Controller\Survey\My\Test`
4. Create a `routes.xml`.
5. Go to http://example.com/customer/survey/test.
6. Go to http://example.com/customer/survey/my/test.

*etc/frontend/routes.xml*
```xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:App/etc/routes.xsd">
    <router id="standard">
        <route id="survey" frontName="survey">
            <module name="MyVendor_CustomerSurvey"/>
        </route>
        <route id="customer">
            <module name="MyVendor_CustomerSurvey" after="Magento_Customer"/>
        </route>
    </router>
</config>
```

Example of controller
```php
<?php

namespace MyVendor\CustomerSurvey\Controller\Survey;

use Magento\Framework\App\Action\Context;
use Magento\Framework\View\Result\PageFactory;

class Test extends \Magento\Framework\App\Action\Action
{
    /**
     * @var \Magento\Framework\View\Result\PageFactory
     */
    protected $resultPageFactory;

    /**
     * @param \Magento\Framework\App\Action\Context $context
     * @param \Magento\Framework\View\Result\PageFactory resultPageFactory
     */
    public function __construct(
    Context $context, PageFactory $resultPageFactory
    )
    {
        $this->resultPageFactory = $resultPageFactory;

        parent::__construct($context);
    }

    /**
     * Default customer account page
     *
     * @return void
     */
    public function execute()
    {
        
        echo 1;
        exit;

        //return $this->resultPageFactory->create();
    }
}

```

### Actual result
1. http://example.com/customer/survey/test - working.
2. http://example.com/customer/survey/my/test - not working (404).

What is permissible level of nesting for the controller?

| Q | A |
| --- | --- |
| Magento version | 2.1.2 with sample data |
| PHP version | 7 x64 |
| Operating system | Windows 10 x64 |

**Comment by osmansorkar** [comment]
2nd url will be
http://example.com/customer/survey_my/test

In Magento 2 URL’s are constructed this way:
frontName   controler_folder_name   controller_class_name

Your Front Name= Customer
Your Controller Folder = Survey/my
Your Controller Class Name = test

If you user multi folder for your controller your must be use "_" between 2 controller Folder Name. 

Other wise Magento 2 decide 
Font name= Customer
Controller Folder= Survey
Controller Class= My
& First parameter= test 

You show 404 error due to you did not create  "My" class. 

![screenshot_2](https://cloud.githubusercontent.com/assets/10289018/20389172/840bc276-acf2-11e6-9abb-d1f862b1602f.png)
Directory structure
![screenshot_3](https://cloud.githubusercontent.com/assets/10289018/20389171/840bcc4e-acf2-11e6-8c5a-9324da96f1e5.png)

**Comment by veloraven** [comment]
@springimport thank you for your feedback.
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.

**Comment by springimport** [comment]
@osmansorkar It works. Thank you very much!

**Comment by osmansorkar** [comment]
@springimport Welcome :)
