### ISSUE TITLE
Inconsistent CSV file Import error:

### ISSUE THREAD

**Issue by Nym77** [magento/magento2#7495]
I am using a standard Luma installation with example and I am trying to add products in magento using an automatic generated csv file. 

- If I use the file BB-ProductsWorking.csv I am able to import the products and file is parsed without errors. 
![screen shot 2016-11-20 at 19 11 05](https://cloud.githubusercontent.com/assets/9418130/20465071/293a3bba-af55-11e6-92fc-e9e911ba9a7e.png)

- If I am using the file BB-Products.csv I obtain the following error ( Curly quotes used instead of straight quotes in row(s): )
![screen shot 2016-11-20 at 19 08 43](https://cloud.githubusercontent.com/assets/9418130/20465056/f9cf7246-af54-11e6-8db3-650f34152090.png)

- If I remove the rows from the above file the error does not disappear but is present in 4 different rows 
![screen shot 2016-11-20 at 19 15 49](https://cloud.githubusercontent.com/assets/9418130/20465096/e6d3f288-af55-11e6-9427-cf9a1f0dd8d6.png)

Please note also that all files are formatted using the same program and in particular raw 1 and 2 in both BB-ProductsWorking.csv and BB-Products.csv are identical. Therefore they both should be correctly parsed. 

### Preconditions

1. Magento Version: last current version with example PhP 7 installed in MAMP

### Steps to reproduce

1. import BB-ProductsWorking.csv and enjoy the results :-)
2. import BB-Products.csv and experience the error 

### Expected result

1. the file BB-Products.csv should be imported correctly or the error message should explain the reason of the failure 

### Actual result

1. see short description 

files for reproducing the behaviour 

[BB-Products.zip](https://github.com/magento/magento2/files/602216/BB-Products.zip)

**Comment by Nym77** [comment]
I did some deeper investigation. 
The file looks correct if you split it import less then 25 products at the time. If you try a larger amount you get the following error: 
"Curly quotes used instead of straight quotes in row(s):"

**Comment by veloraven** [comment]
@Nym77 thank you for your report.
Please identify which version of Magento you are running

**Comment by Nym77** [comment]
@veloraven Magento 2.1.2 CE 

I looked more into that and i found that a product what containing in the short description a " . This was a regular " not a curly one. However it was messing with the csv file.

Still the error report in magento was completely misleading as it was pointing to the wrong kind of error and to the wrong row.

Is there any documentation regarding the proper formatting of a csv file?

**Comment by veloraven** [comment]
@Nym77 thank you for the update.

**Comment by tobias-forkel** [comment]
@Nym77 I had exactly the same problem today. My product CSV file was fine, but for some reason I got the error message `Curly quotes used instead of straight quotes in row(s)`.

After two hours of headache I ended up using Google Spreadsheet.

1. Open Google Spreadsheet
2. File > New > Spreadsheet
3. Upload your xlsx or csv
4. Import your file to the new spreadsheet
5. Remove new lines
5.1 Edit > Find and Replace
5.2 Find `\n`
5.3 Replace with nothing
5.4 Check `Search using regular expressions`
5.5 Hit the button `Replace All`

In my case I had to remove new lines for the column `categories`. You may can skip step 5.

6. Export the spreadsheet via `File > Download as > CSV`
7. Import the downloaded file in System > Import

So it looks like TextEdit on OSx just broke the CSV format all the time during search / replace operations. I didn't try vim or nano.

**Comment by IlnitskiyArtem** [comment]
Hi, @Nym77. Internal ticket MAGETWO-{70803}, which tracks this GitHub issue, is in our issue backlog.

**Comment by magento-engcom-team** [comment]
@Nym77, thank you for your report.
We've created internal ticket(s) MAGETWO-70803 to track progress on the issue.

**Comment by piotrekkaminski** [comment]
This issue was moved to magento-engcom/import-export-improvements#48

**Comment by danrcoull** [comment]
for anyone coming across this issue, for me it was caused by having \" in any of the columns that are text based for example description and short_description
