### ISSUE TITLE
Bug: searchCriteria conditionType "IN" does not show any results

### ISSUE THREAD

**Issue by skynixukraine** [magento/magento2#7514]
**Preconditions**
1. Magento CE 2.1.2 without sample data is installed.
2. Test Category is created, ID:5
3. Test Sub category is created, ID:112
4. Test Product is created, assigned to the test sub category only, ID:112

**Steps to reproduce**

1. Run request: /index.php/rest/V1/products?searchCriteria[filter_groups][0][filters][0][field]=category_id&searchCriteria[filter_groups][0][filters][0][value]=5,112&searchCriteria[filter_groups][0][filters][0][condition_type]=in

**Actual and Expected result**
Expected result:
Getting JSON with total_products:1
Actual result:
Getting JSON with total_products:0

**Additional information**

This is related to this issue https://github.com/magento/magento2/issues/2892 

This seems, it is still an issue with REST API on Magento 2.1.2
Im using the following endpoint
http://bikebiz.local:4575/index.php/rest/V1/products?searchCriteria[filter_groups][0][filters][0][field]=category_id&searchCriteria[filter_groups][0][filters][0][value]=5,112&searchCriteria[filter_groups][0][filters][0][condition_type]=in

And this looks like Magento ignores condition_type in, and uses something like this category_id=5
as a result returns 0 products.

However, if I change order of values, e.g. [value]=112,5 it will use category_id=112 as a result it will return a bunch of products from category 112.

This shows that condition_type in completely does not work. Could you advice on file name where I can fix this please?

**Comment by veloraven** [comment]
@skynixukraine thank you for your feedback.
Please format your issue description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by skynixukraine** [comment]
Hello @veloraven 
I have updated the issue, let me know if you need more information from me please

**Comment by Sebastien-oxom** [comment]
Hello, 

I think the issue is how the quoting is done on the value. 
I've tried a GET /V1/products request with searchCriteria involving an IN statement, and I saw in my DB log : 

`
SELECT e.*, IF(at_status.value_id > 0, at_status.value, at_status_default.value) AS status, IF(at_visibility.value_id > 0, at_visibility.value, at_visibility_default.value) AS visibility FROM catalog_product_entity AS e
 INNER JOIN catalog_product_entity_int AS at_status_default ON (at_status_default.entity_id = e.entity_id) AND (at_status_default.attribute_id = '97') AND at_status_default.store_id = 0
 LEFT JOIN catalog_product_entity_int AS at_status ON (at_status.entity_id = e.entity_id) AND (at_status.attribute_id = '97') AND (at_status.store_id = 1)
 INNER JOIN catalog_product_entity_int AS at_visibility_default ON (at_visibility_default.entity_id = e.entity_id) AND (at_visibility_default.attribute_id = '99') AND at_visibility_default.store_id = 0
 LEFT JOIN catalog_product_entity_int AS at_visibility ON (at_visibility.entity_id = e.entity_id) AND (at_visibility.attribute_id = '99') AND (at_visibility.store_id = 1) WHERE (e.entity_id IN((SELECT cat.product_id FROM catalog_category_product AS cat WHERE (cat.category_id IN('266,267,269,270,276,278,279,280,281,282,285,286,287,288,289,290,292,293,294,295,297,298,299,300,301,302,303,304,305,306,307,310,311,312,313,314,316,317,318,319,320,321,322,475,490,499,512,532,534,539,541,545,557,559,565,566,569,576,577,589,605,608,619,631,665,679,691,694,696,697,698,699,700,708,718,719,746,751,755,763,786,797,798,822,827,882,923,930,957,1245'))))) LIMIT 100
`

The quoted IN statement, give the illusion of the "category_id = firstValue" @skynixukraine mentioned.

After investigations, I found that the value of the IN statement should be exploded by these lines  :

https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php#L2844-L2846

But, when I made the API call, `$value` was not a string at this point but a single item array containing the string from the API call.

I hope these informations will help you.

**Comment by veloraven** [comment]
@skynixukraine thank you for updating.

**Comment by skynixukraine** [comment]
Hi @veloraven 
Any news on the issue?
I tried magento 2.1.4, and this seems it's not fixed.

**Comment by altafhussain10** [comment]
@veloraven is this issue fixed? I am facing same issue in Mage 2.1.2 CE and Mage 2.1.3 EE.

**Comment by skynixukraine** [comment]
Hello @altafhussain10 

It has never been fixed even in Magento 2.1.5 And this seems they are not willing to fix this at all.
So, look for custom solutions.

**Comment by altafhussain10** [comment]
Hi @skynixukraine , thanks for the details. 
By the way, it seems like Magento is getting more stupid and ugly. I am using EE version and if they are not fixing the small issues, then there is no benefit of using it. I have already started kicking out magento butt and started moving parts from it. 

For example, I need phone verification in checkout address section, and it was hell just to place a custom phone field there, so I have created my own checkout application and used the REST APIs to integrate it with magento. 

The APIs has a lot of issues due to which i had to created custom APIs. 
It is extremely stupid that the default checkout is using REST APIs, but it is so deeply integrated to magento, that modifying it is f*****g time expensive. There does not seem any reason why the checkout is using API for this purpose. 

Anyway, I will try to find out a custom solution for my problem, and will soon stop paying thousands of dollars to magento for a product which sucks so hard that the sucking get ashamed of it. 

Please everybody, dont mind my language, but I am angry because of wasting a lot of time and money. This is not the only issue I have, I have issues with transferring old data from M1 to M2 

https://github.com/magento/data-migration-tool/issues/201

Which is never fixed. 

Thanks everybody

**Comment by RomanKrut** [comment]
@skynixukraine Hi. Thank you for your report. The internal ticket was created MAGETWO-70566

**Comment by magento-engcom-team** [comment]
@skynixukraine, thank you for your report.
We've created internal ticket(s) MAGETWO-70566, MAGETWO-73054 to track progress on the issue.

**Comment by aledefreitas** [comment]
Based off of @Sebastien-oxom response, I developed a *very dirty* fix for this problem while there is no fix published on this repository.

If anyone is interested the fix is as follows.

https://github.com/magento/magento2/blob/2.3-develop/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php#L2975-L2977
Add the following code after those lines:
```php
    if (($key == 'in' || $key == 'nin') && is_array($value) && isset($value[0]) && strpos($value[0], ',')) {
        $newValue = [];
        foreach($value as $val) {
                $newValue = array_merge($newValue, explode(',', $val));
        }
        $value = $newValue;
    }
```

**Comment by magento-engcom-team** [comment]
@skynixukraine, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
