### ISSUE TITLE
Error when submit customer/account/editPost form and session expired

### ISSUE THREAD

**Issue by edelepine** [magento/magento2#7515]
### Preconditions
1. Magento CE 2.1.2

### Steps to reproduce
1. Connect to any customer account.
2. Go to the Edit account information page `/customer/account/edit/`
3. Wait enough time until session expired. You can change the default cookie lifetime (3600 seconds) to reduce waiting and in order to reproduce bug fastest.
4. Submit directly form by clicking save button.

### Expected result
1. Should redirect to customer login page.

### Actual result
1. Display a fatal error 
 > Fatal error: Uncaught Error: Call to a member function getEmail() on null in vendor/magento/module-captcha/Observer/CheckUserEditObserver.php on line 131

**Comment by sevos1984** [comment]
Internal ticket created MAGETWO-61436, thanks for reporting

**Comment by magento-engcom-team** [comment]
@edelepine, thank you for your report.
We've created internal ticket(s) MAGETWO-61436 to track progress on the issue.

**Comment by RomaKis** [comment]
Working on this.

**Comment by magento-engcom-team** [comment]
Hi @edelepine. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1187 by @RomaKis in 2.2-develop branch
Related commit(s):
 - [9bb3dd3a4ec9319615af6094e66c2ac1b0d4ed4b](https://github.com/magento/magento2/commit/9bb3dd3a4ec9319615af6094e66c2ac1b0d4ed4b)

The fix will be available with the upcoming 2.2.4 release.
