### ISSUE TITLE
Sorting by Price in Catalog Product grid returns incorrect number of products.

### ISSUE THREAD

**Issue by axthor** [magento/magento2#7522]
Sorting by the Price column in the admin Catalog Product grid gives an incorrect "records found" count at the top of the grid. This occurs because when sorting by price, products with status set to "disabled" are ignored.
 
### Preconditions
1. Magento CE 2.1.2

### Steps to reproduce
1. Open the admin dashboard.
2. In the admin menu, navigate to Products > Catalog
3. Ensure that the status of one or more products is set to "disabled".
4. Note the "records found" product count at the top of grid.
5. Click in the Price column header to sort by price.
6. Note the updated "records found" product count. It should be lower that in Step 4 by the number of disabled products. 

### Expected result
1. The number of records found should remain the same when sorting on different columns in the Catalog Product grid. 

### Actual result
1. When sorting by price, the product count is reduced by the number of disabled products.

### Additional information
In the code, the relevant query is formed in magento/module-catalog/Model/ResourceModel/Product/Collection.php::_productLimitationPrice(). This behavior occurs because the price index (catalog_product_index_price) is used when sorting by price, and does not include disabled products.

**Comment by olysenko** [comment]
Hi, thank you for your report. Internal ticket was created MAGETWO-61355

**Comment by manthandhola** [comment]
Any updates on this issue?

**Comment by magento-engcom-team** [comment]
@axthor, thank you for your report.
We've created internal ticket(s) MAGETWO-61355 to track progress on the issue.

**Comment by RomaKis** [comment]
This bug isn't reproducible on 2.1-develop and 2.2-develop anymore.

**Comment by stephansteiner** [comment]
Problem still exists on a 2.2.3 project. I'll try to provide you with a dump containing all products

**Comment by ghost** [comment]
Any updates on this issue? We are facing the same issue for magento version 2.2.3

**Comment by magento2dev** [comment]
Any update on this issue ? @magento-engcom-team 

Thanks !

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by shikhamis11** [comment]
I think this is due to inner join condition in query

**Comment by engcom-Alfa** [comment]
Hi @axthor. Thanks for your collaboration!

We are not able to reproduce this issue on the fresh 2.4-develop instance. Everything works correctly.

**Manual testing scenario:**

1.Log in to Admin;
2. In the admin menu, navigate to Products > Catalog;
3. Ensure that the status of one or more products is set to "disabled";
4. Note the "records found" product count at the top of the grid;
5. Click in the Price column header to sort by price;
6. Note the updated "records found" product count;

**Actual Result:** 
The number of records found remains the same when sorted by different columns in the Product Catalog grid.
![screen](https://user-images.githubusercontent.com/51679138/71360059-33594800-2597-11ea-92f0-1f3d7c37bb2e.gif)

@axthor Could you take a look?
Thanks!

**Comment by engcom-Alfa** [comment]
Hi @axthor, I'm closing this PR now due to inactivity.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
