### ISSUE TITLE
Backend Security key broken for controllers with frontname not equal to route ID

### ISSUE THREAD

**Issue by AlexandreKhayrullin** [magento/magento2#7557]
### Preconditions
The Magento used is the "develop" branch.
PHP: PHP 7.0.10-1+deb.sury.org~xenial+1

### Steps to reproduce
1. Create a new module with a controller usable in the backend.
2. Define a new route for the controller (new adminhtml/routes.xml file) with a frontname different from the route ID.
3. Add the new controller to the menu and add the appropriate item to the ACL.
4. Log into the backend, locate the new item and click on it.

### Expected result
1. The new controller is executed.

### Actual result
1. The user is redirected back to the dashboard.

After a debugging session, it appears that the security key is incorrectly generated during either the creation of backend URLs or the security key validation.

If you place a breakpoint at the last line of \Magento\Backend\Model\Url::getSecretKey(), you'll notice the following discrepancy:
- While generating the security key used during the creation of the URL, the "$secret" string (the one that is hashed to form the security key) starts with the frontname.
- While checking the security key after having clicked on the link, the "$secret" string starts with the route ID instead.

**Comment by flancer64** [comment]
These are stack traces and secret sources for hashing in my case (Magento ver. 2.2.0-rc30).

Secret key generation for navigation links:
![secret_generate](https://user-images.githubusercontent.com/5052385/30794783-dff69bb2-a1d2-11e7-984e-6312951a9c0c.png)

Secret key validation on route action:
![secret_validate](https://user-images.githubusercontent.com/5052385/30794806-ffe821e8-a1d2-11e7-8db9-f06e4299b889.png)

My module's descriptors for routes & menu:

`./etc/adminhtml/routes.xml`

    <config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="urn:magento:framework:App/etc/routes.xsd">
        <router id="admin">
    
            <route id="fl32_login_as_route" frontName="loginas">
                <module name="Flancer32_LoginAs"/>
            </route>
    
        </router>
    </config>


`./etc/adminhtml/menu.xml`

    <config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Backend:etc/menu.xsd">
        <menu>
            <add id="Flancer32_LoginAs::customer_logged"
                    module="Flancer32_LoginAs"
                    action="loginas/logged"/>
        </menu>
    </config>

**Comment by magento-engcom-team** [comment]
@AlexandreKhayrullin, thank you for your report.
We've created internal ticket(s) MAGETWO-81949 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @AlexandreKhayrullin

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by lfolco** [comment]
I have a commit that I'm testing, please don't close this.

**Comment by ishakhsuvarov** [comment]
Hi @AlexandreKhayrullin. Thank you for your report. 
The issue has been fixed in magento/magento2#17650 by @lfolco in 2.3-develop branch
Related commit(s):
 - [2662dfaa3e6cf6c0131a6eea098631099e7683bc](https://github.com/magento/magento2/commit/2662dfaa3e6cf6c0131a6eea098631099e7683bc)
 - [a0dfb6de5ea98d7586a30cfebdbfd4d78c0e104b](https://github.com/magento/magento2/commit/a0dfb6de5ea98d7586a30cfebdbfd4d78c0e104b)
 - [35eba04973e3a9b32715038843acfba9d52bca6d](https://github.com/magento/magento2/commit/35eba04973e3a9b32715038843acfba9d52bca6d)
 - [600a18593b7c08601bf9e9c1841d538f6df4361d](https://github.com/magento/magento2/commit/600a18593b7c08601bf9e9c1841d538f6df4361d)
 - [062286ef1ea841289d3a1cdf862e5f2daa8954f9](https://github.com/magento/magento2/commit/062286ef1ea841289d3a1cdf862e5f2daa8954f9)
 - [c3d700aad6fe574c4f8c3b15c556c69a93fa0e30](https://github.com/magento/magento2/commit/c3d700aad6fe574c4f8c3b15c556c69a93fa0e30)
 - [be7c9614c66d6618d783a00adf0d9207aca259f3](https://github.com/magento/magento2/commit/be7c9614c66d6618d783a00adf0d9207aca259f3)
 - [fa8a222e8ea787ea1cc07e45ea0c00ea34459377](https://github.com/magento/magento2/commit/fa8a222e8ea787ea1cc07e45ea0c00ea34459377)
 - [b738ce6ba67548db35ead1d1e622bfa1b4647cdc](https://github.com/magento/magento2/commit/b738ce6ba67548db35ead1d1e622bfa1b4647cdc)
 - [af3507a9af254b3b723a66af52625cdbd48f8243](https://github.com/magento/magento2/commit/af3507a9af254b3b723a66af52625cdbd48f8243)

The fix will be available with the upcoming 2.3.0 release.

**Comment by sidolov** [comment]
Hi @AlexandreKhayrullin. Thank you for your report. 
The issue has been fixed in magento/magento2#18018 by @lfolco in 2.2-develop branch
Related commit(s):
 - [719f7b34dc1c297cfd3748bf3920f68d881ae3f2](https://github.com/magento/magento2/commit/719f7b34dc1c297cfd3748bf3920f68d881ae3f2)
 - [a0f38af994c0f40b773ed7be9711ec481b3147d0](https://github.com/magento/magento2/commit/a0f38af994c0f40b773ed7be9711ec481b3147d0)
 - [2b4384c603c0add4c56a29b41b6c0bb71a713b8a](https://github.com/magento/magento2/commit/2b4384c603c0add4c56a29b41b6c0bb71a713b8a)
 - [19aa0fdc12ca9085ba18e2eb6d919c0a503d5b44](https://github.com/magento/magento2/commit/19aa0fdc12ca9085ba18e2eb6d919c0a503d5b44)
 - [184f67fb0f29738273cf9a8c470e8115fc6bd3d2](https://github.com/magento/magento2/commit/184f67fb0f29738273cf9a8c470e8115fc6bd3d2)
 - [600a4b0f452eaf7aeae411198cdda873238d7a40](https://github.com/magento/magento2/commit/600a4b0f452eaf7aeae411198cdda873238d7a40)
 - [11d05fd96adedf2d5ee8ef5f5c2a07ecc1f38076](https://github.com/magento/magento2/commit/11d05fd96adedf2d5ee8ef5f5c2a07ecc1f38076)
 - [d935078abefb4742dac09bece446a6514364473d](https://github.com/magento/magento2/commit/d935078abefb4742dac09bece446a6514364473d)
 - [27aeecb114b0b7ef247d8e958a53bd9fe35e1a7d](https://github.com/magento/magento2/commit/27aeecb114b0b7ef247d8e958a53bd9fe35e1a7d)
 - [b08e8173ef58852fd816a30b95e92a5d2dfcd5c3](https://github.com/magento/magento2/commit/b08e8173ef58852fd816a30b95e92a5d2dfcd5c3)
 - [ba5b8cb2099e82ef94d29caaad3739cda946268a](https://github.com/magento/magento2/commit/ba5b8cb2099e82ef94d29caaad3739cda946268a)
 - [ccbb792ce3dccd39e67b7b5cf11e6241a11e7633](https://github.com/magento/magento2/commit/ccbb792ce3dccd39e67b7b5cf11e6241a11e7633)

The fix will be available with the upcoming 2.2.8 release.

**Comment by romanrabotaet** [comment]
Fix is wrong in 2.2.8.

**Comment by romanrabotaet** [comment]
Fix is wrong in 2.2.8.
code in 2.2.8 
    protected function _callbackSecretKey($match)
    {
        $routeId = $this->routeConfig->getRouteByFrontName($match[1]);
        return \Magento\Backend\Model\UrlInterface::SECRET_KEY_PARAM_NAME . '/' . $this->_url->getSecretKey(
            $routeId,
            $match[2],
            $match[3]
        );
    }

code in 2.3
    protected function _callbackSecretKey($match)
    {
        $routeId = $this->routeConfig->getRouteByFrontName($match[1]);
        return \Magento\Backend\Model\UrlInterface::SECRET_KEY_PARAM_NAME . '/' . $this->_url->getSecretKey(
            $routeId?:$match[1],
            $match[2],
            $match[3]
        );
    }

**Comment by richardgrey-netxtra** [comment]
Had this issue after upgrading to 2.2.8. Caused problems if the admin/startup/menu_item_id is set to redirect to a specific page after login, I was unable to access any of the adminhtml routes and was redirected back to the page defined in admin/startup/menu_item_id.

**Comment by waldok** [comment]
@richardgrey-netxtra, we have the same issue after upgrading to 2.2.8 from 2.2.7 (there was no issue on 2.2.7). Do you think this is caused by Magento bug or any 3rd party extension or theme? We have not tested yet on vanilla 2.2.8
Are you using WeltPixel Theme or any extensions from Mirasvit or Amasty?

**Comment by chrisputnam9** [comment]
Definitely still broken in 2.2.8 - can this be re-opened @sidolov ?

**Comment by sidolov** [comment]
Hi @chrisputnam9 , yes, we should reopen it if the issue still reproducing

**Comment by novikor** [comment]
Still is being reproduced on 2.3.1.

I`ll reopen and fix it when I have some time.

**Comment by vasilii-b** [comment]
2024, Magento 2.4.6-p6 - same dam issue!

![image](https://github.com/user-attachments/assets/cb4bb362-5407-4713-b5e1-e5bd7c458ff2)

cc @sidolov

**Comment by tufahu** [comment]
Yes the problem is with \Magento\Backend\Model\Url::getUrl() uses frontName for secretKey generation and when we want to call the controller action secretKey validation runs with router id , so mismatch happens.

The only solution is to use same id and frontName at backend :\ good to know
