### ISSUE TITLE
Default success messages not showing at frontend

### ISSUE THREAD

**Issue by deepak-netwin** [magento/magento2#7561]
I've installed magento version 2.1.1 and facing issues that Magento's default success/failure messages not showing at frontend on top of the page.

Example 1. If I add product to cart it doesn't show success message for adding product to cart however product is added to the cart.

2. I'm submitting contact us form, receiving email but success message not showing at top.

**Comment by veloraven** [comment]
@deepak-netwin thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by deepak-netwin** [comment]
@veloraven Don't you understand the issue? I think any developer should understand what I posted here. Just not expecting this kind of reply from the worlds best eCommerce development team and that too after 3 days.

The issue is straight forward.

1) I've isntalled Magento 2.1.1
2) Created my custom theme.
3) Custom as well as default (blank/luma) themes doesn't show success/failure messages which we normally see after adding product to cart, submitting forgot password form, successful registration etc.

Hope you understand this. Can't explain more than this. Sorry.

**Comment by veloraven** [comment]
@deepak-netwin the question is not in the raw understanding.
The question is in better visibility and faster understanding. It is much easier to understand what the problem is, when the issue is well-formatted and you see actual result, expected result and exact steps to reproduce. That's why when some user creates new issue he is proposed to follow bug report template.
And in order to avoid argues that some issue is simple enough to be described without template or it is not (and some times it can be very difficult to draw the line) we would like to see any issue formatted properly. 
I hope you understand this and next time will follow the template during issue creating.

**Comment by deepak-netwin** [comment]
@veloraven anything about the issue?

**Comment by veloraven** [comment]
@deepak-netwin is this issue still actual?
We were not able to reproduce it.

**Comment by Priyanka9582** [comment]
I'm also facing the same issue in Version 2.2.4

Preconditions
1. Magento version 2.2.6

Steps to reproduce 
1. Create a new Theme

Expected result 
1. No default message is displaying when product is added or any other action is performed when we expect to see default message.

Actual result 
1. To see Default Success, Error, Warning Messages When a product is added to cart or customer is login to account or customer put wrong credentials to login.

**Comment by latenights** [comment]
@Priyanka9582 Could be something in theme you created. Please make sure that:

1. Messages block is not removed in XML
1. Message block have existing template file e.g.:
`<block class="Magento\Framework\View\Element\Messages" name="messages" as="messages" template="Magento_Theme::messages.phtml"/>`

**Comment by Priyanka9582** [comment]
@latenights Thank you very much! I had removed Message block in catalog default.xml

**Comment by hiteshb247** [comment]
> 
> 
> @Priyanka9582 Could be something in theme you created. Please make sure that:
> 
>     1. Messages block is not removed in XML
> 
>     2. Message block have existing template file e.g.:
>        `<block class="Magento\Framework\View\Element\Messages" name="messages" as="messages" template="Magento_Theme::messages.phtml"/>`

Above code is not working in our live site(with https url) but same code is working http://35.456.781.89/xyz_wee url. Because in our live site with we are calling 2 apis and these apis are working live site before validating the code so in our point of view session getting expired because all other site it is working fine using above layout.

if you guys have any idea please guide us
