### ISSUE TITLE
Property does not have corresponding setter in class Magento\Quote\Api\Data\AddressInterface

### ISSUE THREAD

**Issue by allamgr** [magento/magento2#7571]
### Preconditions

1. Create a custom module and add a eav attribute to customer_address.
2. Add the extension attribute to Magento\Quote\Api\Data\AddressInterface.
3. Here is a link to download my custom module [https://drive.google.com/file/d/0B_ATVsq8N054c1dFdHU4emxGY28/view?usp=sharing](url)

### Steps to reproduce

1. Add product to cart
2. Proceed to checkout
3. Create new shipping address
4. Fill the reference field
5. Save the shipping address
6. Click next

### Expected result

1. The Payment method step should be showed

### Actual result

1. Property "Reference" does not have corresponding setter in class Magento\Quote\Api\Data\AddressInterface
![capture3](https://cloud.githubusercontent.com/assets/1780017/20633134/ae063d2c-b319-11e6-86c2-1d977ebedf99.PNG)

**I have already clean and flush cache, run setup:upgrade and setup:di:compile**

**Comment by veloraven** [comment]
@allamgr thank you for you report.
Please, also identify which version of Magento you are running.

**Comment by allamgr** [comment]
I'm using magento CLI version 2.2.0-dev.

Do I need to upgrade magento?

**Comment by veloraven** [comment]
@allamgr thank you for update.
No, you do not need to upgrade. This information just was not specified in your description.
Which Magento edition do you use? As I can see you mention custom address attributes.
Customer custom address attributes are available in Enterprise edition only.
If you use this one, please contact Magento support instead of posting your issue here.
If you use Community Edition please address your question at  [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) or [Magento Stack Exchange](http://magento.stackexchange.com/). As it is not a native behavior of Magento CE amd we can not treat it as an issue

**Comment by vzabaznov** [comment]
hi @allamgr thank you for your reporting, we will close this issue for now as no update more than 2 week was received, please feel free to write here or to open new issue if needed

**Comment by ghost** [comment]
What do you mean by custom attributes are only available in the Enterprise edition? This is not clearly stated anywhere - the checkout is described as highly customizable (which it is not whatsoever) and now I've discovered this bombshell when having the same issue as the original reporter.

Custom attributes cannot be added to customer addresses in Community Edition programmatically?

**Comment by peterjaap** [comment]
@xAvarice yes they can be added programmatically. What @veloraven meant is that only Magento Commerce has a GUI in the admin for adding custom atributes on the customer.
