### ISSUE TITLE
Coding standards: arrays

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#758]
I've gone through the [coding standards document](https://wiki.magento.com/display/MAGE2DOC/Magento+PHP+Coding+Standards+and+Practices) (that by the ways it's very well wrtitten :smile: Thanks for this. ), but I didn't find anything regarding the array declaration format.  
Since Magento 2 will support php 5.4+ we can use the clasic form `$a = array(1,2,3)` or the short form `$a = [1,2,3]`. I see in the code that both forms are used. 
- [Long format](https://github.com/magento/magento2/blob/master/app/code/Magento/AdminNotification/Model/Config/Source/Frequency.php#L38)
- [Short format](https://github.com/magento/magento2/blob/master/app/code/Magento/Backend/Controller/Adminhtml/Ajax/Translate.php#L69).  

I actually have 2 questions here: 
- Is this going to be standardized? (I know it's not that easy)
- What format do you encourage developers to use? (or is "use them as you like them"?)

**Comment by magento-team** [comment]
Hi @tzyganu. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1193 by @nmalevanec in 2.3-develop branch
Related commit(s):
 - 6d86db14751c3b152c2c34a37e89a89fe6e85166

The fix will be available with the upcoming patch release.

**Comment by magento-engcom-team** [comment]
Hi @tzyganu. Thank you for your report. 
The issue has been fixed in magento/magento2#14675 by @nmalevanec in 2.3-develop branch
Related commit(s):
 - [8c023494d9ee2f4350a91f8d2139a31689cb4512](https://github.com/magento/magento2/commit/8c023494d9ee2f4350a91f8d2139a31689cb4512)

The fix will be available with the upcoming 2.3.0 release.
