### ISSUE TITLE
Adding categories

### ISSUE THREAD

**Issue by mr-amirganishaikh** [magento/magento2#7602]
### Preconditions

1. Magento 2.1.2
2. PHP 5.6.25
3. Linux OS on server

### Steps to reproduce

1. In Admin panel > Products > Click on Categories 

### Expected result

1. It should open categories page

### Actual result

1. It is opening the page but it continuously showing loading screen over it.
![download-issue](https://cloud.githubusercontent.com/assets/8222422/20699704/b73115bc-b62e-11e6-8ba1-44c916a9241f.png)

**Comment by veloraven** [comment]
@shaikhamir thank you for your feedback.
Was it clear install or upgrade from some previous version?
Have you tried to clear browser cache including offline website data? 
Please also provide exact magento version you are running and details of your environment: OS, versions of PHP, MySQL and web-server.

**Comment by mr-amirganishaikh** [comment]
It is installed not upgraded.

Yes, it is due to browser cache. I tried it in a different browser and now it is working perfectly.

Does it means I have to clear cache each time I have to use Admin panel?

**Comment by veloraven** [comment]
@shaikhamir thank you for your update.
No, it does not mean that you have to clear browser cache each time in order to use Admin panel. It might happen after upgrade from previous version or if it was clear install but previously another Magento version was installed with the same URL. 
To avoid the same issue in future you can turn on the following option in admin area:
Stores -> Configuration -> Advanced -> Developer -> Static Files Settings -> Sign Static Files = Yes
