### ISSUE TITLE
When saving the cms page getting 403 forbidden error in development mode .

### ISSUE THREAD

**Issue by KalaiarasanSeetharaman** [magento/magento2#7603]
### Version of PHP , Magento

1. We are using Nexcess server with PHP 7.0.13, Mysql 5.6.32-78.0, Apache 2.2.31
2. Magento 2.0.6 in development mode . With cache enabled. We will not update the version

### Error while saving

1.In Backend  When while saving the cms page or block content shows 403 Forbidden error.
2. In local it is working fine but it is in default mode. 
3. 

### Need to save

1. It should save properly 

### Screen shot

1. [Screenshot, logs]
![screenshot from 2016-11-29 12 44 54](https://cloud.githubusercontent.com/assets/16400150/20700160/ac2a1116-b631-11e6-8170-816fbc9ce2a6.png)

**Comment by veloraven** [comment]
@KalaiarasanSeetharaman thank you for your feedback.
According to your screenshot it's rather a question of permissions than of Magento functionality. Please check that permissions are configured properly.

**Comment by KalaiarasanSeetharaman** [comment]
@veloraven I have given full permission to as 777 . But it is not working

**Comment by IlnitskiyArtem** [comment]
@KalaiarasanSeetharaman, Thanks for reporting this issue. 
We've created internal ticket MAGETWO-70324 to address this issue.

**Comment by magento-engcom-team** [comment]
@KalaiarasanSeetharaman, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
