### ISSUE TITLE
A more verbose message when the db is not up to date.  

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#761]
Right now, when the database is not up to date you just get a message saying "Looks like database is outdated. Please, use setup tool to perform update".  
I know that running the setup tool should solve the problem, no matter what the out of sync module is, but as a developer I would like to know what module is not updated yet.  
This can simply be solved if the method `Magento\Framework\Module\Plugin\DbStatusValidator::isDbUpToDate` returned the name of the outdated module instead of false and in `aroundDispatch` instead of checking `if (!$this->isDbUpToDate())` just check `if ($this->isDbUpToDate() !== true)`

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-31536

**Comment by buskamuza** [comment]
Hi @tzyganu , the implementation is already available in the repository. Let us know if you have any concerns about new message.

**Comment by tzyganu** [comment]
@buskamuza I've seen the changes. Much better now. thank you.

**Comment by magento-engcom-team** [comment]
Hi @tzyganu. Thank you for your report. 
The issue has been fixed in magento/graphql-ce#804 by @sedonik in 2.3-develop branch
Related commit(s):
 - [439830da50d2e54e112cd5583cae5bbd4752dfa4](https://github.com/magento/graphql-ce/commit/439830da50d2e54e112cd5583cae5bbd4752dfa4)
 - [80b848a36567deb2540f4cfd6c3d005dfa0bf25e](https://github.com/magento/graphql-ce/commit/80b848a36567deb2540f4cfd6c3d005dfa0bf25e)
 - [6550d06bb660d5c16da93b0cc7ffcbca57ebf735](https://github.com/magento/graphql-ce/commit/6550d06bb660d5c16da93b0cc7ffcbca57ebf735)
 - [ab4e73654bb2b9eceb010e6adc3368435e696326](https://github.com/magento/graphql-ce/commit/ab4e73654bb2b9eceb010e6adc3368435e696326)
 - [1e821dd8aa6f11c9fbef3c2f6b118c03c3b17a92](https://github.com/magento/graphql-ce/commit/1e821dd8aa6f11c9fbef3c2f6b118c03c3b17a92)
 - [594cb63165d1552e5e39eb4e54375a1367b56600](https://github.com/magento/graphql-ce/commit/594cb63165d1552e5e39eb4e54375a1367b56600)
 - [295372e3ba09b1715370d994b17d44391c2eb88d](https://github.com/magento/graphql-ce/commit/295372e3ba09b1715370d994b17d44391c2eb88d)
 - [063950ff18de2e9ee96b5cbc79f4431a4210f0b0](https://github.com/magento/graphql-ce/commit/063950ff18de2e9ee96b5cbc79f4431a4210f0b0)
 - [10d20bf302f7676d7b7801b7b78f0ff61f630e37](https://github.com/magento/graphql-ce/commit/10d20bf302f7676d7b7801b7b78f0ff61f630e37)
 - [0809b691d5406fef955c46f18aef14d21def24c8](https://github.com/magento/graphql-ce/commit/0809b691d5406fef955c46f18aef14d21def24c8)
 - [d2039f2cfea4a731791b4c340fb9cb73979f04f7](https://github.com/magento/graphql-ce/commit/d2039f2cfea4a731791b4c340fb9cb73979f04f7)
 - [facce4c963381ef3c43ac0d01726820537c2f7dd](https://github.com/magento/graphql-ce/commit/facce4c963381ef3c43ac0d01726820537c2f7dd)
 - [7653126e8eba4593cc7433715312540062af3508](https://github.com/magento/graphql-ce/commit/7653126e8eba4593cc7433715312540062af3508)

The fix will be available with the upcoming 2.3.4 release.

**Comment by VladimirZaets** [comment]
Hi @tzyganu. Thank you for your report. 
The issue has been fixed in magento/magento2#25864 by @serhiyzhovnir in 2.4-develop branch
Related commit(s):
 - [2be777942056985a81371890cfc010d43c47bccd](https://github.com/magento/magento2/commit/2be777942056985a81371890cfc010d43c47bccd)
 - [83fadc4a406bbe6500034f46ee3802b4c408cb08](https://github.com/magento/magento2/commit/83fadc4a406bbe6500034f46ee3802b4c408cb08)
 - [a7f6e2d895d3c818d52b318349b5e7d03e06df30](https://github.com/magento/magento2/commit/a7f6e2d895d3c818d52b318349b5e7d03e06df30)
 - [ee115feeb5d412c69d3e8a8fc9b58e7d406207e6](https://github.com/magento/magento2/commit/ee115feeb5d412c69d3e8a8fc9b58e7d406207e6)
 - [21bc869ce9f6992846a3ff71b6ac07f3d20588a8](https://github.com/magento/magento2/commit/21bc869ce9f6992846a3ff71b6ac07f3d20588a8)

The fix will be available with the upcoming 2.4.0 release.
