### ISSUE TITLE
frontend_labels always empty

### ISSUE THREAD

**Issue by ghost** [magento/magento2#7626]
No matter how an attribute is created, frontend_labels is always null...

Magento 2.1.2
PHP 7.0.8

1. Create product atrribute
2. Call the attribute 

Call attribute `products/attributes/auto_artikelnummer`

### Actual result

`{
	"is_wysiwyg_enabled": false,
	"is_html_allowed_on_front": false,
	"used_for_sort_by": false,
	"is_filterable": false,
	"is_filterable_in_search": false,
	"is_used_in_grid": false,
	"is_visible_in_grid": false,
	"is_filterable_in_grid": false,
	"position": 0,
	"apply_to": [],
	"is_searchable": "1",
	"is_visible_in_advanced_search": "1",
	"is_comparable": "0",
	"is_used_for_promo_rules": "0",
	"is_visible_on_front": "1",
	"used_in_product_listing": "0",
	"is_visible": true,
	"scope": "global",
	"attribute_id": 163,
	"attribute_code": "auto_artikelnummer",
	"frontend_input": "text",
	"entity_type_id": "4",
	"is_required": false,
	"options": [],
	"is_user_defined": true,
	"default_frontend_label": "Artikelnummer",
	"frontend_labels": null,
	"backend_type": "varchar",
	"is_unique": "0",
	"validation_rules": []
}`

frontend_labels is always null
validation_rules is always an empty array

### Expected result

`{
	"is_wysiwyg_enabled": false,
	"is_html_allowed_on_front": false,
	"used_for_sort_by": false,
	"is_filterable": false,
	"is_filterable_in_search": false,
	"is_used_in_grid": false,
	"is_visible_in_grid": false,
	"is_filterable_in_grid": false,
	"position": 0,
	"apply_to": [],
	"is_searchable": "1",
	"is_visible_in_advanced_search": "1",
	"is_comparable": "0",
	"is_used_for_promo_rules": "0",
	"is_visible_on_front": "1",
	"used_in_product_listing": "0",
	"is_visible": true,
	"scope": "global",
	"attribute_id": 163,
	"attribute_code": "auto_artikelnummer",
	"frontend_input": "text",
	"entity_type_id": "4",
	"is_required": false,
	"options": [],
	"is_user_defined": true,
	"default_frontend_label": "Artikelnummer",
        "frontendLabels": [{
          "storeId": 0,
          "label": "Artikelnummer"
         }],
	"backend_type": "varchar",
	"is_unique": "0",
	"validation_rules": []
}`

Is this a bug or do I have something wrong configured in Magento?

**Comment by veloraven** [comment]
@oluijks thank you for feedback.
Please add expected result to the issue description.
If you are looking for advise please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. As  GitHub issue tracker is intended for technical issues only.

**Comment by RomanKrut** [comment]
@oluijks Hi. Thanks for your feedback. The internal ticket was created MAGETWO-70769

**Comment by magento-engcom-team** [comment]
@oluijks, thank you for your report.
We've created internal ticket(s) MAGETWO-70769 to track progress on the issue.

**Comment by facundocapua** [comment]
#distributed-cd

**Comment by magento-engcom-team** [comment]
@facundocapua thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
HI @oluijks thank you for you report, this issue has already fixed in 2.3-dev branch and will be available on 2.3.1 release.
![selection_299](https://user-images.githubusercontent.com/40756439/51899994-db34b880-23bc-11e9-8119-b1269bf0f9c9.png)
