### ISSUE TITLE
 in static folder front end & adminhtml directories are missing

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#763]
front end and admin theme missing.I mean in static folder front end & adminhtml directories are not there.From starting onwards these  directories are not there.even after pull also.can you help any one?

**Comment by rabee3** [comment]
I dont see `dev/tools/Magento/Tools/View/deploy.php` there. am on master branch.

**Comment by RohitSavaliya** [comment]
I install magneto 2. it is working good, but on home page and all other pages including admin panel a JavaScript error occurred

the error is :

```
NetworkError: 404 Not Found - http://localhost:8080/pub/static/frontend/Magento/luma/en_US/js-translation.json"
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
$.mage.translate.add(JSON.parse(string));
```

then I explore location  `/pub/static/frontend/Magento/luma/en_US/` 
and found that the file is there when open the file it is contain just two square bracket `[]`.

i dont know why magento show that file is not found, because it is already there

I already delete folders in pub/static directory and then re-run the deploy command from cmd

php bin/magento setup:static-content:deploy
but it is not work for me.
