### ISSUE TITLE
Magento 2.1.x No support for PHP7.1

### ISSUE THREAD

**Issue by BigL** [magento/magento2#7663]
### Preconditions

1. PHP 7.1.0RC6 (cli) ( NTS )
2 . Magento CLI version 2.1.2

### Steps to reproduce

1. ./bin/magento setup:upgrade
2. ./bin/magento setup:di:compile
3.

### Expected result

1. successful compiled DI

### Actual result

1.Repositories code generation... 1/7 [====>-----------------------]  14% 1 sec 42.0 MiBPHP Fatal error:  Cannot use 'Void' as class name as it is reserved in /data/vendor/magento/module-sales/Controller/Adminhtml/Order/Creditmemo/Void.php on line 10

This doesn't happen on PHP7.0

**Comment by maksek** [comment]
We are not supporting PHP 7.1 yet.

**Comment by cscd98** [comment]
@maksek When? :)

**Comment by ghost** [comment]
In order to compile I changed it to Voided. I know it broke something but I havent found it yet...
Cannot use 'Void' as class name as it is reserved in app/code/Magento/Sales/Controller/Adminhtml/Order/Creditmemo/Void.php on line 10
Cannot use 'Void' as class name as it is reserved in app/code/Magento/Sales/Controller/Adminhtml/Order/Invoice/Void.php on line 9

**Comment by dmitrii-fediuk** [comment]
My fix: https://example.com/t/2433
**None of the Magento 2 functionality is broken.**

**Comment by QWp6t** [comment]
PHP 5.6 officially no longer under active support. 

Might be time to revisit this issue.

**Comment by orlangur** [comment]
@dmitry-fedyuk, your fix is lame.

You can get an idea for proper fix from https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/Controller/Adminhtml/Product/NewAction.php#L13 ;)

**Comment by davidalger** [comment]
This issue has been addressed via PR #8609. Closing
