### ISSUE TITLE
Zend_Validate_Hostname add supporting of *.shop TLD

### ISSUE THREAD

**Issue by oleksii-lisovyi** [magento/magento2#7697]
Hi guys,

I found, that there is no ability to register customer with email with TLD .shop.
Can you please fix it?

### Preconditions
1. Magento 2.1.* installed.

### Steps to reproduce

1. Go to register page.
2. Try do register with email test@my.shop.

### Expected result
1. Customer successfully created.

### Actual result
1. Customer is not able to register account.
Screenshot:
![magento2_invalid_email_for_shop_tld](https://cloud.githubusercontent.com/assets/3918875/20924334/953b9bea-bbb9-11e6-8e7c-51aa1a2bef33.png)

The same issue is in Magento 1.9.* ZF. Do I need to create new one issue for M1?

**Comment by ihor-sviziev** [comment]
This issue caused by https://github.com/zendframework/zf1/issues/728 that used in Magento 1.x and Magento 2.x for email validation. For this issue we have answer that ZF1 is reached it's End Of Life, so would be great to replace using Zend_Validate to similar validator from ZF2, or another one.

Also Oleksii created the same issue for ZF2: https://github.com/zendframework/zend-validator/issues/139

**Comment by hostep** [comment]
This is probably a duplicate of https://github.com/magento/magento2/issues/4547 ?

**Comment by oleksii-lisovyi** [comment]
Yes. Thanks for catching!
