### ISSUE TITLE
In magento 2.1.2, with Configurable product view page when i click on add to cart button with selecting color attribute , product is not adding to the cart and redirect to the same page.

### ISSUE THREAD

**Issue by shakilagc** [magento/magento2#7714]
### Preconditions

1. open any configurable product , on product detail page click on add to cart button
2. Message "You need to choose the options for your item" showing after clicking add to cart button 

### Steps to reproduce

1. open any configurable product , on product detail page click on add to cart button
2. Message "You need to choose the options for your item" showing after clicking add to cart button 
 here is the screenshot http://imgur.com/a/JzOPY

here is my product detail page 
http://s-a.store/arabic-product.html
try to add this product to cart.

### Expected result

1. product should be added to the cart without redirect to same page.

### Actual result

1. Product is not added to the cart after clicking add to cart button on product detail page. here is the screenshot http://imgur.com/a/JzOPY

**Comment by TommyKolkman** [comment]
I've had this before. My simple product was out of stock then - checked that one?

**Comment by Corefix** [comment]
Yep this is a problem, i tracked down the issue to this commit:

https://github.com/magento/magento2/commit/08079204d7b669d8f3069db3dc7c47e85354c31a#diff-399a85a40d4acb52d7fd1cb0b79b9d0a

When asking for a configurable products children, we are no longer getting a list filtered by stock because this was added:

->setFlag('has_stock_status_filter', true)

I would hope someone from Magento or the community would remove this again :-)

**Comment by smoskaluk** [comment]
Please advise, is this issue relevant for latest Magento version (2.1.7), I can't reproduce it.

**Comment by magento-engcom-team** [comment]
@shakilagc, thank you for your report.
We were not able to reproduce this issue on latest 2.1.x by following the steps you provided. If you'd like to update it, please reopen the issue.
