### ISSUE TITLE
Payflow Payment error message unused. An error occurred on the server.

### ISSUE THREAD

**Issue by H3dz** [magento/magento2#7721]
When using Payflow to make a payment if the transaction fails the error message will always be
An error occurred on the server. Please try to place the order again.

### Preconditions
1. Magento version 2.1.2
2. PHP 7.0.11
3. MySQL 5.6

### Steps to reproduce
1. Configure Payflow
2. Make a purchase with an invalid credit card

### Expected result
1.  The message displayed should be "Transaction has been declined"

### Actual result
1. The message is "An error occurred on the server. Please try to place the order again."

Fix

In app/code/Magento/Payment/view/frontend/templates/transparent/iframe.phtml
replace
`message: $t('An error occurred on the server. Please try to place the order again.')`
with
`message: $t(<?php echo json_encode($params['error_msg']); ?>)`

**Comment by YevSent** [comment]
Hi, @H3dz, this is expected behavior. Magento payment solutions don't provide specific information about fails, only global messages.

Developer or merchant can find more information about fail in log, but customer should not see this details.

**Comment by joebusby** [comment]
This message is confusing for customers and in fact there was no processing error, there was a failure to process the payment method.  It should say something like:
"Payment processing process failed"   so that customers can try another payment method instead of calling the vendor to tell them there is something wrong with their server, when there is nothing wrong with the server.  We get these calls frequently.
