### ISSUE TITLE
uiClass Objects do not Deep Copy Observable defaults

### ISSUE THREAD

**Issue by astorm** [magento/magento2#7749]
### Preconditions
Magento CE, 2.1.x, installed via `composer create-project` Google Chrome's javascript engine.  Other system details not relevant. 

### Steps to reproduce

1. Create a RequireJS based program, per instructions below

2. Run RequireJS program

### Expected result
The `foo` property of `object1` retains its `The Default Value` value.  The `foo` property is a different object in each instantiated object.

### Actual result
The `foo` property of `object1` is linked to that of `object2`'s.  i.e. the observable object is not deep copied. 

Context/The Program
--------------------------------------------------
Here's the program to run per the instructions above.  This is a simplified program to demonstrate the bug, which can crop up in any number of places that rely on `uiClass`, `uiElement`, and `uiCollection` objects. 

    requirejs(['ko','uiClass'], function(ko, Class){
        //create a new class
        var CustomClass = Class.extend({
            'defaults':{
                'foo': ko.observable('The Default Value'),
                'bar':{}
            }
        });
        
        object1 = new CustomClass();
        object2 = new CustomClass();        
        
        console.log(object1.foo());
        console.log(object2.foo());
        
        object2.foo('A non-default value');
        
        console.log(object1.foo());
        console.log(object2.foo());        
        
        //returns true, indicating the same object
        console.log( object1.foo === object2.foo );
        
        //returns false, indicating different objects.
        //i.e. regular objects are deep copied, observables not
        console.log( object1.bar === object2.bar );
    });
    
If you run this program, the `foo` observables remain linked in each object.  The reason for this appears to be the core code in `class.js` that copies over the `defaults` values 

    #File: vendor/magento/module-ui/view/base/web/js/lib/core/class.js
    initConfig: function (options) {
        /* ... */    
        var defaults    = this.constructor.defaults,
            config      = utils.extend({}, defaults, options || {}),
        /* ... */
    }
    
The intention of the `extend` method of the `mageUtils` module (`utils.extend` above)  is a **deep** copy of the values in `default`.  However, the `mageUtils` `extend` method fails to deep copy observables.  Consider this sample program

    requirejs(['mageUtils','ko'], function(utils, ko){
        var test1 = {foo:ko.observable('test'),bar:{}};
        var test2 = utils.extend({}, test1);
        console.log(test1.foo === test2.foo);
        console.log(test1.bar === test2.bar);
    });

The `bar` object is cloned/deep-copied, the `foo` object (an observable) is not.  

This is not the expected behavior of a general purpose object system. It will lead to many subtle bugs in core team, and third party, programs that attempt to utilize the `uiClass` system. i.e. this is a bug, not a new feature request.

**Comment by zetlen** [comment]
First, thanks for the level of detail in this report. You're right that the "deep copy" behavior of `.extend()` does not deeply clone all types of object. Deeply cloning JavaScript objects that cannot be serialized is a non-trivial problem that can surprise you in subtle ways; this occurs in all systems that try to do this, including ours. [You can see here that the Core code delegates to `jQuery.extend()`](https://github.com/magento/magento2/blob/develop/lib/web/mage/utils/objects.js#L223-L229). And you can see in the [jQuery documentation for that method](http://api.jquery.com/jQuery.extend/) that "custom objects" will not be "reconstructed".

Because object methods can close over arbitrary state, and "classes" are not required in JS to declare their own serialization strategy, it's impossible to write a single-purpose algorithm that will clone any type of object, including its circular references, prototype chain, or its enclosed state. So `jQuery.extend` doesn't try, and neither do competing implementations like `lodash.cloneDeep`. Even for something as straightforward (and fundamental to our system) as Knockout observables, there are too many questions for a general algorithm. Should the cloned observable clone from the current value, or create a computed observable that stays in sync with the first observable? Should subscriptions be copied? The only safe choice is to not attempt to clone the object.

However, you're also right to observe that this can cause subtle bugs when a developer provides a constructed object to the `defaults` configuration. We'll clarify this in documentation! In the meantime, attaching any complex object might be best done by overriding the `initConfig` method of your custom class. *(It's worth mentioning here that we recommend using `uiElement.observe()` instead of directly creating Knockout observables.)*

#### Suggested workaround
```js
var CustomClass = Class.extend({
    'defaults':{
        'foo': 'The Default Value',
        'bar':{}
    },
    initConfig: function() {
        // Call the parent method to extend `this` with config
        this._super(); 
        // Create an observable belonging only to this instance, if one was not provided in config
        if (!ko.isObservable(this.foo)) {
            this.foo = ko.observable(this.foo);
        }
    }
});
```

I recognize that this seems verbose. We may add a future behavior to `defaults` so that instead of an object literal, it can optionally be a function that returns an object literal. The function would be called for every new instantiation, so there would no longer be a deep copy issue.

#### A future API we are considering
```js
var CustomClass = Class.extend({
    defaults: function() {
        return {
            foo: ko.observable('The Default Value'),
            bar: {}
        };
    }
});
```

**Comment by astorm** [comment]
Thanks @zetlen, that totally makes sense -- not ideal, but clear statements w/r/t usage and intention (both in docs and core usage) seem like a reasonable solution here.  Assuming you're tracking this one internally somewhere, so closing out since you're aware of the behavior.

**Comment by zetlen** [comment]
Thank you, @astorm. We are indeed moving this to internal review for docs and dev.
