### ISSUE TITLE
Magento don't have a function for hide validation errors

### ISSUE THREAD

**Issue by springimport** [magento/magento2#7766]
### Preconditions
I have a task to set labels state to default after click on "Complete" button.
For adding errors magento have an [errorPlacement](https://github.com/magento/magento2/blob/develop/lib/web/mage/validation.js#L1506). I need have a similar function.

### Steps to reproduce
1. I go to my computer.
2. I open my IDE.
3. I try to solve a problem.

### Expected result
I can add my code for clearError event.

### Actual result
[clearError](https://mage2.pro/t/topic/1080) not working.

| Q | A |
| --- | --- |
| Magento version | 2.1.2 with sample data |
| PHP version | 7 x64 |
| Operating system | Windows 10 x64 |

**Comment by vzabaznov** [comment]
Please format your issue description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by springimport** [comment]
@vzabaznov I have updated the question.

**Comment by veloraven** [comment]
@springimport thank you for an update, but 'Steps' section is still missed.
Please describe steps so that anyone can reproduce the issue executing them.
From the current description it more looks like an improvement. And we have separate [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) for improvements (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

**Comment by springimport** [comment]
@veloraven receive.
