### ISSUE TITLE
Option to remove default CMS page from sitemap, because already index through /

### ISSUE THREAD

**Issue by seansan** [magento/magento2#777]
Add configuration setting to "no include default CMS page to sitemap"

Set default CMS page in backend settings as homepage (in this case /homepage)

This site domain is myshop.com

Sitemap should contain myshop.com and not also myshop.com/hompage

if the configuration setting (do not include default CMS page to sitemap is enabled)

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-32178

**Comment by verklov** [comment]
@seansan, we put the ticket for your suggestion to the internal backlog. We are closing this GitHub ticket now. Thanks again for your suggestion!

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Option-to-remove-default-CMS-page-from-sitemap-because-already/idi-p/46970).

**Comment by rav-redchamps** [comment]
@seansan 

These free Magento 2 plugins should solve the problem for you

SEO and Sitemap Patch: https://redchamps.com/seo-and-sitemap-patch-magento-2-extension.html

XML Sitemap URL Exclude: https://redchamps.com/xml-sitemap-exclude-url-magento-2-extension.html
