### ISSUE TITLE
General system exception happened

### ISSUE THREAD

**Issue by sk-indiafin** [magento/magento2#7808]
Hello,

When i am going to import on local server It is imported successfully but on live server it is showing **"General system exception happened"** with same .csv file again and again in **Magento ver. 2.1.2**.
Please help us to solve this.
I have attached the .csv file also.

### Expected result

1. Import successfully done

### Actual result

1. General system exception happened

[Test.zip](https://github.com/magento/magento2/files/654023/Test.zip)

**Comment by veloraven** [comment]
@sk-indiafin thank you for your report.
Please format description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) (add steps section). It is just much easier to understand what the problem is and how to reproduce it when the description is structured.
Do you have the same environment (OS, web-server, PHP version, MySQL version) on production server and local server? Are settings (including database settings, permission setting) the same?
Did you check other GitHub issues which describe the same exception?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
