### ISSUE TITLE
REST PUT on Category fails to update with 200 response

### ISSUE THREAD

**Issue by george-vlahakis** [magento/magento2#7831]
### Preconditions
1. Magento 2.1.3 

### Steps to reproduce
1. REST POST a new category  (receive 200 ok with category id 43)
2. REST PUT to rename the category (receive 200 ok with new category name in response)
3. REST GET to get the new name (receive 200 ok with new category name)
4. Check category name in administration console

### Expected result
1. The category name to change 

### Actual result
1. Category name does not change in console
2. In the db the new name is added as an additional attribute set.

Payload in REST PUT:

```
{
  "category": {
    "name": "Test Category Rename"
  }
}
```

**Comment by george-vlahakis** [comment]
Looking in the db after a REST PUT the new name is added under store with ID 1 in table 'catalog_category_entity_varchar'. 

Any way of forcing the change to happen to store with ID 0 - which is the default store (sample data)

**Comment by george-vlahakis** [comment]
Turns out the REST PUT changes the name in the Default Store View (with ID 1) and not at All Store Views level (ID 0).

**Comment by george-vlahakis** [comment]
**Update:** If you add store_id to the URL it works for GET. I could not find **anywhere** in the documentation saying something about store_id. Saw it on another ticket. 

Now if I call  REST PUT with a store_id it seems to always create a new category no matter what.

**Comment by george-vlahakis** [comment]
Ok I think I have finally found the solution:

In essence **all** calls to REST API should define the store code as described [here](http://devdocs.magento.com/guides/v2.0/rest/rest_endpoints.html).

So **< domain >**/index.php/rest/**< store_code >**/V1/categories is the full URL to define the store. 

If you always set **all** as the store code then it will always update the top store view.

The same applies for products.

If only the docs where a bit more clear on this (especially the samples)

Also, to update an entity use POST (not PUT) with the item id (sku for product) in the JSON sent.
If you use PUT the full path does not work and you need to use the store_id parameter instead as in my previous post.

Pff

**Comment by george-vlahakis** [comment]
Wrote a guide with whatever I've found thus far here: http://undefined.gr/site/2016/12/22/magento-2-1-3-rest-api/

**Comment by magnetic5355** [comment]
@vlahakis  - going to test this out!... this functionality has been driving me crazy. Every time we update a category with /rest/v1/categories and PUT it would split the attributes into store view 1.

**Comment by magnetic5355** [comment]
@vlahakis - putting ?store_id=0 on put solved it! thanks so much

**Comment by misha-kotov** [comment]
Agree that this should be better documented, and we can certainly work on that (cc: @keharper, @tanberry )

By the way, <store_code> should actually be the <storeview_code> that each Store View has in the Admin panel (it's confusing bc it's identified as "store/id" in the url). 

What I found in my investigation: 
"all" keyword is used to designate that the operation should be performed in the "All Store Views" scope. Since category names can be overridden per store view, the category names you see under "All store views"scope are just the defaults. If you send a REST PUT request to rename a category with "all" scope, it will rename the default category name (one you see under "All Store Views" scope) and category names under all other store views where the category name has not been overridden yet (if the name's different from default, it will not be touched). 

Whenever the <storeview_code> is not specified in the URL (or "default" is specified), the system assumes the single default store view scope (store_id=1). This is why when you rename a category like you did in the original post (no storeview_code), you can only see it after selecting the default store view in the Admin panel UI (as opposed to looking at the default "All Store Views" scope). 

The system will not let you create a category with scope="All Store Views" (presumably because each category can only belong to one root category). You'll need to pick a specific one or the default one will be used. 

I'm not entirely sure why specifying "?store_id=0" works, but it may not be intended. I would recommend sticking to specifying "storeview_code" in the REST URL (or using "all" instead). 

I'd like to chalk up this issue to a documentation improvement and not a bug report. Let me know if this makes sense.

**Comment by george-vlahakis** [comment]
@misha-kotov I agree in terms of flagging it as a DOC improvement however I wonder to what extent it may be also a BUG. That is to be determined by the original product specification and architecture, meaning if it was mean to work another way from start. Taking from SWAGGER docs I suspect it is also a BUG my friend.

**Comment by misha-kotov** [comment]
> Taking from SWAGGER docs I suspect it is also a BUG my friend.

@vlahakis do you mean that swagger docs don't mention the <storeview_code> parameter? Or is there another discrepancy between swagger docs and actual functionality that you're referring to?

**Comment by george-vlahakis** [comment]
@misha-kotov Swagger docs definitely do not mention a parameter of this type. I can't comment extensively on other aspects.

**Comment by magento-engcom-team** [comment]
@georgios-2317, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
