### ISSUE TITLE
M2.1.2 : Deletion of url rewrites uses `url_rewrite_id` instead of `entity_id`

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#7847]
The `url_rewrite` table of Magento 2 uses `url_rewrite_id` as primary key and `entity_id` as a reference to the entity (product or category, etc.).

However, if you execute the following:

    $urlRewrite = $this->urlRewriteFactory->create(['data' => ['entity_id' => $productId]]);
    $this->urlRewriteResource->delete($urlRewrite);

You would expect that the row with the specific `$productId` gets deleted, but this is not the case. Further inspection points me to `Magento\Framework\Model\ResourceModel\Db\AbstractDb::delete()`, and if I look at what the rule `$this->getConnection()->quoteInto($this->getIdFieldName() . '=?', $object->getId())` produces it shows what's going wrong:

    url_rewrite_id=''

Clearly, this needs to be

    entity_id=''

So I guess the problem here is that if a `delete()` is executed with a property `entity_id`, that it internally is mapped to the primary key of the resource model (which is `url_rewrite_id` in this case).

## Preconditions
Magento 2.1.2
## Steps to reproduce

Try to delete a url key by entity ID:

    $urlRewrite = $this->urlRewriteFactory->create(['data' => ['entity_id' => $productId]]);
    $this->urlRewriteResource->delete($urlRewrite);

## Expected result

The row with `entity_id` = `$productId` gets deleted.

## Actual result

The row with `url_rewrite_id` = `$productId` gets deleted.

I only tested Magento 2.1.2 so far. Cannot say if this issue applies for other versions as well. It could even be that the main problem is beyond the scope of the URL Rewrite module and affects every module where `entity_id` is not the primary key column and it exists as a regular column.

**Comment by magento-engcom-team** [comment]
Hi, @kanduvisla, thank you for your report. We tried to reproduce this issue in 2.1.9.

As we understood:
1. Simple product created (id = 1).
2. Execute $ urlRewrite = $ this-> urlRewriteFactory-> create (['data' => ['entity_id' => 1]]); (You have an object with only data entity_id).
3. $ this-> urlRewriteResource-> delete ($ urlRewrite); (You tried to delete it with resource).
It will enter to: Magento \ Framework \ Model \ ResourceModel \ Db \ ObjectRelationProcessor :: delete () - here you have $ table = url_rewrite, $ condition = "url_rewrite_id = ',' because our $ url rewrite model does not have id and sql will not delete any row.
4. Nothing is deleted.

Please correct our steps or confirm that the bug is not anymore reproducible in 2.1.9 version.

**Comment by orlangur** [comment]
System works as expected with the steps provided.

To remove URL Rewrites by Product something like
https://github.com/magento/magento2/blob/develop/app/code/Magento/CatalogUrlRewrite/Observer/ClearProductUrlsObserver.php#L54 should be used.

**Comment by magento-engcom-team** [comment]
@kanduvisla, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
