### ISSUE TITLE
Product import updates wrong product

### ISSUE THREAD

**Issue by ziiljuks** [magento/magento2#7904]
### Preconditions

1. Magento 2.1.1

### Steps to reproduce

1. Two existing products with sku 13020663105 (db entity_id = 2) and 13020663105SL (db entity_id = 1)
2. Use magento product import/update
3. Try to update name for 13020663105

### Expected result

1. Name changed for 13020663105

### Actual result

1. Name changed for 13020663105SL

This is because of Magento\CatalogImportExport\Model\Import\Product function _saveProductAttributes(array $attributesData).

It creates select: 
`SELECT `catalog_product_entity`.*, `catalog_product_entity`.`entity_id` FROM `catalog_product_entity` WHERE (sku = 13020663105)`

This will return two rows and fetchOne will select first one.

Should be: 
`SELECT `catalog_product_entity`.*, `catalog_product_entity`.`entity_id` FROM `catalog_product_entity` WHERE (sku = '13020663105')`

**Comment by jurgisl** [comment]
Without the quotes SKU field on the left is being converted to numeric so it drops trailing characters. Then the numeric comparison sees the 13020663105 and 13020663105SL as the same numbers.

This happens because earlier SKUs are being used as array keys, and array keys are converted to int by PHP if it is possible http://php.net/manual/en/language.types.array.php:

> Strings containing valid integers will be cast to the integer type. E.g. the key "8" will actually be stored under 8. On the other hand "08" will not be cast, as it isn't a valid decimal integer.

So if the import function is using these keys, they must be manually cast to string (because all SKUs should be treated as string?).

**Comment by AlexWorking** [comment]
Hello, @ziiljuks. The internal ticked MAGETWO-70444 has been created based on Your issue. As the issue is resolved You'll be immediately informed. Thanks for applying.

**Comment by magento-engcom-team** [comment]
@ziiljuks, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
