### ISSUE TITLE
customer objects are equal to eachother after observing event customer_save_after_data_object 

### ISSUE THREAD

**Issue by anthonycouckhuyt** [magento/magento2#7915]
### Preconditions
1. Magento CE 2.1.2 without sample data is installed.
2. Running on Linux Webserver with PHP 7, MySQL  5.0.12

### Steps to reproduce
1. Log in with existing user in frontend.
2. Change first name of customer to 'test35'.
3. Observe the event 'customer_save_after_data_object'. Two objects are given called : 'orig_customer_data_object' & 'customer_data_object'.
4. Those two objects are identical to each other. First name in both objects is equal to 'test35'

### Expected result
1. 'customer_data_object' firstname should not be equal to 'orig_customer_data_object'

### Actual result
1. orig_customer_data_object and customer_data_object are equal to each other
Screenshot here: http://imgur.com/a/IDV1t

This also happens with last name and email. There may be more, but I haven't checked.

**Comment by medinadato** [comment]
The problem here is a bug in the file vendor/magento/module-customer/Model/ResourceModel/CustomerRepository.php  line 227. See below:

`['customer_data_object' => $savedCustomer, 'orig_customer_data_object' => $customer]`

It should be:

`['customer_data_object' => $savedCustomer, 'orig_customer_data_object' => $prevCustomerData]`

Until Magento Team fixes it, you should overwrite the method to fix the issue. I've written a how to here https://blog.mdnsolutions.com/magento-2-customer_save_after_data_object-equal-objects/

Cheers,

**Comment by magento-engcom-team** [comment]
@Koekoet, thank you for your report.
We've created internal ticket(s) MAGETWO-81900 to track progress on the issue.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-82529

**Comment by okorshenko** [comment]
The issue has been fixed in 2.2-develop branch

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-82652
