### ISSUE TITLE
Can't change customer group when placing an admin order, even after MAGETWO-57077 applied

### ISSUE THREAD

**Issue by mtstedman** [magento/magento2#7974]
1. Magento 2.1.3,  
2. PHP 5.6.27
3. mySQL 5.6.33
4. Ubuntu 14.04.5 LTS

### Steps to reproduce
1. From the admin section go to Sales > Orders > Create New Order > Select Customer
2. The customer group field is set to the default customer group (not the one the customer is actually in) and when I attempt to change the group to something else, the waiting icon spins and then it resets it back to the default customer group.
3.  Same thing occurs if I try and create a new customer via Create New Customer > Add Customer

### Expected result
1. Customer's actual group should be the default selected in the Customer Group field, not the default setting
2. Should be able to change the customer group, or at least process the order as something other than the default customer group.

### Actual result
1. Customer group is set to the default group, and impossible to change off it via admin orders.

**Comment by marksharkey** [comment]
when will this be implemented?  https://github.com/magento/magento2/issues/6162

**Comment by magento-engcom-team** [comment]
Hi @mtstedman. Thank you for your report. 
The issue has been fixed in magento/magento2#21145 by @gauravagarwal1001 in 2.3-develop branch
Related commit(s):
 - [76468502c720ae637c3c61382dfd57a40c071ad1](https://github.com/magento/magento2/commit/76468502c720ae637c3c61382dfd57a40c071ad1)

The fix will be available with the upcoming 2.3.2 release.

**Comment by magento-engcom-team** [comment]
Hi @mtstedman. Thank you for your report. 
The issue has been fixed in magento/magento2#21239 by @amol2jcommerce in 2.2-develop branch
Related commit(s):
 - [d77bc6acaccaecddc4bda3415d268ed21ef94981](https://github.com/magento/magento2/commit/d77bc6acaccaecddc4bda3415d268ed21ef94981)

The fix will be available with the upcoming 2.2.9 release.
