### ISSUE TITLE
[Advanced Pricing] Magento 2.1.2: Can't remove special price for product

### ISSUE THREAD

**Issue by ostrovanka** [magento/magento2#8034]
Preconditions
1.Magento 2.1.2 EE with Sample data

Steps to reproduce
1. Open any product in admin panel and set special price for it
2. Check price on storefront -> it is applied correctly
3. Remove special price for the product and save
4.Open Advanced Pricing tab fro the product

Expected result
1. Special price for the product is removed

Actual result
1.Special price for the product is not removed: http://screencast.com/t/2tODEarhXDs

**Comment by veloraven** [comment]
@ostrovanka thank you for your report.
As Enterprise edition issues should be reported via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant (this will allow for proper tracking of issues at the account level), please let us know if you have already report it via some portal in order to avoid duplicates in our internal system. Github is intended for Community edition reports given no account management for CE users.

**Comment by MartinWickman** [comment]
This is not an EE issue. It happens in the community version as well. It's not possible to remove special price.

**Comment by ErvinLlojku** [comment]
Any update regarding the issue?

**Comment by OvalMedia** [comment]
Version 2.2.8 and this issue still exists. As a workaround I could set the special price to 0 and it would be removed. But this does not work when running more than one website. I wanted to remove the special price for one website but not for the other. The special price was actually displayed as 0 in the frontend. 
I had to set the special price equal or greater than the normal price to make it go away in the frontend.

**Comment by psuthar12** [comment]
Issue exist in Version 2.3.0, with multi website when we try to remove special price for any single website then after product save it is set to use default Value, It should remove special price for that website. Is there any solution/patch for this?

**Comment by soloma88** [comment]
It's 2022 now. Issue still exist when you try to save special price for store.
