### ISSUE TITLE
Swiftmailer Security issue CVE-2016-10074

### ISSUE THREAD

**Issue by javsalgar** [magento/magento2#8049]
On 25.12.2016 a security issue (CVE-2016-10074) was found in the Swiftmailer component for versions lower than 5.4.5. You use the monolog component which uses Swiftmailer. Could you confirm if that affects the security of the application?

More info: http://pwnscriptum.com/

**Comment by safwkhan** [comment]
This vulnerability (CVE-2016-10074) doesn’t affect Magento application. When you run composer install/update from Magento root, by default it will install all “require-dev” packages in the root composer file where you run the command. It doesn’t recursively download “require-dev” dependencies of a package (a package that is listed in the root composer file). In this case,  “swiftmailer/swiftmailer”, which is in “require-dev” for "monolog/monolog" package, will not be installed/downloaded either in development or production environment of Magento. This swiftmailer is only for development purpose (e.g. test) of monolog -- in case you want to develop or contribute to monolog, you can download swiftmailer; otherwise not. In essence, swiftmailer has nothing to do with Magento application.
