### ISSUE TITLE
Page messages (notifications) are not displayed correctly

### ISSUE THREAD

**Issue by venkivenkatesh** [magento/magento2#8087]
The page messages are displayed wrongly on random pages:

I am using Magento 2.1.0 .Are these reported GitHub issue 4336,4186 and 3503 moved in Magento 2.1.0.Because still i face those issues like 
i) I added a product to cart and the sucess message is displayed in every other page that i visit subsequently.
ii) Also some times the error messages are not displayed.Suppose i tried to login with wrong credentials on login page.Notification message "Invalid login or password", should appear, but it didn't happen.

**Comment by korostii** [comment]
Well, it was supposed to be fixed in 2.1.3. From [release notes](http://devdocs.magento.com/guides/v2.1/release-notes/ReleaseNotes2.1.3CE.html):
> Magento now displays the product add validation message (“Product was added to the cart”) only after you have successfully added a product to your cart.

So it probably got better although I've seen reports saying otherwise (in particular #8007), so maybe it's not completely fixed. 
I can only suggest that you try to upgrade to 2.1.3 preferably on a testing environment in order to see whether that'll fix your problem while not breaking anything else (which is unfortunately possible, if you, for example, have a multi-website setup)

**Comment by venkivenkatesh** [comment]
Thanks for your reply. We can't upgrade it to 2.1.3 right now as our site is ready to be moved to production.We have left only with this issue.

Can you please share the fix which has been updated to 2.1.3 so that we can check that it in our instance.

**Comment by korostii** [comment]
Just to clarify, a disclaimer: I am not an employee of Magento, Inc. nor do I have close relationship to the Magento Core development team. Thus I might not have all the related information available.

However, luckily, the fixes in question were referenced in the two original bug reports: #5301, #5530 
In particular, here's the fix from 2.1 branch: 39b35ec55bad37f7166dc6bd57b56b9af3ec4f96
And again, I very much hope it works for you, but it just might be the case that it doesn't. So I hope you will test it carefully.

**Comment by veloraven** [comment]
@venkivenkatesh thank you for your feedback.
The GitHub issue tracker is intended for technical issues only which are expected to be fixed in following releases. 
Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions, when you need advice or discussion.
