### ISSUE TITLE
M2.1.3 : 'One of the countries has invalid code' when importing Tax Rates

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#8102]
Not a bug, but more of a feature request.

I'm trying to import 250 tax rates, but it only imports 200 of them and then shows the message: _'One of the countries has invalid code'_. It would be better feedback if Magento tells us which country / countries these are.

**Comment by veloraven** [comment]
@kanduvisla thank you for your submission.
As it is an improvement rather than issue please submit it to the [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).
As GitHub is intended for technical issues only.

**Comment by kanduvisla** [comment]
@veloraven I added it to the forum: https://community.magento.com/t5/Magento-2-Feature-Requests-and/Improve-the-message-when-importing-tax-rates-for-non-existing/idi-p/57341
