### ISSUE TITLE
"Save Block"-button on Add New Block silently ignores clicks if the content is empty.

### ISSUE THREAD

**Issue by geon** [magento/magento2#8114]
When clicking "Save Block", nothing happens if the content editor is empty.

### Preconditions

Magento: 2.1.2, 2.1.3
PHP: 7
Mysql: Percona
(Mageinferno docker-compose)

### Steps to reproduce
1. Go to Content > Blocks > Add New Block
2. Fill in Block Title and Identifier
3. Click "Save Block"

### Expected result
Block saved with empty content, or error message displayed.

### Actual result
Nothing. Click is ignored.

**Comment by magento-engcom-team** [comment]
@geon, thank you for your report.
We've created internal ticket(s) MAGETWO-80459 to track progress on the issue.

**Comment by RomaKis** [comment]
Working on this.

**Comment by ishakhsuvarov** [comment]
Hi @geon. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1032 by @RomaKis in 2.2-develop branch
Related commit(s):
 - 5bac54fc879f5551b8187c0250b5874efdb74391
 - 4456872bb47fee7271ce887a306e1bf7477e9d2e
 - 42ee7cc8bc5e2bb8121e9e13b1c90b3255ba6897

The fix will be available with the upcoming patch release.
