### ISSUE TITLE
FPC invalidated after login/logout

### ISSUE THREAD

**Issue by cizgidekiadam** [magento/magento2#8127]
### Preconditions

1. Magento 2.1.3
2. Redis OR/AND Varnish
3. PHP 7.0.14
4. Single store mode

### Steps to reproduce

1. Enable cache (Redis or Varnish with default configuration, not changed conf)
2. Browse a page first (Not cached)
3. Refresh (FPC HIT)
4. Login (FPC invalidated for all )
5. Logout (FPC invalidated again)

### Expected result

1. It shouldn't clear all cached. If it required, may be cleaned by account related tags, not catalog wide.

### Actual result

1. FPC Invalidated

**Comment by cizgidekiadam** [comment]
An addition;
The invalidation happening 'silently'. There is not any warning in admin/cache management or debug.log. 

Only way to check this, look at X-Magento-Cache-Debug header before and after login/logout

fyi.

**Comment by naydav** [comment]
It is expected behaviour.
Page Cache is generated for an user context (user groups).

Example on your steps:
1. Browse a page first (Not cached)
3. Refresh (FPC HIT)
--
Cache is generated for "not logged user" context (cache is same for all not logged users)

4. Login (FPC invalidated for all)
--
Page Cache is not invalidated for all.
Now you in another context (logged user, default customer group).
So, if you are the first user in the scope of some specific context - you will get a MISS (because content should be generated for current context during your request)
but for 2nd and further visitors - there would be cache HIT

After 4) step make logout(change context) and go to the first page you will see cache HIT on this page.

For more information see using of \Magento\Framework\App\Http\Context::getVaryString
Also you can create plugin on this method for adding new metrix to cache context.

Thanks

**Comment by cizgidekiadam** [comment]
Agree that, but;
Our websites are serve same data for logged in or regular users.
There is not any price, design or config etc... changes for different customer/user groups.

I think this behaviour could be switched on/off for custom usage scenarios. Or could be enabled for selected areas (ex. order list, account page etc.)

Why we should invalidate regular content (product list, category etc..) without changes just user loggedin/out states ? 

It  confused me a bit.

**Comment by naydav** [comment]
For now Magento doesn’t check whether you have pre set  custom rules for specific context.
And actually it’s very complicated, because some of the extension installed could pluginize/change/extend 
"look and feel" of the product for specific customer group or affect (modify)  prices

Taking into account that it does not introduce a lot of extra memory and introduces just single extra request for new context we consider this as acceptable out of the box solution. 

But of course it could be customized for your specific installation.

**Comment by cizgidekiadam** [comment]
Thanks for quick response. I'll do some planning for custom solution.
