### ISSUE TITLE
Magento 2.1.3 - There is a bug in advanced search form regarding validation messages

### ISSUE THREAD

**Issue by DarkLanternMG** [magento/magento2#8131]
### Preconditions

1. Magento 2.1.3 CE
2. PHP 7.0.9
3. MariaDB 10.1.16
4. Apache 2.4.23

### Steps to reproduce

1. Go on the site "advanced search" and click the submit button below the form without any entries.
2. Then click for example on the "sign in" link in the top right corner.

### Expected result

1. Validation message (Please specify at least one search term) appears on the same site (advanced search) above the form after you click the submit button.

### Actual result

1. No message appears, rather on random site after you submit the advanced search form without entries.
![bug8131](https://cloud.githubusercontent.com/assets/25103000/21933019/d8e90b72-d9a3-11e6-8f71-066cd2acf7c9.JPG)

2. I remember that behavior was already in Magento Version 2.1.2 CE.

**Comment by DarkLanternMG** [comment]
Any suggestions how to fix this problem?

**Comment by Radosav** [comment]
We are having a similar issue. 

Preconditions:
1. PHP 5.6
2. Magento 2.1.0
3. Apache 2.4.12

Steps to reproduce

1. Go on the site "advanced search" and click the submit button below the form without any entries.
2. Message appears on result page, or any page we click on right after clicking "submit" on search page.

**Comment by DarkLanternMG** [comment]
Hey, I just noticed that behavior happens if the page cache is enabled.

I hope @veloraven can assign someone new or maybe @choukalos again to solve this bug.

**Comment by veloraven** [comment]
Internal ticket - MAGETWO-69899

**Comment by magento-engcom-team** [comment]
@DarkLanternMG, thank you for your report.
We've created internal ticket(s) MAGETWO-80621 to track progress on the issue.

**Comment by sidolov** [comment]
Hi @DarkLanternMG. Thank you for your report. 
The issue has been fixed in magento/magento2#16952 by @brobie in 2.2-develop branch
Related commit(s):
 - [a8ba2f3f0211b9f2f77a7bd0cfa1f62716294ec9](https://github.com/magento/magento2/commit/a8ba2f3f0211b9f2f77a7bd0cfa1f62716294ec9)
 - [61012870b79fbd9f93369d7e9f91f4adadf630bd](https://github.com/magento/magento2/commit/61012870b79fbd9f93369d7e9f91f4adadf630bd)
 - [f5c32015a40e39b0eb58e71b8f516bfd152dc665](https://github.com/magento/magento2/commit/f5c32015a40e39b0eb58e71b8f516bfd152dc665)

The fix will be available with the upcoming 2.2.6 release.

**Comment by sidolov** [comment]
Hi @DarkLanternMG. Thank you for your report. 
The issue has been fixed in magento/magento2#17210 by @torhoehn in 2.3-develop branch
Related commit(s):
 - [369b7bc5ad23f4f6eeda14cc24cd94f812aecf49](https://github.com/magento/magento2/commit/369b7bc5ad23f4f6eeda14cc24cd94f812aecf49)
 - [20a712431f597e90a2e4c8fd38dde9e1d68218b1](https://github.com/magento/magento2/commit/20a712431f597e90a2e4c8fd38dde9e1d68218b1)
 - [a39c8e4d054c81f9eccd0ad864d1ea07c64169b6](https://github.com/magento/magento2/commit/a39c8e4d054c81f9eccd0ad864d1ea07c64169b6)

The fix will be available with the upcoming 2.3.0 release.

**Comment by DarkLanternMG** [comment]
Thank you all.
