### ISSUE TITLE
Fatal error in Fedex Tracking

### ISSUE THREAD

**Issue by casconed** [magento/magento2#8219]
### Preconditions

1. Magento HEAD
2. PHP 7
3. Fedex configured in Sandbox mode with appropriate credentials

### Steps to reproduce

1. Create Fedex Shipment from the Admin
2. Use tracking `122816215025810` 
2. Click tracking link to open popup window

### Expected result

1. Tracking information should be displayed

### Actual result

1.`
Fatal error: Uncaught Error: Call to a member function format() on boolean in /Users/jmoore/Develop/magento2/app/code/Magento/Fedex/Model/Carrier.php:1576`

File `module-fedex/Model/Carrier.php` makes incorrect assumptions on line 1576 about the format of dates returned from Fedex. The call `\DateTime::createFromFormat(\DateTime::ISO8601, $event->Timestamp);` returns 0 for non-ISO8601 formats (8601: 2017-01-03T22:27:00-05:00), but Fedex can (and does) return dates formated like: '2017-01-03T00:00:00' (with no offset for TZ)

When the return is 0, the subsequent calls to 'format' fail.

However, even when that assumption is corrected, I still get errors:
`Invalid method Magento\Framework\View\Element\Template::formatDeliveryDateTime`
`Invalid method Magento\Framework\View\Element\Template::formatDeliveryDate`
This is because in details.phtml 'block' is no longer \Magento\Shipping\Block\Tracking\Popup. It looks like details.phtml got refactored out of popup.phtml, but the methods weren't updated accordingly.

**Comment by YevSent** [comment]
Hi, @casconed, thanks for reporting, this is known issue (internal ticket MAGETWO-63215).

**Comment by YevSent** [comment]
Related PR https://github.com/magento/magento2/pull/7229.

**Comment by alena-marchenko** [comment]
Hi @casconed 

Fix for MAGETWO-63215 is merged to develop branch, closing the issue.
Thank you.

**Comment by Ctucker9233** [comment]
@magento-engcom-team this doesn't appear to be fixed in 2.2 branch, if you link commits, i'll create backport.

**Comment by Ctucker9233** [comment]
@magento-engcom-team @joni-jones This fix doesn't seem to be included in 2.2. Any news?

**Comment by sdzhepa** [comment]
Hello @casconed and @Ctucker9233 

As I can see this issue was fixed in the scope of internal tickets `MAGETWO-63215` and `MAGETWO-69898`

And should be available now for 2.2.0 and 2.1.1

For 2.2.0 see commits for more details:
- 0c2836a8d909102eca9a4ed22009e61e53ddf43d
- 2c5b4c5de69e611b61628990cecc4e4e97b581f0
- 0111bacbc75513c36609b4080a06707460342c4e
- 21d79d35426f60ae13083131b3ea02df83435c3f
- 87436e0591010ccbadf791995a4f00c18ea51651
- 62f7d7566db85097c61ed4e884fa85bdb9211884
- b9c7cad0f68fff3cf4de721e1f0d59138376cdce

For 2.1.1 see commits for more details:
- 9c1c45b741195cb5bd0099c7f25c92d73b19ae07
- 09bbedb7618b4e264a5edbf619f21123df43f7c7
- 1346cba7d0bb4cfa72ad046d332f87fd65715f71
- 005b273dd6021448ca13589807065901ba84944f

Please, feel free to reopen or create a new one if issue still exists or was not fully fixed

Thank you for feedback and collaboration

**Comment by marvinhinz** [comment]
Still happens on Magento 2.4.1 :/
