### ISSUE TITLE
Add product page loading forever.

### ISSUE THREAD

**Issue by hyesungs** [magento/magento2#8225]
When I click the add product button the page just loads forever with the spinner icon.

I am using Magento2 - 2.1.3

Reproduce
1.  Goto products
2.  Goto catalog
3.  Click 'add product'

Expected result
1. Be able to add product.

Actual result
1. Product page spinner loading forever.

![capture](https://cloud.githubusercontent.com/assets/25263158/22173485/57a6b01c-e008-11e6-8a16-3ccbb476cc08.PNG)

**Comment by allanpaiste** [comment]
Have you tried to repeat this with Vanilla Magento2 (no other extensions installed)? I am not able to repeat this issue and am wondering if some 3rd party module causes this to happen (with js mixins). Could you provide the whole js call-stack here as well? Is it somewhat understandable what context/variables/usage causes this? Certain product type maybe? More details would be highly appreciated to understand what's going on there.

Considering that it's a ui-component js script that fails (view/adminhtml/web/js/components/import-handler.js), I would place my bets on an explanation that something goes wrong before that .js crash and the actual issue comes from something in the ui-components or layout configuration (js can't find fields that are supposed to be there). So that crash is probably a symptom of some other issue, that causes the output to be missing.

**Comment by hyesungs** [comment]
Hi there, Thanks for your reply.

Unfortunately I am just not that knowledgeable enough to be able to
understand a lot of this. I have basic html skills, bootstrap ect... and
only a basic understanding of php ect... java is far beyond my scope.

I basically can just give you a run down of whats happening.

I have 1 module (Webkul Marketplace for Magento2) and 1 theme (Ultimo)...
However please note that when both of these are fully disabled the problem
is still there. Although even stranger is that just as I originally
installed Magento2 as a fresh with no extensions or themes the add product
button did work (Although I must say it was slow and hesitant), then all of
a sudden it just stopped working (Althoug I am not sure at what point or
the cause). (But like I say I have disabled both the theme and the
Marketplace module and the problem is still there). I have spoken to Webkul
who are 100% sure that it is not there module.

Other than the above 2 installs of the theme and marketplace its a fresh
install with no data e.g customers, products ect... As far as I am aware
the crons are running correctly too.

I have tried the usual deploy:static, cache:flush, setup:di:compile ect...
Nothing what so ever is working. :-(

I do not mind paying some one to fix the issue but everyone who I am asking
dosn't seem to have an answer either.

So I am left in a very awkward position as to what to do or what or whom to
blame for the problem and am no closer to been able to find a fix.

I have used Mageto1 a million times and Magento2 a fare few times on
different small shops of ours and never had this kind of issue t the point
where I cant actually use it (or even find anyone to fix it)...

Not sure where to go from here.

**Comment by veloraven** [comment]
@hyesungs thank you for your report.
Could you please provide some more information about your environment?
1. Please provide versions of PHP, MySQL and WebServer which are used.
2. Do I understand correctly that this is clear install of Magento 2.1.3, not an upgrade from some previous version?
3. Please provide information about Magento mode.
4. Did you try to clean browser cache including offline website data?

**Comment by webkul** [comment]
Hi hyesungs  , If you are still have any issues please create a support request at https://webkul.uvdesk.com . Thanks

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
