### ISSUE TITLE
Custom attribute in address form on checkaut page.

### ISSUE THREAD

**Issue by AlexSeyFomin** [magento/magento2#8231]
I added a few custom attributes for a customer addresses. New fields are displayed on the checkout page, but they are not processed by JS.

### Preconditions
1. Magento ver. 2.1.1

### Steps to reproduce
1. Add new attributes to customer addresses.
2. Go to checkout page. 

### Expected result
1. New fields should be present in "shipping information" request.

### Actual result
1. New fields do not take part in the checkout processing (if not logged in)

New field: ![selection_009](https://cloud.githubusercontent.com/assets/16902841/22196901/1efce0d2-e158-11e6-862a-b3f8f10e2122.png)
Request data: 
![selection_010](https://cloud.githubusercontent.com/assets/16902841/22196933/4b104434-e158-11e6-80a8-3e1790657994.png)

If logged in: 
New fields are present in an array of custom attributes
![selection_011](https://cloud.githubusercontent.com/assets/16902841/22197196/8ff1c824-e159-11e6-9090-7946d306d1e6.png)

Sample code to add customer address attribute:
```
$customerSetup->addAttribute('customer_address', 'company_telephone', [
            'type' => 'text',
            'label' => 'Company Telephone',
            'required' => false,
            'visible' => true,
            'visible_on_front' => true,
            'user_defined' => false,
            'sort_order' => 61,
            'position' => 61,
            'system' => 0,
            'input' => 'text',
            'validate_rules' => 'a:2:{s:15:"max_text_length";i:255;s:15:"min_text_length";i:1;}',
        ]);
        $attribute = $customerSetup->getEavConfig()->getAttribute('customer_address', 'company_telephone')
            ->addData([
                'attribute_set_id' => $attributeSetId,
                'attribute_group_id' => $attributeGroupId,
                'used_in_forms' => ['adminhtml_customer_address', 'customer_address_edit', 'customer_register_address','customer_address'],
            ]);
        $attribute->save();
```

**Comment by veloraven** [comment]
@AlexSeyFomin thank you for your report.
Which Magento edition do you use? As I can see you mention custom address attributes.
Customer custom address attributes are available in Enterprise edition only.
If you use this one, please contact Magento support instead of posting your issue here.
If you use Community Edition please address your question at  [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) or [Magento Stack Exchange](http://magento.stackexchange.com/). As it is not a native behavior of Magento CE amd we can not treat it as an issue
