### ISSUE TITLE
Unable to reindex from backend, bug?

### ISSUE THREAD

**Issue by MagePsycho** [magento/magento2#824]
There is no way to reindex from backend. Whatever you do it says: Reindex Required.
But using command line works fine:
`php dev/shell/indexer.php reindexall`

**Comment by WilliamAtMagento** [comment]
This behavior is as expected by design.

Indexing has become a background operation with automatic consideration for partial or full re-indexing.

Documentation will be updated with details about asynchronous admin functions.

**Comment by alankent** [comment]
Just for the record, I came across http://devdocs.magento.com/guides/v1.0/config-guide/cli/config-cli-subcommands-cron.html which describes how to run 'magento cron:run' from the command line to rebuild indexes (because there is no button in the Admin UI).  The trick I did not realize immediately was you have to run it more than once to schedule the work then do the work (something like that).  For me developing on Windows, crontab was not an option.

**Comment by jayelkaake** [comment]
I understand this is by design but I'm going to +1 on having the ability to re-index from the admin - maybe make it a hidden option for admins only or something.

**Comment by krlecarp** [comment]
+1 here too. Maybe not best practice, but I do it enough manually that it's
an annoyance. But if I need to have a less-technical colleague with admin
access to run it, then they need to wait. Admin option would be nice.

**Comment by Vincentguo1990** [comment]
+1 here to on having the ability to re-index from the admin.

**Comment by ghost** [comment]
You can use magento indexer:reindex at any time. http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-index.html#config-cli-subcommands-index-reindex

**Comment by jayelkaake** [comment]
@xcomSteveJohnson Of course :smile: - we're just +1-ing for an admin UI for it so that we don't have to SSH into our clients' sites when we want to rebuild the indexes.

**Comment by KrishnaPB** [comment]
Hi, I am unable to reindex through SSH. I can see below result.
root@ubuntuserver:/var/www/html/test# magento indexer:show-mode
magento: command not found

Please help me how do I reindex.

**Comment by ihor-sviziev** [comment]
Try to type following command:
./bin/magento indexer:show-mode

**Comment by KrishnaPB** [comment]
Thank you. but I got below error now:

root@ubuntuserver:/var/www/html/test/bin# ./magento indexer:show-mode
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20131226/php_xsl.dll' - /usr/lib/php5/20131226/php_xsl.dll: cannot open shared object file: No such file or directory in Unknown on line 0

I have installed the module xsl still I am getting above error. Please help me on this.

**Comment by ihor-sviziev** [comment]
KrishnaPB,
looks like you have some issues with php env, it's not related to Magento.
You used library for windows on Linux machine, as result it doesn't work.
Try revert your changes and install them with following command:

sudo apt-get install php5-xls

**Comment by KrishnaPB** [comment]
Thank you very much. i will check it out

**Comment by zoneradx** [comment]
I want to know how cron works? How can I run it to reindex data?

**Comment by titechnologies** [comment]
+1 having the ability to re-index from the admin

**Comment by JuliaGosling** [comment]
+1 having the ability to re-index from the admin

**Comment by Ctucker9233** [comment]
+1 having the ability to re-index from admin. Unless someone can explain the advantage to have to run cron jobs or CLI every single time.

**Comment by femorais** [comment]
+1 to re-index from Admin

**Comment by serzhik** [comment]
I force reindex from admin panel with such steps:
1. Go to Index Managment at admin panel.
2. Switch all actions to Update on Save.
3. Switch all actions back to Update by Schedule.

**Comment by krejcif** [comment]
@alankent Even from scheduled CLI, reindex is still partial from queue generated by saves. 
You can force full rebuild by some fundamental changes in setting (bad workaround). But you can't force full rebuild by command.

Am I right?

There is lot of cases where we need to rebuild in development process (if you have broken eg url rewrites, prices, etc.). This is our developer experience.

**Comment by digitalpianism** [comment]
For those who are interested in reindexing from the backend: https://github.com/digitalpianism/reindex

But again as William said: "Indexing has become a background operation with automatic consideration for partial or full re-indexing" so don't use this module if you have SSH access as you will run into a lot of problems with your store if you do not have Magento's cron scheduler set up and running as intended.

**Comment by magento-engcom-team** [comment]
Hi @MagePsycho. Thank you for your report. 
The issue has been fixed in magento/magento2#28366 by @Nazar65 in 2.4-develop branch
Related commit(s):
 - [8bfc104948ce65e0f98e78f34aeffacdc2f8f276](https://github.com/magento/magento2/commit/8bfc104948ce65e0f98e78f34aeffacdc2f8f276)
 - [a5a13fb40f7656dfa79cecec9c0b921d30cdd52f](https://github.com/magento/magento2/commit/a5a13fb40f7656dfa79cecec9c0b921d30cdd52f)
 - [5667714ced2b982a14b5b18b6591d34fbf287028](https://github.com/magento/magento2/commit/5667714ced2b982a14b5b18b6591d34fbf287028)
 - [a867d70f9809e95c75e3d4aa6dc0d2808620605f](https://github.com/magento/magento2/commit/a867d70f9809e95c75e3d4aa6dc0d2808620605f)
 - [1d0316d756987e4453c38bb432eee03153a7fec0](https://github.com/magento/magento2/commit/1d0316d756987e4453c38bb432eee03153a7fec0)
 - [d06fd27fbdaa2633c81e9f5babff6aa28b56ffed](https://github.com/magento/magento2/commit/d06fd27fbdaa2633c81e9f5babff6aa28b56ffed)
 - [f953f3545453fecfc5d47e2b23411a13aa39b6be](https://github.com/magento/magento2/commit/f953f3545453fecfc5d47e2b23411a13aa39b6be)
 - [a0ed711a5235f06cb6d36a308293f0257b93c256](https://github.com/magento/magento2/commit/a0ed711a5235f06cb6d36a308293f0257b93c256)
 - [a63e68113f978ce0c24b1a2221a314b0fdbcbebe](https://github.com/magento/magento2/commit/a63e68113f978ce0c24b1a2221a314b0fdbcbebe)
 - [2133abce671bb6b09a835eec80e265568f9b3960](https://github.com/magento/magento2/commit/2133abce671bb6b09a835eec80e265568f9b3960)
 - [5032914621d42df37977acea17e06d98c94b748e](https://github.com/magento/magento2/commit/5032914621d42df37977acea17e06d98c94b748e)
 - [a54886350a90a3c944af90c5cd88d4dbbc0b0881](https://github.com/magento/magento2/commit/a54886350a90a3c944af90c5cd88d4dbbc0b0881)
 - [6e8c990ba95ad754dfe6a617bff77e428f2c6bc4](https://github.com/magento/magento2/commit/6e8c990ba95ad754dfe6a617bff77e428f2c6bc4)
 - [aef54e3e1697e1fb513c2ba35d81a6fb665cb6b2](https://github.com/magento/magento2/commit/aef54e3e1697e1fb513c2ba35d81a6fb665cb6b2)

The fix will be available with the upcoming 2.4.1 release.

**Comment by ihor-sviziev** [comment]
Looks not related to this issue
