### ISSUE TITLE
csv import validation of columns

### ISSUE THREAD

**Issue by krejcif** [magento/magento2#8248]
CSV import validation is not much clever. We are getting lot of requests from customer to help him validate the CSV format, as he is getting 503 in many cases instead of message what is wrong.

### Preconditions
1. CE 2.1.3

### Steps to reproduce

1. create CSV file for import
2. duplicate some columns 

### Expected result

1. tell the user what's wrong in message

### Actual result

1. error 503, frozen loader
![screenshot_123](https://cloud.githubusercontent.com/assets/11734352/22239030/bb19dbde-e214-11e6-9389-580dc5066e9d.png)

**Comment by veloraven** [comment]
@magexo thank you for your feedback.
Given this issue is reported against Enterprise edition, please report via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level

**Comment by krejcif** [comment]
Updated. It's the same for CE.

**Comment by magento-engcom-team** [comment]
@magexo, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
