### ISSUE TITLE
Export Products action doesn't consider hide_for_product_page value

### ISSUE THREAD

**Issue by barbanet** [magento/magento2#8255]
### Preconditions

1. Magento 2.1.3
2. My instance have 1 website and 2 store views for that website.
3. Tested with 1 product.

### Steps to reproduce

1. Create a simple product and upload an image.
2. Change the scope to 1 store view.
3. Set the image as Hide for product page in that store view.
4. Got to System -> Export.
5. Select Products and then Continue.

### Expected result

1. The CSV files should have 2 lines. The default values at the first row of values.
2. The second lines should contain values on sku, store_view_code and hide_from_product_page columns

### Actual result

1. I've created my simple product with an image. Same values for both store views.

![01](https://cloud.githubusercontent.com/assets/392385/22250503/ebc146bc-e225-11e6-9c0d-740ee651b53e.png)

2. Then I've changed the scope of my product and I've changed my image properties.

![02](https://cloud.githubusercontent.com/assets/392385/22250526/046d575a-e226-11e6-8d8b-71550728665e.png)

3. Now my product is the same but in 1 store view the image is hidden. Next step was Export productos. The file hasn't information about the second store view changes for that product.

![03](https://cloud.githubusercontent.com/assets/392385/22250565/27f2311e-e226-11e6-8970-352b4b72af53.png)

4. Now I've chanegd the product name in the same store view where I have been changed the image properties. The name has changed and the image is still hidden.

![04](https://cloud.githubusercontent.com/assets/392385/22250604/4b3005f2-e226-11e6-8a01-1bea37aec53e.png)

5. Now I've exported the file again and the name change is right but the hide_for_product_page value is still empty.

![05](https://cloud.githubusercontent.com/assets/392385/22250627/63710ae4-e226-11e6-9df0-02447e400af6.png)

**Comment by xmav** [comment]
@barbanet Thanks for reporting this issue. 
We've created internal ticket MAGETWO-63706 to address this issue.

**Comment by parthpatel147** [comment]
when we can expect Magento will fix issue , cause need to update client when we will be able to import images and and how we can get updated when that internal ticket is updated

**Comment by jinalpatelcsoft** [comment]
if ($uploadedFile && $imageNotAssigned) {
						$this->_logger->info('&&&&&uploadedFile');
                            if ($column == self::COL_MEDIA_IMAGE) {
                                $rowData[$column][] = $uploadedFile;
                            }
							$this->_logger->info('keyvalidate = '.in_array($columnImage,$disabledImages) ." *** ". isset($disabledImages[$columnImage]) );
                            $mediaGallery[$rowSku][] = [
                                'attribute_id' => $this->getMediaGalleryAttributeId(),
                                'label' => isset($rowLabels[$column][$position]) ? $rowLabels[$column][$position] : '',
                                'position' => $position + 1,
								 'disabled' => in_array($columnImage , $disabledImages)?1:0,
                               // 'disabled' => isset($disabledImages[$columnImage]) ? '1' : '0',
                                'value' => $uploadedFile,
                            ];
							if(in_array($columnImage , $disabledImages))
								$this->_logger->info('disabled  if= '.$columnImage);
							else 
								$this->_logger->info('disabled  else= '.$columnImage);
                            $existingImages[$rowSku][$uploadedFile] = true;
                        }

I went throught the code and seen  that it comes in this code for new images only when uploaded images later we cant do disable , can we have help to the issue , cause site is pending to live due to images

**Comment by magento-engcom-team** [comment]
@barbanet, thank you for your report.
We've created internal ticket(s) MAGETWO-63706 to track progress on the issue.

**Comment by okorshenko** [comment]
The issue has been fixed and delivered to 2.2-develop branch. Will be available with upcoming patch release

**Comment by magento-engcom-team** [comment]
Hi @barbanet. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1351 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - 70dd5a3fa17e1ee1cdfaf7f0defd9276989ebbd0
 - 54bc3a1dca861e11e46e12f5a15578e0cb7ceb6d
 - 3debd3f87e27e23949b81cb2d7e881b5a269608c
 - 72c496566bf0d2ff1ced0401514faa5cbaccc0f8
 - e60ecdfeabe8b8839cf52fd5ba7fefcbb0b9bdc3
 - 8703b3da3dbe28f71c1daeaba08bbe44887f0733
 - bd88ed8cc4e1f98b791bd7ca8bed45c29b276ee1
 - 1c70b18a339fddf8a51a476a5a251aabef951350
 - 5fd7481d2cf8b298369837508a16a23ab4f49850
 - 7c615065b36cdafa95d752a891c09dd4ab1a4dfa
 - 2653b8ae55625637a6836d305451e292f881bd6a
 - 917a03f89f98454cb2ecde524dc8557d7fdcc135
 - eca73d0abd1ca6e110c364ef380adab86ab3cc1a
 - 26f3109842ce89096a49b9c122af0bae6b672ba2
 - c223484a75e38fdcece09d4586342528f06c6383
 - 3b90ad71d791ba9cf8e81cc204fd306f41473a18
 - ad317c25039de70c1a976e1139c57730899eb114
 - 53e721ccc06f1ade05132690715575bd7d47d6b7
 - 6114120c0a921b342871448dfb6c47bf34a65cdc
 - 63b483925c18304a32441f66b0db8a9c70995c73

The fix will be available with the upcoming 2.3.0 release.
