### ISSUE TITLE
Static block inserted via .html file not shown in fronted when magento cache is enabled

### ISSUE THREAD

**Issue by andidhouse** [magento/magento2#8273]
### Preconditions

1. Magento 2.1.3 via update from 2.1.2
2. Nginx, PHP7, Varnish, Redis
3. Debian minimal

### Steps to reproduce

1. Include a static block via this code into a .html file to show it on the frontend:

`<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block_name')->toHtml();?>`

2. Turn on magento2 internal caching (no varnish!)

### Expected result

1. Block shows in frontend

### Actual result

1. Block does not show in frontend when magento internal chaching is activated

The block however shows when the caching is deactivated OR when varnish caching is active.

Can you guys pls check this. We reproduced this on two different systems.

Thanks!

**Comment by andidhouse** [comment]
hi @veloraven - did you test it on your system and it is a bug?

**Comment by naydav** [comment]
First of all I want to notice that it is bad practice to create and call block directly in phtml template (it is complex for customization and extension).
You need to use layout declaration instead.

In your case looks like your block is not shown because you enabled cache (and cache has been generated before your block was included).
Try to clean "Blocks HTML output" and "Page Cache" cache in Dashboard: System > Cache Management.

If it does not help pls provide more information:
- Please provide precise name of PHTML template where you injected your code snippet 
- Cache Management configuration

Thanks

**Comment by andidhouse** [comment]
hi @naydav 

no - in our case this has nothing to do with a not deleted cache etc.

We tested several times. The problem is as described before. Before entering and discussing this here (which costs all of us time and effort) i think it is best if you try to implement a static block in a .phtml file and then test it (takes about 5 minutes). As described the block is not shown when normal magento cache is activated. It is shown when cache is deactivated or when varnish is used.

To you "bad practice" comment. I do not agree here - there are cases where it makes sense to place static blocks in a .phtml file - and there are cases when it is better to include a static block via layout update and xml (which by the way works under all circumstances).

**Comment by andidhouse** [comment]
if you think this is bad practice i would also advise you to not give the opportunity in the system to include static blocks in a .phtml file at all - i think this would be best if you think so right?

**Comment by naydav** [comment]
To save time and efforts to all of us, please 
1. Create block in the admin panel with Identity - “block_name” (and some content)
2. Inject 
```php
<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block_name')->toHtml();?>
```
into 
app\code\Magento\Catalog\view\frontend\templates\product\list.phtml
3. invalidate "Blocks HTML output" and "Page Cache" cache in Dashboard: System > Cache Management. cache  (but not just switch it off and on after that)
4. Open Category Page and share the results

**Comment by andidhouse** [comment]
That is exactly what i did and why i reported this bug here... I do not understand why we should do this a second time. Instead i really would like you to check this on your system... For me this is closed now. If we report bugs and the magento team does not even have 5 minutes for testing this but we are writing a ping pong here this makes absolutely no sense for me.

**Comment by maghamed** [comment]
@andidhouse 
that's the point, we verified use-case described in your ticket according to steps @naydav  listed in his previous answer. And couldn't reproduce it on Magento 2.1.3 

So, from our perspective the reason for this could be one of the next:
1. You didn't invalidate the FPC cache, but just turned it off and then turned on. Which is different to what we asked to do, because in this case cache is preserved.
2. You didn't created Block in the admin panel 
3. You specified incorrect Block identifier in the code (setBlockId('block_name')), referring to non existent block.
4. There is another reason, maybe environment dependent which makes this bug reproducible on your side, but not reproducible on our side.

That's why we asked you to replicate all the steps @naydav mentioned to eliminate first three options which look the most evident and probable for us and start to discover 4th option if needed.

So, let's stop blaming each other and turn the communication in more productive way, we spent much more than 5 minutes for issue you created and ready to spend more, but we need your feedback and assistence at least in reproducing the bug. 
Thanks in advance for your help and patience

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
