### ISSUE TITLE
Magento v2.1.2 - Choosing a child theme for product page

### ISSUE THREAD

**Issue by ChevCheusov** [magento/magento2#8333]
The Magento only pulls through the styles from the child theme, and not the layouts. The XML files are pulled from the parent theme wich is wrong.

### Preconditions
1. Install Magento 2.1.2 , PHP 5.6.29, MySQL 5.6

### Steps to reproduce

1. Trying to setup a child theme specifically for some products. However, this doesn't contribute. Magento does not pull layout from the "child theme".
2. See the theme catalog structure:
Master_theme
    -- theme
        -- Magento_Catalog
            -- layout
                -- catalog_product_view.xml
Child_theme
    -- theme
        -- Magento_Catalog
            -- layout
                -- catalog_product_view.xml

Magento pulls the "catalog_product_view.xml" from the parent theme instead of child.
That is the problem!

### Expected result
1. Magento pulls the "catalog_product_view.xml" from the child theme.

### Actual result
1. admin panel --> product edit --> select design tab --> new theme --> select "child theme"
http://dl3.joxi.net/drive/2017/01/30/0019/0670/1295006/06/d588e67506.jpg
I chose the theme needed and save. But it does not help pulling layouts.

### Additional information
Exactly the same bug was described here - http://magento.stackexchange.com/questions/145687/magento-2-v2-1-2-choosing-separate-theme-for-product-page
And the solution was not found.

**Comment by ChevCheusov** [comment]
The same bug is in the Magento 2.1.3.
Updating up to the latest release did not help.

**Comment by ChevCheusov** [comment]
Hello, 
Magento
Is there any news on the bug described above?
Thank you!

**Comment by magento-engcom-team** [comment]
@ChevCheusov, thank you for your report.
We've created internal ticket(s) MAGETWO-81795 to track progress on the issue.

**Comment by soncp** [comment]
Is there any update on this one?

**Comment by svenpro** [comment]
Hello! I have the same bug in Magento 2.2, it is still not fixed?

**Comment by kirmorozov** [comment]
Hi, dived in into this issue this week,
Here is quick patch: https://gist.github.com/kirmorozov/38b26b88e959cb5487b0f722090749e1

**Comment by magento-engcom-team** [comment]
Hi @ChevCheusov. Thank you for your report. 
The issue has been fixed in magento/magento2#19124 by @drew7721 in 2.3-develop branch
Related commit(s):
 - [1becee9bb4114318c89f54b45c10b6b60cdc9cee](https://github.com/magento/magento2/commit/1becee9bb4114318c89f54b45c10b6b60cdc9cee)
 - [b8940db9514c672c9e191bbb33172884a524a993](https://github.com/magento/magento2/commit/b8940db9514c672c9e191bbb33172884a524a993)
 - [fd26b94dc1950845a135879937ce7ce0d8f8b8b4](https://github.com/magento/magento2/commit/fd26b94dc1950845a135879937ce7ce0d8f8b8b4)
 - [47e42a969d443715bf483f9e90eabfd2a141c930](https://github.com/magento/magento2/commit/47e42a969d443715bf483f9e90eabfd2a141c930)
 - [4b6100d1e991fc56f7ff9f8e0f0be0db7192328e](https://github.com/magento/magento2/commit/4b6100d1e991fc56f7ff9f8e0f0be0db7192328e)
 - [b8442a15bb1fed7843166bdd4437c009ef03a82f](https://github.com/magento/magento2/commit/b8442a15bb1fed7843166bdd4437c009ef03a82f)

The fix will be available with the upcoming 2.3.1 release.
