### ISSUE TITLE
Special price not showing correct for in future discounts

### ISSUE THREAD

**Issue by henk-hypershop** [magento/magento2#8375]
**Precoditions**

- Magento 2.1.3
- NGINX

I have setup a configurable product with 3 simple products attached.

I would like to give the simple products a discount price, with a special price from date in the future. However, on the frontend the special price is shown. When i go to this product page, i can see that none of the simple products show the discount price.

This seems like an issue to. Has anyone else experienced this problem?
![screen shot 2017-02-01 at 21 09 46](https://cloud.githubusercontent.com/assets/24226635/22524269/d923ab78-e8c2-11e6-9161-246c1ff95591.png)
![screen shot 2017-02-01 at 21 10 08](https://cloud.githubusercontent.com/assets/24226635/22524271/d926d32a-e8c2-11e6-84fa-be0c7da89d66.png)
![screen shot 2017-02-01 at 21 10 13](https://cloud.githubusercontent.com/assets/24226635/22524270/d92624ac-e8c2-11e6-82d7-0c09d06e436c.png)

**Comment by miakusha** [comment]
Hi @henk-hypershop , thanks for report

We've created internal ticket MAGETWO-64221 to address this issue.

**Comment by henk-hypershop** [comment]
What is the status of this issue?

**Comment by veloraven** [comment]
This issue was fixed in develop branch.
Closed.

**Comment by korostii** [comment]
Hi @veloraven,
Are there any plans to backport this fix?

**Comment by batmike** [comment]
@korostii - I just came across this fix so it hasn't been fixed yet in v. 2.1.7. I copied in the change from commit 1ab9b26 to vendor/magento/module-configurable-product/Pricing/Price/LowestPriceOptionsProvider.php and it worked for me.

**Comment by henk-hypershop** [comment]
@korostii You should not make changes in your vendor folder.

**Comment by korostii** [comment]
@batmike, @henk-hypershop,
Yes, please keep in mind everyone that patching `vendor` is _not_ a robust solution, since the fixes you place this way will get discarded with the very next version of CE you update to, and you'll have to re-apply them all over again! 
However, it still by far the fastest end the most low-effort way to go around these (unless it's either okay for you to wait a few months for the official release or you have a friendly neighborhood developer around which can make the override for you on module level).
