### ISSUE TITLE
Custom Checkout Step and Shipping Step are Highlighted and Combined upon Checkout page load

### ISSUE THREAD

**Issue by natebatty** [magento/magento2#8410]
### Preconditions

1. Magento 2.1
2. PHP 7

### Steps to reproduce

1. Create a custom checkout step. Set the step to appear first.
2. Start the checkout process
3. Both my custom step and the shipping step are displaying and highlighted
4. Upon using the next buttons the steps show up in their own section

### Expected result

1. Shipping step should be hidden since it is now step 2

### Actual result

1.  Both my custom step and the shipping step are displaying and highlighted

**Comment by psyklopz** [comment]
I can confirm the same behavior.  I also created a custom checkout step (sortOrder: 0 in the xml, sortOrder:5 in js) so that it would appear before the shipping step.  When you first visit the checkout, it will show both steps highlighted on the top bar.  Additionally, the content for both steps will both be shown until you click the next button.  It will run the validator for my custom step, then move to the shipping step.  From here, I can move back to my custom step and it will display only my custom step.  Not surprisingly, I can also visit "http://localhost/checkout/#mycustomstep", and it will properly display my step on it's own.

Attached is a zip of my module, which may be helpful in debugging this issue.
[CustomCheckoutStepBug.zip](https://github.com/magento/magento2/files/962890/CustomCheckoutStepBug.zip)

**Comment by psyklopz** [comment]
There may be a workaround described in this issue report, but I'm still trying to understand what is said... #8875

**Comment by psyklopz** [comment]
Confirmed it's also an issue with:
### Preconditions

Magento version 2.1.6
PHP version 5.6.30
Used browser: Google Chrome, Mozilla Firefox

**Comment by magento-engcom-team** [comment]
@natebatty, thank you for your report.
We've created internal ticket(s) MAGETWO-83363 to track progress on the issue.

**Comment by okorshenko** [comment]
Hi @natebatty 
The issue has been fixed and delivered in 2.2-develop branch. Will be available with upcoming patch release.

**Comment by ryangerber1990** [comment]
This wasn't fixed
