### ISSUE TITLE
Button Submit Shipment not exists

### ISSUE THREAD

**Issue by ghost** [magento/magento2#8424]
### Preconditions
Magento 2.2.0 (061977e46fdd0126a939761379d482ab5e27d5e0)

### Steps to reproduce
1. Create simple product
2. Submit order with simple product
3. In admin go to Order->Ship
4. In page Create new Shipment observe button "Submit Shipment"

### Expected result
1. Button is visible
2. Items is visible

### Actual result
1. No button. In dev mode exception

Can be cured by reverting 5831ca1 by Sylvain Rayé

**Comment by mbrinton01** [comment]
Reproduced on https://github.com/magento/magento2/commit/988f3a37bc17b458c98bfa0a1dc0238805f98380.

Screenshot of missing Submit Shipment:

<img width="855" alt="screen shot 2017-02-09 at 11 31 31 am" src="https://cloud.githubusercontent.com/assets/10635536/22779510/5b9147b6-eebb-11e6-8f89-97a02e1450f0.png">

**Comment by digixweb** [comment]
I have this same problem with 2.1.4 in both default and production mode. Reverting to suggested commit did not solve it.

**Comment by ghost** [comment]
In my case "shipment_item_default" does'nt resolve my problem, i changet it to "default" and it work clearly :).
Link here https://github.com/magento/magento2/commit/5831ca1e833b3ccf18f43fcc6e6988b2e7c7afb3

**Comment by Stas94** [comment]
@butthurt We cannot reproduce this issue as described. Please provide the detailed steps we must follow to reproduce this issue. In addition, identify the web server you are running, the versions of PHP and MySQL, and any other information needed to reproduce your issue.

**Comment by ghost** [comment]
@Stas94 Thanks
[http://take.ms/uYZNv](http://take.ms/uYZNv)

**Comment by veloraven** [comment]
@butthurt does it mean that this issue is not actual any more?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by ahnbizcad** [comment]
I have the same issue on 2.1.11
PHP version is 5.6.33
MariaDB/MYSQL version is 
`mysql  Ver 15.1 Distrib 10.2.12-MariaDB, for Linux (x86_64) using readline 5.1`


The portion of the layout mentioned in the OP already comes "reverted" for me.
In other words, my code is

`<block class="Magento\Sales\Block\Adminhtml\Items\Renderer\DefaultRenderer" name="default" template="Magento_Shipping::create/items/renderer/default.phtml"/>`
rather than
` <block class="Magento\Sales\Block\Adminhtml\Items\Renderer\DefaultRenderer" name="shipment_item_default" as="shipment_item_default" template="Magento_Shipping::create/items/renderer/default.phtml"/>`

and I am still getting the missing button behavior.
In other words, rolling it back doesn't resolve the issue for me as it does for the OP.

_____

Is all of this due to not having shipping method options set up?
If the button missing is due to not having shipping method options configured would seem like a silent failure.
In that case, a greyed out shipping button with a hover of "no shipping methods configured" would be more traceable.
But this is all a big if.

_____

I'm creating orders programmatically, by sending in a shipping method string for the order.
If that string is somehow invalid, would it result in the button disappearance behavior?

_____

In M2, shipments can be sent before invoicing. so the problem does not stem from not having invoicing.
or even sending an email.

**Comment by ahnbizcad** [comment]
In programmatic creation of an order, the shipping method string requires a `_` character.
That caused the shipping button to show.

It seems a bit left field that this would cause the button to not show.
