### ISSUE TITLE
Duplicated line on invoice/order for configurable product

### ISSUE THREAD

**Issue by Tapin1** [magento/magento2#8452]
Hello.
When configurable product is ordered, Magento show 2 lines in order (and in invoice)
configurable product generates 2 lines : one with the actual price and the other one with $0 price. 

Can anyone help me with this duplicate issue? Thank you in advance.

### Preconditions

1. Magento 2.1.0
2. Php 7

### Steps to reproduce

1.  Set SIMPLE PRODUCT visible on search
2. MAKE AN ORDER (order configurable product)
3. Look at orders in backend

### Expected result

1.  I don't expect duplicated items in orders or invoices

### Actual result

1. uplicated items in orders or invoices

[Screenshot, logs]
![d8502db46c](https://cloud.githubusercontent.com/assets/22484149/22698884/e1f2a2e2-ed66-11e6-8062-e8cb8ef8e91c.jpg)

**Comment by Tapin1** [comment]
No one has similar bug?

**Comment by eTonki** [comment]
I have the same problem on Magento CE 2.1.4 
Someone has solved the problem? 

Might be some external extension installed?
If you put a list of your extensions I can see if we have some the same and try to turn it off.

Hello

**Comment by Tapin1** [comment]
No extensions. Default installation
This happens only when child products of configurable set to “visible on search”
If you switch visibility to “Not Visible Individually” – everything works fine

**Comment by eTonki** [comment]
My child products are "Not Visible Individually" and the parent is 'Catalog, Search'.
But the problem I have the same.
The problem disappears if I put the children 'Catalog, Search' and I purchase directly to a child without going through the parent.
How is it possible that the problem have it in a few people?

**Comment by Tapin1** [comment]
If you buy directly child - no problem
If you buy it from configurable - problem still persist

Guys!!!  URGENT!!! Patch needed!!!
Any suggestions?

**Comment by EmilyPepperman** [comment]
We have this same issue. Ours appears when we updated the M2E Pro extension. 

![2017-02-24_16-42-01](https://cloud.githubusercontent.com/assets/12411491/23323812/559202a2-fab8-11e6-9220-59690e3d317e.png)


https://www.screencast.com/t/0C4RGgju

**Comment by eTonki** [comment]
I also use M2E Pro extension,
if @Tapin1 uses it, we found the first suspect.

**Comment by Tapin1** [comment]
Yes, I use it too.

**Comment by zajazdowicz** [comment]
The same issue here ( M2.1.3, m2epro installed ), if someone has a sollution for this, please share.

**Comment by eTonki** [comment]
I created the ticket in "m2 and pro", 
they asked me the data to access the site, 
you'll know how to solve it.

**Comment by EmilyPepperman** [comment]
What version of M2E Pro is everyone using? 
I didn't have this issue with an older version... when I updated only the M2E extension it appeared... at one point I even rolled back to the old version again and the problem went away... but the version was getting stale and when they released 1.3.1 I updated and the issue is there again. I do have a ticket in with M2E I gave them all the details that I could... this is last response. 

Dear Emily,

The issue you submitted is very uncommon and requires a complex analysis. 

We are waiting for an update from the developers and as soon as we have information, we will contact you. 

-----
Best Regards,
Anna
M2E Pro Support Team

**Comment by zajazdowicz** [comment]
I'm using ver. 1.2.1, also gave them access to backend to check it out, will let you know if they find anything.

**Comment by mbrinton01** [comment]
@Tapin1 I am not able to reproduce this issue on:
- _develop_
- _2.1.0_
- _2.1.1_

I checked the order, invoice admin page, and printed invoice for all three versions and there was no issue. I set the child of the configurable product I used for the test order to `visibility=Catalog, Search` and also ran a separate test where `visibility=Not Visible Individually`.

I'm closing this issue as it looks to be caused by the M2E extension.  If you find this is not the case after researching with the extension provider, please open a new issue.

**Comment by EmilyPepperman** [comment]
This is a reproduce-able issue... if you also have M2E pro installed. @mbrinton01 M2E has given us a updated file that DOES solve this bug. Atleast 4 documented people have had this issue. 
app\code\Ess\M2ePro\Plugin\Order\Magento\Quote\Model\Quote\Item\ToOrderItem.php

**Comment by mbrinton01** [comment]
If the issue is only present with M2E pro then please use the fix they have provided.

**Comment by zajazdowicz** [comment]
@EmilyPepperman Could You please provide the sollution for this ? I contacted m2epro team last week regarding this issue but since then, no hear from them...

**Comment by eTonki** [comment]
The solution is this: 
[https://community.m2epro.com/topic/258-magento-2-issues-with-m2e-pro-need-help-frustrated/#comment-716](https://community.m2epro.com/topic/258-magento-2-issues-with-m2e-pro-need-help-frustrated/#comment-716) 

Regards

**Comment by gewaechshaus** [comment]
Same here...

**Comment by 2dogrc** [comment]
Hello,
 I am getting this issue on Magento 2.2 store, m2E is NOT installed.  I did not that configurable products are different in 2.2 then 2.1.7.  In 2.2 The price is not editable and the block is 0.00. In 2.1.7 the block is not editable, but there is a price listed. there.
This is 2.1.7
<img width="1680" alt="screenshot 2018-03-18 22 16 55" src="https://user-images.githubusercontent.com/17340442/37574996-0b4c75e6-2afb-11e8-96e0-006d932b6333.png">

This is 2.2.2
<img width="1613" alt="screenshot 2018-03-18 22 25 00" src="https://user-images.githubusercontent.com/17340442/37575037-441f1b6c-2afb-11e8-80f5-e6a67ac12b8e.png">

This is the invoice which is very hard to read!
![screenshot 2018-03-18 22 24 31](https://user-images.githubusercontent.com/17340442/37575042-5050f48c-2afb-11e8-90b2-b7ec020be99c.png)
