### ISSUE TITLE
Use cursor: pointer for the product online switcher

### ISSUE THREAD

**Issue by kalenjordan** [magento/magento2#847]
I was thinking it would be good to use 

    cursor: pointer

for the product online switcher.

![switcher](https://cloud.githubusercontent.com/assets/1542197/5516472/d06c9c04-8854-11e4-9fbe-cb9689a5eceb.jpg)

Sound like a good idea?

If so, I was having a bit of trouble finding docs on how to compile less.

**Comment by vpelipenko** [comment]
The proposal has been taken into account by lead of Product Design and should be implemented in the future updates for backend theme.

**Comment by magento-engcom-team** [comment]
Hi @kalenjordan. Thank you for your report. 
The issue has been fixed in magento/magento2#25991 by @drpayyne in 2.4-develop branch
Related commit(s):
 - [9f1be1dbba124ca102ec414fa82f7e4967341d4e](https://github.com/magento/magento2/commit/9f1be1dbba124ca102ec414fa82f7e4967341d4e)
 - [8c4b6d6cb45fee6962ff7827832a9da79cd1aaa4](https://github.com/magento/magento2/commit/8c4b6d6cb45fee6962ff7827832a9da79cd1aaa4)
 - [6aeb8653333b0ec8ca926ac81a73b39e17b78467](https://github.com/magento/magento2/commit/6aeb8653333b0ec8ca926ac81a73b39e17b78467)
 - [56daae0ce5f2b0805683786b54c1a65c26fc2e28](https://github.com/magento/magento2/commit/56daae0ce5f2b0805683786b54c1a65c26fc2e28)
 - [edc16d5f70dfd1ea3b0223834c657b7ab576826f](https://github.com/magento/magento2/commit/edc16d5f70dfd1ea3b0223834c657b7ab576826f)
 - [5cc2dc77f59d941b524e5879318ab0b7e509cebe](https://github.com/magento/magento2/commit/5cc2dc77f59d941b524e5879318ab0b7e509cebe)
 - [7a88ffc63d9578865e19b9946a7bf368d6a1dda6](https://github.com/magento/magento2/commit/7a88ffc63d9578865e19b9946a7bf368d6a1dda6)

The fix will be available with the upcoming 2.4.0 release.

**Comment by drpayyne** [comment]
Hi @magento-engcom-team, how exactly did I fix this issue in https://github.com/magento/magento2/pull/25991? I'm confused this is linked to that.
