### ISSUE TITLE
Consumer token always expires when REST API based oauth is done

### ISSUE THREAD

**Issue by jinujd** [magento/magento2#8493]
I was trying to do oAuth based authorization for mobile app development.
So as said in the docs, the first step, is requesting a token.
I did it as follows.
http://ihive.in/m2/oauth/token/request?oauth_consumer_key=iejx013hj015j5d7wo2uqh8sqvtx3o58&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1486664140&oauth_nonce=AIwhKlQCsgk&oauth_version=1.0&oauth_signature=j7V1h8866p7PE8kuILVK9cWaaFE=
Note : All the parameters are put in Authorization header.
But I am getting the following error always.
`oauth_problem=Consumer+key+has+expired`

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by feelinc** [comment]
I think it's a bug, I'm also having the same issue.

I have change the Consumer Expiration Period value to zero at Stores -> Configuration -> SERVICES -> OAuth -> Consumer Settings. The $expiry always return "300" in "\Magento\Integration\Model\Oauth\Consumer::isValidForTokenExchange" method.

If I'm bypass the expiration validation, the /oauth/token/request returning "Cannot create request token because consumer token is not a verifier token".

I'm not sure what process should I use, so the mobile app able to use the Magento 2 API securely without have to hardcode the Access Token and Access Token Secret inside the mobile app source.

**Comment by rfink** [comment]
This is definitely an issue - the updated_at field (which seems to be used for expiration calculation) seems to always be set to 0000-00-00 00:00:00

**Comment by misha-kotov** [comment]
Make sure you provide the `callback url` and the `identity link url`
