### ISSUE TITLE
Magento 2 does not have a api call to add multiple product cart in a single call

### ISSUE THREAD

**Issue by umang-ranium** [magento/magento2#8501]
### Preconditions

1. use api call guest-carts/27f7f91cf4344bb9bda7d30b076216f3/items

### Steps to reproduce

1. use api call guest-carts/27f7f91cf4344bb9bda7d30b076216f3/items
2. post data sku qty

### Expected result

1. There should be a way to add multiple product to cartt, why this functionality is not provided.

### Actual result

1. Can only add 1 product in 1 call to cart

**Comment by atishgoswami** [comment]
Hi @umang-ranium,

Can you please provide the following details:

- Which version of magento are you on ?
- Is it Community or Enterprise ?

Think why it is this way is because Magento native (from the browser) "Add to Cart" functionality also only allows the user to add one product as a time.

If you would like to add products to cart in bulk you will have do some customization to the functionality. If that's your case you can post a question on [stackexchange](http://magento.stackexchange.com/) and people might help you out on this.

Thanks

**Comment by umang-ranium** [comment]
i am using magento 2.1 community edition can you please help with the api call and data to post. Thanks in advances.

**Comment by atishgoswami** [comment]
Hi @umang-ranium,

You will have to post a question [stackexchange](http://magento.stackexchange.com/), so that people in the stackexchange community help you out on this.

Secondly, please close the this issue as it seems it not a issue but a feature requirement.

Thirdly, whenever providing the magento version be specific on the version number. Magento 2.1 is a very vague version number as it could be 2.1.1 or 2.1.2 or 2.1.3 or 2.1.4, so keep this in mind when providing the version number.

Thanks

**Comment by magento-engcom-team** [comment]
@umang-ranium, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by magento-engcom-team** [comment]
Hi @umang-ranium. Thank you for the report. We are moving your feature request to the special project. You can track this issue here: https://github.com/magento-engcom/community-features/issues/31
