### ISSUE TITLE
No ability to reset filters after an error

### ISSUE THREAD

**Issue by spyrule** [magento/magento2#8538]
If a filter is applied to the Product Categories window, if that filter is removed, it generates a "Something went wrong" error, that prevents you from ever "erasing" the problematic error.

### Preconditions
1. Magento 2.4-develop
2. PHP 7.3
3. Nginx hosted service

### Steps to reproduce
1. Create a new store view (call it test for example)
2. Log into admin > Products > Catalog 
3. Set up and apply a filter for the newly created store view;
4. Now, go to Admin->Stores->All Stores;
5. Delete the created before "test" store view;
6. Switch back to the Product Catalog, you'll get "Something went wrong" error

### Expected result
1. If there is an error in selecting a filter option, it should apply NO FILTER at all, and indicate that a filter option was broken.

### Actual result

:heavy_multiplication_x: _Attention. Something went wrong_
![Screenshot from 2020-04-08 11-34-07](https://user-images.githubusercontent.com/51679138/78767511-5b788580-7993-11ea-92f5-b574dc21e3ba.png)

**Comment by rogyar** [comment]
That's an annoying issue. Have a lack of time to find a sort of fix, but can recommend a workaround. When you get the "Something went wrong" message, open Developer Tools console in your browser and type there:

```js
jQuery('.action-clear').click();
```

That will simulate the "Clear All" link click for filters (tried in Chrome). Hope it will help.

**Comment by oleg-onufer** [comment]
Hi @spyrule.
Thanks for reporting this issue.
Internal ticket MAGETWO-70414 was created.

**Comment by magento-engcom-team** [comment]
@spyrule, thank you for your report.
We've created internal ticket(s) MAGETWO-70414, MAGETWO-80634 to track progress on the issue.

**Comment by RomaKis** [comment]
This issue was fixed by the commits: 
https://github.com/magento/magento2/commit/2933325, https://github.com/magento/magento2/commit/550ae56,
https://github.com/magento/magento2/commit/478b0ec,
https://github.com/magento/magento2/commit/a6a2301,
https://github.com/magento/magento2/commit/aafcc0b.
@magento-engcom-team, I think you can close this ticket.

**Comment by 4DallasC** [comment]
I think you can do it from database, go to database and ui_bookmark table
Remove entry/s for your user id and namespace you need to remove the filtering

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
HI @spyrule this issue was tested, and we can confirm , that this issue already fixed on 2.3.0 release.

**Comment by j-lloyd-slc** [comment]
This issue is still a problem in 2.3.3

**Comment by sdzhepa** [comment]
Reopened due to https://github.com/magento/magento2/issues/8538#issuecomment-610479283

The issue should be re-verified on `2.4-develop` branch according to [Issues Processing Workflow](https://github.com/magento/magento2/wiki/GitHub-Issues-Processing-Workflow)

**Comment by j-lloyd-slc** [comment]
To clarify, the problem I am seeing may be different. The filters can be reset after the error occurs, which is good.

However, the error message persists after a new filter is submitted, which is confusing and suggests that the subsequent filtering may not be reliable.

Also, the root of the issue (in my case) was a migrated product with a NULL sku. In 1.9 these are "broken", but can be listed/viewed/deleted, etc. In 2.3.3 (and 2.3.0) products with NULL skus create unpredictable behaviors in the admin and can not be delete or edited.

**Comment by engcom-Alfa** [comment]
@sdzhepa The issue is still reproducible on fresh 2.4-developer instance

**Preconditions:**
1. Magento 2.4-develop;
2. PHP v7.3

**Manual testing scenario:**
1. Create a  new store view (call it "Second Store View" for example);
2. Log in to Admin -> Catalog -> Products;
3. Set up and apply a filter for the newly created store view;
![screenshot1111](https://user-images.githubusercontent.com/51679138/78762028-0b49f500-798c-11ea-90ba-d98869350881.png)
4. Now, go to Admin->Stores->All Stores;
5. Delete the created before "Second Store View" store view;
6. Go to Admin->Catalog->Products again;

**Actual Result:**
:heavy_multiplication_x: _Attention. Something went wrong_
![Screenshot from 2020-04-08 11-34-07](https://user-images.githubusercontent.com/51679138/78763310-a42d4000-798d-11ea-883e-c92eb464e154.png)

and the error message persists after a new filter is submitted which is the wrong behavior
![Peek 2020-04-08 12-09](https://user-images.githubusercontent.com/51679138/78766372-db9deb80-7991-11ea-9122-14fddd9f001e.gif)

The description will be updated and the issue will be approved.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33191` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @spyrule. Thank you for your report. 
The issue has been fixed in magento/magento2#28687 by @AbdulRahmanAbouzaid in 2.4-develop branch
Related commit(s):
 - [674324c6ae3cdee5c664bac6be3e275070bda758](https://github.com/magento/magento2/commit/674324c6ae3cdee5c664bac6be3e275070bda758)
 - [9fac5f7173db77e933e5a59e671151d9bf0b62c2](https://github.com/magento/magento2/commit/9fac5f7173db77e933e5a59e671151d9bf0b62c2)
 - [3852c89cebccfef1da7242d73be40e4d831d3a97](https://github.com/magento/magento2/commit/3852c89cebccfef1da7242d73be40e4d831d3a97)
 - [7517b21aa87f9e47aefa1ef0986f0198e6f4d70b](https://github.com/magento/magento2/commit/7517b21aa87f9e47aefa1ef0986f0198e6f4d70b)
 - [cef2186708426f7683cbd38d308562b2aa80ff46](https://github.com/magento/magento2/commit/cef2186708426f7683cbd38d308562b2aa80ff46)

The fix will be available with the upcoming 2.4.2 release.

**Comment by joinso** [comment]
Hi!

We see the same error on Order Grid in Magento 2.3.5

Regards,
JOINSO

**Comment by arzezniczak** [comment]
I have the same issue on 2.2.8

Regards,
Adrian

**Comment by mweaver-inmusic** [comment]
This is still an issue in magento ver. 2.3.6
