### ISSUE TITLE
Setup wizard option not displaying within System >> Tools, Magento ver. 2.1.2 

### ISSUE THREAD

**Issue by neerajproweb** [magento/magento2#8629]
Successful installed magneto 2.1.2, but 'Setup Wizard' option not displaying within 'System' >> 'tools'.
can you please help for solve this issue ASAP.

Thanks,

**Comment by Radiergummi** [comment]
*push*  
Seems to be the same as #7623, #5235, #5247, #4159 and #7616. Still not fixed, still blocking my project.

**Comment by ghost** [comment]
I also have this issue and nowhere is there any solution!

**Comment by Radiergummi** [comment]
This has been a week already - any news?

**Comment by korostii** [comment]
> a week already

Ha-ha, that's funny. You must be new here. Let me briefly explain of the reaction you could expect from Magento, Inc. regarding your issue.

**If** it gets changed right away, there's still 2 months on the average for the change to get through the testing process and reach a release.
It would speed up the process, if you could provide a pull request with the fix, otherwise chances are you'll get it fixed earlier if you work around it locally in your codebase, rather than wait for a fix to get released.

Otherwise, you will also need for the Magento team to do the following:
1) Confirm that your issue report conforms to the [guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines). Otherwise it'll get a "needs update label" and will be closed in two weeks unless you provide additional information.
2) Reproduce your issue on a clean installation using the steps you provide. If they are unable to reproduce the issue, it'll get a "needs update label" and will be closed in two weeks unless you provide additional information.
3) From there, it might go one of the following ways:
  -  If the issue will turn out to be caused by a misconfiguration on your end, customized code or insufficient installation environment (bad file permissions, etc.), no additional assistance will be provided. You'll get redirected [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/) because the GitHub issue tracker is intended for tracking technical issues (read: "bugs") only.. 
  - If the issue will turn out to be caused by a 3rd-party module, you'll get redirected to either the module vendor. 
  - If the issue will, in fact, get reproduced on a clean installation and is considered to be a bug (and not a suggested improvement or feature request), only then it'll get acknowledged and will be tracked by the Magento development team. Which, you know, still doesn't guarantee neither that someone will start fixing it right away (priorities!) nor any kind of timeline.

**Comment by Radiergummi** [comment]
Please, let *me* briefly explain my view on this issue. Within a week, I wouldn't expect a fix for a newly reported issue - Magento is pretty big and complex and requires a copious amount of testing, that's clear to me. But I'd **at least** expect someone reporting about the current progress of fixing a problem **known since at least April 2016**.  
You see, as I wrote in a previous comment on this issue, that the problem has been reported by various users in various issues, SE posts and forum threads. The Magento team did mostly ignore those reports, then stated the problem has been fixed, only to find out it has been erroneously marked fixed while it was actually still pending.  
The issue has been reproduced in fresh installations multiple times, including on my current project. Considering the premium price of Magento Enterprise, the "not really open source" status of the Magento code and the pretty much non-existing support, I refuse to do the work for Magento, Inc. to be honest.  

Besides, this problem has an internal bug tracker number already, which is `MAGETWO-52799`, so while I appreciate the time you took to detail the process of reporting bugs in Magento, it's pretty much void in this case.  
I fail to understand why a core functionality of a software ecosystem - the ability to update and install extensions many third-party developers sell - can be dysfunctional for a large part of the user base in a commercial product.

**Comment by korostii** [comment]
No need to convince me, I'm not an employee of Magento, Inc. neither. 
Just saying that considering Magento's current approach to bugfixing and treating GitHub Issues it is unreasonable to expect a timely or reasonable response from them here.
Which is infuriating. 

There were some changes starting a couple months ago, and they made a dedicated team which started to sort it out and engage with the community. They are now processing the pull requests, [far from being done](https://github.com/magento/magento2/projects/3) and I guess issues' priority is even less.

I'd say It would be reasonable to expect they'd at least take a glimpse at the [top commented issues INCLUDING closed ones](https://github.com/magento/magento2/issues?q=is%3Aissue+sort%3Acomments-desc) and do something about those (put them into development with a high priority is ideal, but at least an official response would be nice).

I would guess you'd need a shout to [maksek in twitter](https://twitter.com/maksek_ua) in order to bring any attention to the issue. 

Still, I think the most ironic thing is that if more attention would be given to the bugfixing and patching early on, the github wouldn't become such a overflooded mess. I already [wrote about that before](https://github.com/magento/magento2/issues/7943#issuecomment-270862382) and I stand by that opinion.

**Comment by Radiergummi** [comment]
I'm sorry, this is just so absurd I overreacted a little... 
Thank you for your extensive answer though, maybe it's time to head over to another shop system for me, something like Reaction maybe. No matter how worse the situation will be somewhere else, it can't be like with Magento.

**Comment by rparsi-commer** [comment]
@Radiergummi Unfortunately for me I'm stuck with magento2, was brought into project months after got started.
As for alternatives, so far my magento2 pain aka "learning curve" has shown me that Shopify and even PrestaShop are far better in terms of developer experience.

**Comment by rparsi-commer** [comment]
@neerajproweb
@Radiergummi
@seowhite
@korostii

I'm working on same issue, found temporary workaround.
See my comment [here](https://github.com/magento/magento2/issues/5247)

**Comment by magento-engcom-team** [comment]
@neerajproweb, thank you for your report.
The issue is already fixed in develop branch, 2.2.0, 2.1.9
