### ISSUE TITLE
How to switch base,thumbnail images in magento 2 back end 

### ISSUE THREAD

**Issue by nmohanswe** [magento/magento2#863]
Hi

I didn't noticed the option to switch the Base, Thumbnail and Small Images in Magento 2 Backend while adding new products.
any one can help?

**Comment by magento-engcom-team** [comment]
Hi @nmohanswe. Thank you for your report. 
The issue has been fixed in magento/magento2#26502 by @konarshankar07 in 2.4-develop branch
Related commit(s):
 - [c9d5e8ef8e3b12f6483ec02e2bf561c2752b68d1](https://github.com/magento/magento2/commit/c9d5e8ef8e3b12f6483ec02e2bf561c2752b68d1)
 - [8357cf80e7cde248c091bf7fef6934c40e47400a](https://github.com/magento/magento2/commit/8357cf80e7cde248c091bf7fef6934c40e47400a)
 - [a17c2a51d226f810ddc5bf32a7b28b23b6b59ea2](https://github.com/magento/magento2/commit/a17c2a51d226f810ddc5bf32a7b28b23b6b59ea2)
 - [7fafb2d13517705d86ca0c65cfa52d52bd1c5c40](https://github.com/magento/magento2/commit/7fafb2d13517705d86ca0c65cfa52d52bd1c5c40)
 - [9de1e591300d8b77a7aeeffda2c3c01ab4763e55](https://github.com/magento/magento2/commit/9de1e591300d8b77a7aeeffda2c3c01ab4763e55)
 - [c3ba2ce2468e04ed87f11c8a2cbac7732ef1fe40](https://github.com/magento/magento2/commit/c3ba2ce2468e04ed87f11c8a2cbac7732ef1fe40)
 - [0aef9add469dda3a0102b886b008757469bb8f26](https://github.com/magento/magento2/commit/0aef9add469dda3a0102b886b008757469bb8f26)
 - [7ef0c88e9c0b452a5e43ad0189a052a4dab500a8](https://github.com/magento/magento2/commit/7ef0c88e9c0b452a5e43ad0189a052a4dab500a8)
 - [a1d2a846d5752eb3708155ecc9468835d82f4504](https://github.com/magento/magento2/commit/a1d2a846d5752eb3708155ecc9468835d82f4504)
 - [1f2ed9035507c8ebf46ddacd0e9c923206ffec0d](https://github.com/magento/magento2/commit/1f2ed9035507c8ebf46ddacd0e9c923206ffec0d)

The fix will be available with the upcoming 2.4.0 release.
