### ISSUE TITLE
Passing Variables from Magento to requirejs-config

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#8650]
I am trying to add https://github.com/aerisweather/googlemaps-amd and https://github.com/codegile/gmaps-markerwithlabel-amd

They both need a api key for google maps being added to their require js config.

### Preconditions
1. Magento 2.1.5

### Steps to reproduce
1. In your phtml:

```
<script type="text/x-magento-init">
    {
        "*": {
            "xyz/js/storelocator": {
                "apiKey" : 'xxx',
                "defaultLat" : -25.363,
                "defaultLng" : 131.044            }
        }
    }
</script>
```

In my requirejs-config.js for my module:

```
var config = {
    config: {
        'googlemaps': {
            key: 'xxx'
        },
        'markerlabel': {
            api_key: 'xxx'
        }
    },
```

How can I inject that key into the module? Is this even the right place? How do I pass params to a amd module?

### Expected result
1. Pass the variable

### Actual result
1. It's not possible

**Comment by orlangur** [comment]
You can get the idea from Google Analytics implementation: https://github.com/magento/magento2/blob/f298ef5f4f802e0f91b64b3123052c2940f3f87a/app/code/Magento/GoogleAnalytics/view/frontend/templates/ga.phtml#L21

Please use http://magento.stackexchange.com for asking questions instead of GitHub so that the answer may help others in the future.

**Comment by cscd98** [comment]
@orlangur That's not really going to work as then I can't use it as a require in another javascript file.

Will do

**Comment by orlangur** [comment]
@craigcarnell you are not going to commit API Key into source code, do you?

Sorry, I may not understand your problem from first attempt. If you need to integrate any non-Magento-aware library you need to make a wrapper.

Here is an example of `fotorama` integration: https://github.com/magento/magento2/blob/develop/lib/web/mage/gallery/gallery.js#L129 Leaving finding a place where `gallery` is initialized as a homework ;)

**Comment by cscd98** [comment]
@orlangur Hi, the key is stored in sytem->config area and is passed using the text/x-magento-init method above to the relevant javascript file.

I don't want to store any api keys in source code!

But I don't see how to get the api key from magento into the requirejs-config where it is required.

Will look into the above.

It all depends also on how the amd module is structured.

**Comment by orlangur** [comment]
@craigcarnell the key point here is that you must not use third-party libraries directly even when they support AMD loading.

> key is stored in sytem->config area and is passed using the text/x-magento-init method above to the relevant javascript file

It is not a good idea to pass PHP variables to `requirejs-config.js` (technically it is possible to put anything into anything but better is those files remain static), I'm not sure there is builtin mechanism to have some `requirejs-config.js` file template instead of file.

You can initialize third-party components directly using `<script type="text/x-magento-init">` or create wrappers on top of them with proper `requirejs-config.js` files but dynamic parameters from PHP side will still be passed through `<script type="text/x-magento-init">`.

**Comment by orlangur** [comment]
GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions.

Initial question seem to be answered to me, StackOverflow is the best place for exact snippets of code.
