### ISSUE TITLE
URL key for specified store already exists error on product save with same name

### ISSUE THREAD

**Issue by vmasciotta** [magento/magento2#8679]
### Preconditions

1. Any magento2 version
2. PHP >= 5

### Steps to reproduce

1. create a new simple product, name it "red shirt" and save
2. create another new simple product, name it again "red shirt" and save it

### Expected result

1. The second "red shirt" should be saved successfully even if another product with the same name already exists
2. url-key should be automatically updated with -x suffix in order to prevent this behavior

### Actual result

1. error message _URL key for specified store already exists_

If I _save and duplicate_ the first "red shirt" product it works as expected, a new product will be created and the system will add a _-x_ suffix to the url-key, everything is fine. 
Why it doesn't work for a _normal_ save? I mean, I read the code and I know why, but is this a feature or a bug?

**Comment by orlangur** [comment]
This works as intended.

One of the main differences between M1 and M2 urlrewrites is that in M2 merchant has full control over what is going on with URLs on his site. The main reason for this change is SEO as in M1 it is not guaranteed that after reindex the same numeric suffix will be preserved.

In M2 just specify in `URL Key` value other than autogenerated to avoid collision. 

Possible UX improvements I see here:
- some `Generate Good Suffix` button or mode for `URL Key` field which picks the appropriate _-x_  suffix for you (so that it works similar to M1 but without negative impact on SEO);
- of course, as it was already reported many times here, for massive operations like category movement or save there should be clear message for merchant which entities shall be edited to fix the collision;

**Comment by orlangur** [comment]
System behaves normally in current implementation if your data is valid in the first place. If https://github.com/magento/data-migration-tool produces invalid data in some cases, it should be reported.

Error message was improved on Magento 2.2.0 branch to give more information to merchant what exactly needs to be changed.
