### ISSUE TITLE
Category X-Magento-Tags too long causing Varnish to 503

### ISSUE THREAD

**Issue by djfordz** [magento/magento2#8696]
I have a customer site that Varnish is 503'ing on Category pages that have a too long X-Magento-Tags similar to this issue here: https://github.com/magento/magento2/issues/6401.

### Preconditions

 

1. Magento 2.1.3
2. CentOS 6
3.  Mysql Ver 14.14 Distrib 5.6.32-78.1
4. PHP 7.0.16

### Steps to reproduce

1. Enable Varnish for page cache
2. Add over 5000 categories greater than 4 levels deep each level with hundreds more categories
3. try to goto category page

![screenshot from 2017-02-27 10-22-30](https://cloud.githubusercontent.com/assets/5413221/23369381/cdaefb12-fcd6-11e6-802f-b1a1e92a4b23.png)

### Expected result

1. Category Page displays

### Actual result

1. [Screenshot, logs]
  503 Varnish Cache Error
![screenshot from 2017-02-27 10-24-17](https://cloud.githubusercontent.com/assets/5413221/23369422/ed1878a2-fcd6-11e6-8bd6-91a8dde271fb.png)

**Comment by logan-robbins** [comment]
I ran into this problem and I think Magento updated documentation to explain how to extend the parameter value in the varnish config. 

http://devdocs.magento.com/guides/v2.0/config-guide/varnish/tshoot-varnish-503.html

**Comment by dcabrejas** [comment]
I have encountered this issue on a Magento site running on 2.1.5. Category pages containing a large number of products return aX-Magento-Tag header which is bigger than the size allowed by the HTTP specification.

We have implemented this workaround for now http://devdocs.magento.com/guides/v2.0/config-guide/varnish/tshoot-varnish-503.html

But this is not a solution, just a workaround because the http header size is still larger than the limit set by the HTTp specification.

**Comment by magento-engcom-team** [comment]
@djfordz, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
