### ISSUE TITLE
Javascript Error After Upgrading to Magento CE 2.1.5

### ISSUE THREAD

**Issue by rendyep** [magento/magento2#8705]
### Preconditions
1. Apache 2.4.23
2. PHP 7.0.10
3. MySQL 5.6.30
4. Firefox 51.0.1

### Steps to reproduce
1. Upgrade Magento CE from 2.1.2 to 2.1.5
2. Go to homepage

### Expected result
1. When I load the admin page, the page is loaded successfully.
2. When I load homepage, the page is loaded successfully.

### Actual result
1. When I loaded the admin page, the page is loaded successfully.

2. When I loaded homepage, the page is loaded, but the loading took forever, and in some seconds, Firefox displayed a warning.
![capture1](https://cloud.githubusercontent.com/assets/5343517/23390602/29608420-fdaa-11e6-98ea-079441f9d0fd.jpg)

3. When I pressed "stop it", Firefox debugger displayed a lot of javascript errors.
![capture2](https://cloud.githubusercontent.com/assets/5343517/23390613/37534fd6-fdaa-11e6-819a-5b36f8aff30d.jpg)

4. After a few seconds, another warning displayed.
![capture3](https://cloud.githubusercontent.com/assets/5343517/23390637/5a0b6de2-fdaa-11e6-8781-d8ea07444366.jpg)

5. When I pressed "stop script", Firefox javascript debugger displayed error messages as shown in image.
![capture4](https://cloud.githubusercontent.com/assets/5343517/23390946/1cc9c30a-fdac-11e6-92f2-b37eb1f2e695.jpg)

**Comment by korostii** [comment]
Judging by the screenshots, you seem to have a lot of custom or 3rd-party code installed on top of Magento itself. If I were I'd first try switching off those one-by-one in order to find the source of the problem.
By the way, the browser's "Unresponsive script" pop-up window specifically mentions react.js which AFAIK is not part of Magento2 out of the box. Have you tried checking which of the 3rd party modules you've installed uses that file? I'd guess that module might simply be incompatible with Magento CE 2.1.5 and you'd likely need to contact the module vendor directly in that case.

**Comment by magento-engcom-team** [comment]
@rendyep, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
