### ISSUE TITLE
Unable to import/delete attribute value replacing with null value

### ISSUE THREAD

**Issue by kmgmkg** [magento/magento2#8746]
### Preconditions

1. Magento 2.1.0
2. Update existing attribute

### Steps to reproduce

1. Admin Section
2. System -> Import
3. Add/Update
4. Import csv to update attribute values (i.e. case=, package=2)

### Expected result

1. The attribute value for 'case' should be changed to null, but the existing value remains the same and is not replaced, while the attribute 'package' is updated with the correct value.

### Actual result

1. [Screenshot, logs]

**Comment by kmgmkg** [comment]
The attribute will be updated if you create an empty space, but an artificially created empty space isn't really empty space. Possibly this is the expected functionality?

Thanks,
Kevin

**Comment by magento-engcom-team** [comment]
@kmgmkg, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
