### ISSUE TITLE
CMS page is not editable

### ISSUE THREAD

**Issue by shivkumarsingh7** [magento/magento2#878]
CMS page is not editable

**Comment by magento-engcom-team** [comment]
Hi @shivkumarsingh7. Thank you for your report. 
The issue has been fixed in magento/graphql-ce#951 by @strell in 2.3-develop branch
Related commit(s):
 - [746038efe9fd49d0eb2c1f0349100d80f9ac4d10](https://github.com/magento/magento2/commit/746038efe9fd49d0eb2c1f0349100d80f9ac4d10)
 - [225c9f720d28c1d1ce077c333042a112dac0dd51](https://github.com/magento/magento2/commit/225c9f720d28c1d1ce077c333042a112dac0dd51)

The fix will be available with the upcoming 2.3.4 release.
