### ISSUE TITLE
Installation with sample data failing

### ISSUE THREAD

**Issue by jameswithers** [magento/magento2#881]
Following installation guide here: http://devdocs.magento.com/guides/v1.0/install-gde/install/install-overview.html. 

I get through to http://devdocs.magento.com/guides/v1.0/install-gde/install/sample-data.html:

```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for magento/sample-data 0.42.0-beta1 -> satisfiable by magento/sample-data[0.42.0-beta1].
    - magento/sample-data 0.42.0-beta1 requires magento/framework 0.42.0-beta1 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by magento-engcom-team** [comment]
Hi @jameswithers. Thank you for your report. 
The issue has been fixed in magento/graphql-ce#953 by @pmclain in 2.3-develop branch
Related commit(s):
 - [17ea0876fb2092231924bbdc0aee7846a4f59429](https://github.com/magento/magento2/commit/17ea0876fb2092231924bbdc0aee7846a4f59429)

The fix will be available with the upcoming 2.3.4 release.
