### ISSUE TITLE
REST API - Attribute option creation -> no ID returned

### ISSUE THREAD

**Issue by radoslavdodek** [magento/magento2#8810]
### Preconditions
1. Tested in Magento version: 2.1.4

### Steps to reproduce
1. Fresh install
2. Make following REST request: 

> POST /rest/default/V1/products/attributes/manufacturer/options

with following Body:
```
{
  "option": {
    "label": "Manufacturer 1"
  }
}
```

### Expected result
One of following:
1. The response Body should contain the ID of newly created option
2. The response Header should contain the ID of newly created option

The reason is that external systems will usually remember the ID so that it can be later referenced (for example when the external system needs to delete that option later).

### Actual result
1. The response body contains just following string:
`true`

**Comment by ericahoekerd** [comment]
Same results for SOAP API, returning option id is better than returning string value.

**Comment by RomanKrut** [comment]
@radosdesign Hi, thanks for your issue, internal ticket was created MAGETWO-70363

**Comment by magento-engcom-team** [comment]
@radosdesign, thank you for your report.
We've created internal ticket(s) MAGETWO-70363 to track progress on the issue.

**Comment by sanjay-wagento** [comment]
I am taking this issue. Please assign this ticket to me.

**Comment by poveu** [comment]
Any chance on fixing this on 2.2.6?

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @radosdesign thank you for you report, I'm closing this one, because  we have anothe here -> https://github.com/magento/magento2/issues/18392, and have a Created PR.
