### ISSUE TITLE
REST API salesRuleCouponRepositoryV1 not saving all parameters

### ISSUE THREAD

**Issue by giano574** [magento/magento2#8817]
### Preconditions

1. Magento 2.1.4

### Steps to reproduce

1. POST request to rest/V1/coupons with following JSON
```
{
  "coupon": {
    "rule_id":14,
    "code":"aaabbb",
    "usage_limit":10,
    "expiration_date":"2017-03-19",
    "type":"1"
  }
}
```

### Expected result

<pre>
{
  "coupon_id": 11,
  "rule_id": 14,
  "code": "aaabbb",
  <b>"usage_limit": 10</b>,
  "usage_per_customer": 0,
  "times_used": null,
  <b>"expiration_date": "2017-03-19"</b>,
  "is_primary": null,
  "type": 1
}
</pre>

### Actual result

<pre>
{
  "coupon_id": 11,
  "rule_id": 14,
  "code": "aaabbb",
  <b>"usage_limit": 2147483647</b>,
  "usage_per_customer": 0,
  "times_used": null,
  <b>"expiration_date": "2064-03-14"</b>,
  "is_primary": null,
  "type": 1
}
</pre>

The parameters marked in bold are set to the same as that of the rule (id: 14) by Magento.

**Comment by RomanKrut** [comment]
@giano574 Hi. Thanks for reporting this issue. But this issue isn`t a bug because a coupon gets these values from cart price rule and you cannot change them from admin page and from rest client also. But we was created new internal ticket  MAGETWO-70450 about Rest Client. Rest Client should give some error when you try to change these values.

**Comment by magento-engcom-team** [comment]
@giano574, thank you for your report.
We've created internal ticket(s) MAGETWO-70450 to track progress on the issue.

**Comment by RomaKis** [comment]
Seems like it is not a bug, but correct Magento behavior. Coupon code doesn't have expiration date or usage limit, it is data from Cart price rule. To change this data you can use API rest/V1/coupons and put here something like this:
```
{
  "rule": {
    "rule_id": 1,    
    "uses_per_coupon": 11,
    "uses_per_customer": 12,
    "to_date": "2017-12-19"
  }
}
```

**Comment by magento-engcom-team** [comment]
@giano574, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
