### ISSUE TITLE
Category Listing uses catalog search tables

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#883]
Is this a bug or a feature?  
I'm running the beta2 with sample data.  
If I clear the table `catalogsearch_fulltext` then I get no products while navigating through the top categories.  

After some digging I found that while viewing a category page, this gets executed `Magento\CatalogSearch\Model\Resource\Fulltext\Collection:_renderFiltersBefore` 

Also because of this method, when applying custom filters to the product collection (via custom code, not via layered nav) the filters are applied but the total number of records is wrong because of this line `$this->_totalRecords = count($ids) - 1;`. (This may be my fault, I may be doing it wrong, but still...why use catalogsearch collections in catalog).

**Comment by verklov** [comment]
MAGETWO-32550

**Comment by kokoc** [comment]
@tzyganu Good question.
This is expected behavior. Magento 2 actively uses search engine(s) in order to speed up category page rendering. Also there is a fallback to M1 rendering process for installations without `Search` module enabled.
So custom code has to take into account both cases: results provided by search engine and by regular MySQL queries.

**Comment by tzyganu** [comment]
@verklov @kokoc if this is the intended behavior and you don't plan to change anything regarding this,  then you can close the issue. Thanks for clearing it.
