### ISSUE TITLE
Pressing back on payment window returns empty cart and cookie erros

### ISSUE THREAD

**Issue by PGLDK** [magento/magento2#8843]
### Preconditions
1. Magento version 2.1.4
2. Bambora payment module.

### Steps to reproduce
1. Adding product to cart - going to checkout
2. Fill out checkout information
3. Placing order
4. Press back on payment window.

### Expected result
1. Going back to checkout or cart with items in cart.

### Actual result
1. Returning to a empty cart, if you add the product to cart again, nothing happens if you press "Go to checkout" button in the cart. The cart just reloads.
2. User has to clear cache or use different browser, then adding all the products to cart again, to be able to proceed to checkout.

**Comment by YevSent** [comment]
Hi, @PGLDK. Seems Bambora payment solution does not restore quote items. Magento does not provide support for 3d party modules, please, contact to Bambora support with this issue.

If this issue is reproducible with any Magento built-in payment solution like Braintree, PayPal, Authorize.net, etc., please, be free to re-open this ticket.

**Comment by bhupeshkushwaha** [comment]
# # #
