### ISSUE TITLE
Removal of JavaScript globals

### ISSUE THREAD

**Issue by szepeviktor** [magento/magento2#8856]
Good afternoon!

Are these 3 globals legacy code?
https://github.com/magento/magento2/blob/b1e56ed3b6f13f1ab780d8eddc33fc04cb6ecf75/app/code/Magento/Directory/view/adminhtml/templates/js/optional_zip_countries.phtml#L52-L54

Would it be possible not to use JS globals?
Thank you.

**Comment by orlangur** [comment]
Yeah, this seems pretty old, just look at `varienGlobalEvents` :) https://github.com/magento/magento2/blob/develop/lib/web/mage/adminhtml/events.js#L12

In the new JavaScript code global variables are not used by construction due to static tests: https://github.com/magento/magento2/blob/develop/lib/web/mage/adminhtml/events.js#L6

Removal some legacy globals in some random place does not seem to be a good idea to me, as it can cause bugs but do not introduce significant benefits. On the other hand, some global refactoring, like `varienGlobalEvents`/`varienEvents` mechanism removal, looks good to me.

The crux is that PrototypeJS is not removed from Admin UI yet. When this will happen, all such PrototypeJS-based implementations will rest in peace as well.

**Comment by szepeviktor** [comment]
Related https://github.com/magento/magento2/issues/1913

**Comment by szepeviktor** [comment]
Thank you.

> The crux is that PrototypeJS is not removed from Admin UI yet.

Do we have a todo list on how to remove it?

**Comment by orlangur** [comment]
I'm not even sure complete PrototypeJS removal is in current Magento roadmap. Such kind of changes perfectly fits into `'up for grabs'` form of collaboration as to me.

Let's wait for some Magento officials in this thread.

**Comment by danemacmillan** [comment]
Inline JavaScript and PrototypeJS are so densely woven into the framework. This is massive undertaking.

**Comment by orlangur** [comment]
Well, this is not an impossible mission. PrototypeJS was fully eliminated from storefront, for instance.

Step 1. Reveal PrototypeJS usage: Get rid of PrototypeJS usage in inline JavaScripts (ideally wrapping any JavaScript currently inline in RequireJS-loadable components).
Step 2. Refactor all JavaScript code to get rid of PrototypeJS: Having all usages clearly visible in `define` section (like here: https://github.com/magento/magento2/blob/develop/app/code/Magento/Authorizenet/view/adminhtml/web/js/direct-post.js#L11) refactor such isolated components one-by-one

The only thing which makes my sad after these is that implementations would be much cleaner with Angular 2 instead of jQuery+jQueryUI+KnockoutJS.

**Comment by pboisvert** [comment]
@tkacheva can you check with the front end team on this?

**Comment by aronesztergomi** [comment]
@orlangur Angular 2 is not really supports the multiple instances of root application, its only designed for SPA. React would be a better alternative for Magento2, but the plan is to replace jQuery+UI with KnockoutJS, or not?

**Comment by orlangur** [comment]
> its only designed for SPA.

Not true.

> multiple instances of root application

Not sure what do you mean. I'm not saying about having few root applications in different parts of page, I'm saying about one application initialized somewhere in the heart of `Magento_Ui`.

> React would be a better alternative for Magento2

Nope :) And they are not even comparable: React is a library, Angular 2 is a full-featured framework. You can even use React in some pieces of Angular 2 application, for example, when you use some charts based on React.

> but the plan is to replace jQuery+UI with KnockoutJS, or not?

Initial plan which I heard of was to not integrate any modern framework too deeply, no matter KnockoutJS or Angular. I'm not sure what is the current strategy, you can look into `Magento_Ui` library or fancy checkout-as-SPA to get some insight. If there is not too much jQuery+UI involved, the plan seems to get rid of them.

**Comment by aronesztergomi** [comment]
Sorry, true, Angular2 not ONLY designed for SPA. But Angular's has own thinking and solutions about everything, till React (and flux world) is much more flexible.

**Comment by ihor-sviziev** [comment]
Related part:
https://github.com/magento/magento2/blob/develop/app/code/Magento/Checkout/view/frontend/templates/onepage.phtml#L26

**Comment by orlangur** [comment]
> But Angular's has own thinking and solutions about everything, till React (and flux world) is much more flexible.

The more opinionated framework - the better for the project of Magento 2 scale ;) "flexibility" just creates burden. React can be easily integrated into Angular/EmberJS thus flexibility would not reduce.

For the sake of completeness, EmberJS would be a good choice for Magento 2 as well, but as to me it is not so laconic as Angular 2 and has a steeper learning curve.

**Comment by orlangur** [comment]
GitHub is intended for bug reports, please use [Community Forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) for other suggestions like improvements or feature requests.

**Comment by szepeviktor** [comment]
Thank you @orlangur 
Are there plans to reduce number of globals?

**Comment by orlangur** [comment]
Hi @szepeviktor, have no idea, generally I believe new code is written without new globals and old globals are refactored when it is possible taking into account backward compatibility constraints.

Not sure such refactoring is planned as a separate core team activity but such contributions from Community are always welcomed.
