### ISSUE TITLE
Export error causing "invalid option value" on import on configuarable Products 2.1.5

### ISSUE THREAD

**Issue by torchtrust** [magento/magento2#8867]
### Preconditions
Bitnami Magento Stack 2.1.5-0

### Steps to reproduce

1. Create Product Attributes that have a different value for the Admin and Store View
2. Create a product that is configurable
3. export Products
4. import Products

### Expected result
1.  import should complete without error

### Actual result
1. "invalid option value" on the configurable Product.

**Comment by torchtrust** [comment]
If I edit the 'configurable_variations' of the configurable Product to match the 'additional_attributes' of the virtual Product then the import will work

**Comment by AlexWorking** [comment]
Hello @torchtrust . An internal issue - MAGETWO-70368 has been created based on Your issue. You”ll be informed as the issue is fixed. Thank You for applying.

**Comment by rtroncoso** [comment]
I'm experiencing this same issue using a Magento 2.1.7 install. I found that in my case this was produced by the "Multiple Value separator" in the products import form, which was set by default as a comma instead of a pipe character ( **|** ).

Changing the text field to use a pipe instead of a comma as the separator fixed this issue for me. Will be gathering more information and try to reproduce the fix on a fresh install, if this is the case I'll go ahead and create a PR to change this default value in the products import form.

**Comment by magento-engcom-team** [comment]
@torchtrust, thank you for your report.
We've created internal ticket(s) MAGETWO-70368 to track progress on the issue.

**Comment by piotrekkaminski** [comment]
This issue was moved to magento-engcom/import-export-improvements#87
