### ISSUE TITLE
tinyMCE is disabled

### ISSUE THREAD

**Issue by rastin1** [magento/magento2#8874]
### Preconditions

1. Magento 2.1.5
2. PHP 7.0.16 and MySQL 5.1.17 all installed from Bitnami stack on Ubuntu 16.04,
Everything  was working fine for 2 weeks. Today tinyMCE disabled, I have tried every possible option at 
store>configuration>general>content Management>WYSIWYG options, but there is no difference. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by attheCube** [comment]
Got the same problem but I was able to delimit it:
The TinyMCE worked fine in Firefox 51, but since version 52 it does not.
Mozilla has raised their security rules in version 52. 
For me it looks like the TinyMCE-version integrated in Magento 2 (v3.4.7 / 2011-11-03) does not pass these rules.
TinyMCE 4 will be shown, but until now I don't have a fully working replacement.
As TinyMCE v3.7.4 still works on current Chrome, this will be a workaround for now. But it's time for the magento developers to replace this outdated TinyMCE version.

**Comment by rastin1** [comment]
Hi atteCube
Thanks for your response. I had reached to the same solution.
 I have been using FireFox 52, I tried enabling/disabling JS Bundling, it worked for a while but failed again,after few attempt didn't respond at all. 
Finally, I installed Chrome, the problem was solved. 
 I did not know the reason of failure, just used trial and error method to solve my problem.

**Comment by attheCube** [comment]
For now, this is a solution. But it's just a matter of time, when this TinyMCE-version won't work in Chrome either.
Even IE 11 and above won't work with this version. So I hope one of the next magento 2 releases will include an updated TinyMCE.

**Comment by rhoerr** [comment]
Experiencing this as well.

**Comment by korostii** [comment]
See also #7149 and #700

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-69234

**Comment by magento-engcom-team** [comment]
Hi @rastin1 
Looks like the fix for this issue is now delivered to `2.1.8` and onwards with the PR magento/magento2#9655. 
We are closing this ticket for now. Please reopen if problem persists.
Thank you.
