### ISSUE TITLE
Inconsistent ways of accessing the registry

### ISSUE THREAD

**Issue by SchumacherFM** [magento/magento2#890]
During some review I've found three different ways of reading and writing to the registry:

```
$this->_registry->register(self::REGISTRY_KEY_CURRENT_INTEGRATION, $integrationData);
```

```
$this->_coreRegistry->register('current_widget_instance', $widgetInstance);
```

```
$this->_objectManager->get('Magento\Framework\Registry')->register('current_category', $category);
```

Which one is the official way?

**Comment by antonkril** [comment]
Recommended way is to pass parameters to methods directly instead of using registry, but since registry is available the official way is #1.

#2 is the result of automated tool that used part of namespace to generate unique variable name. This option is fine too because It's totally OK to name variables referencing same services differently in different clients.

#3 is not recommended way because objectManager should not be referenced directly. I think this is the result of "quick" manual substitution of Mage::getSingleton

**Comment by EliasZ** [comment]
@antonkril 
>№3 is not recommended way because objectManager should not be referenced directly

Any argumentation? Is DI always preferred? When should the objectManager be used?

**Comment by antonkril** [comment]
Usage of objectManager as service locator leads to highly coupled code and hidden dependencies. Also ability to configure specific arguments for the client that uses OM directly is lost.

Object manager can be used only in composition root of application (Bootstrap) and for unserialization of entities with service dependencies.

**Comment by SchumacherFM** [comment]
Thank you anton that helped a lot!
