### ISSUE TITLE
Update.log increasing significantly, and not able to disable it

### ISSUE THREAD

**Issue by sennin32** [magento/magento2#8940]
### Preconditions

1. Magento 2.1.4

### Steps to reproduce

1. use cron job:
* * * * * /usr/local/php/bin/php /home/wwwroot/shopkey.doyustudio.com/bin/magento cron:run
* * * * * /usr/local/php/bin/php /home/wwwroot/shopkey.doyustudio.com/update/cron.php
* * * * * /usr/local/php/bin/php /home/wwwroot/shopkey.doyustudio.com/bin/magento setup:cron:run

### Expected result

1. Run cron job without and log

### Actual result

1. update.log is increasing significantly. and there's no option to disable log in admin panel.

**Comment by korostii** [comment]
This sounds a bit as a request for a feature\improvement. [Community Forums](https://community.magento.com/) are intended for processing those. The GitHub issue tracker is intended for technical issues only.

**Comment by magento-engcom-team** [comment]
@sennin32, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
