### ISSUE TITLE
Missing Section in STORES -> Configuration -> Design - Mag 2.1.5

### ISSUE THREAD

**Issue by andreasacca** [magento/magento2#8944]
### Preconditions

1. In Design Section is present only Search Engine Robots section
2. Magento 2.1.5 - Installed with DEVBOX Beta on Mac - Docker

### Steps to reproduce

1. Go to STORES->Configuration->Design

### Expected result

1. Should appear more sections

### Actual result

1. ![screen shot 2017-03-20 at 13 10 58](https://cloud.githubusercontent.com/assets/1486077/24101073/bffd25f4-0d6e-11e7-8787-5b585c97a6b0.png)

**Comment by BeeHealthLimited** [comment]
They have been moved to Content -> Design -> Configuration

**Comment by magento-engcom-team** [comment]
@andreasacca, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
