### ISSUE TITLE
You can't subscribe to newsletter if you already have an account

### ISSUE THREAD

**Issue by loomdecor** [magento/magento2#8952]
Currently, if a user already has an account they cannot use the footer to sign up for email.  This is a terrible user experience...nobody is going to go all the way into their account (or even KNOW to go there) to sign up for the newsletter.  People do it from the footer or from popups.
### Preconditions 
1. Any Magento version

### Steps to reproduce
1.  Create a new account and don't sign up for newsletter
2. Now use that same email to try to sign up for the newsletter

### Actual result
1. Observe that you receive an error message and you will not be subscribed to the newsletter when looking in the Newsletter Subscriber list in admin

### Expected result
1. User is signed up for the newsletter

I submitted this as a bug to Magento Enterprise support and was told this is "expected" behavior.  Regardless of whether it is "expected", this is a terrible experience.

**Comment by grafikchaos** [comment]
> I submitted this as a bug to Magento Enterprise support and was told this is "expected" behavior. Regardless of whether it is "expected", this is a terrible experience.


I agree. That is pretty bad. The error message should at least be helpful enough to explain why and what you should do to remedy the situation. Why can't it be handled by an observer that matches the subscriber to customer email address and link the two?

**Comment by adrian-martinez-interactiv4** [comment]
In the issue description, it's not mentioned if the user that already has an account **is logged in or not, when trying to subscribe himself from the footer or popups**. I think this may be the reason why Magento Enterprise support has said this is the "expected" behaviour. From my point of view, we could split use cases this way:
- **Not logged in customer, introducing a non-existing email**: As it is impossible to find out any information about who is entering the email, and there is no data related to introduced email, it's assumed email could belong to the person introducing the email, and there is no reason to reject subscription.
- **Logged in customer, introducing his own email**: This way, as customer is already identified and he is trying to subscribe himself, the action to take when subscribing from the footer or popup should be the same as he did it from his account.
- **Not logged in customer, introducing an existing email related with a customer account**: At this point, **the customer has already registered that email, and should have full control about his personal data, including his subscription status**. If I had an account registered, it would be weird if I unsubscribe myself from My Account (managing data that is only accessible and modifiable by myself), and then someone could change my subscription status only by introducing my email in the footer or a popup.

Aside of this, for a logged in customer, since he is able to subscribe himself to the newsletter, I think if it would be interesting to block logged in customers to subscribe in the footer and popups different emails than the registered one.

**Comment by magento-engcom-team** [comment]
@loomdecor, thank you for your report.
We've created internal ticket(s) MAGETWO-84869 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @loomdecor. Thank you for your report. 
The issue has been fixed in magento/magento2#19164 by @ravi-chandra3197 in 2.3-develop branch
Related commit(s):
 - [78b694fea14fc0cbbae04b4d98150e18ae007298](https://github.com/magento/magento2/commit/78b694fea14fc0cbbae04b4d98150e18ae007298)
 - [ebfffe494247b4f49d2fb127b7823999202c2b7a](https://github.com/magento/magento2/commit/ebfffe494247b4f49d2fb127b7823999202c2b7a)
 - [b8941a8e25e8759a6ca2d801e67a4d933c0b2e49](https://github.com/magento/magento2/commit/b8941a8e25e8759a6ca2d801e67a4d933c0b2e49)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @loomdecor. Thank you for your report. 
The issue has been fixed in magento/magento2#18912 by @ravi-chandra3197 in 2.2-develop branch
Related commit(s):
 - [b1fc4a7e8319906049069f16cf49c026363dd4c6](https://github.com/magento/magento2/commit/b1fc4a7e8319906049069f16cf49c026363dd4c6)

The fix will be available with the upcoming 2.2.8 release.
