### ISSUE TITLE
Update folder

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#8972]
When you check out Magento CE 2.1.5 via composer and upload to your own repository omitting all core M2 files, is the update folder supposed to be committed as well or omitted from your own repo?

Or are you just supposed to commit update/composer.json?

### Preconditions
1. Magento CE 2.1.5 installed via composer

### Steps to reproduce
1. Omit /update/ folder from git repository 

### Expected result
1. Update folder to be downloaded and installed the same version

### Actual result
1. Nothing gets installed.

**Comment by korostii** [comment]
The magento/updater is a separate application (it needed to be such in order to be able to change the files of the main application). Here is [some limited info about it in the devdocs](http://devdocs.magento.com/guides/v2.1/comp-mgr/updater/update-updater.html) (Including the instructions on how to re-create it)

**Comment by cscd98** [comment]
Thank you
