### ISSUE TITLE
opc-wrapper width calculated incorrectly when overriding blank or luma theme

### ISSUE THREAD

**Issue by rb124559** [magento/magento2#8995]
### Preconditions

1. Magento Enterprise 2.1 and Community 2.0
2.  PHP 7.0, MySQL 10.1.16 MariaDB

### Steps to reproduce

1. Create a new theme.
2. User Luma or BLank as the parent theme
3. Apply the theme to the website
4.  Login and checkout
5.  The checkout page is not displayed correctly.
6.  The "opc-wrapper's" width is 133.3% causing the cart summary to appear at the bottom.

### Expected result

1.   The checkout page should be rendered correctly

### Actual result

1. [Screenshot, logs]

![opc](https://cloud.githubusercontent.com/assets/26639812/24277377/143381bc-1013-11e7-99c5-9a99022e841d.png)

**Comment by neillrobson** [comment]
Digging further, I think the problem lies in the `checkout-wrapper__columns` variable. In Blank, the variable is set to 8 (yielding a width of 66%, which looks correct), but in Luma the variable is set to 16 (yielding the twice-as-large width of 133%). 

I can't figure out the motivation for doubling this variable, but maybe it will bring us one step closer to understanding the cause of the issue. For theme developers, the fix is straightforward enough (setting the variable in an extends file or overriding the width directly), but understanding _why_ this variable was set as such would be interesting even so.

**Comment by magento-engcom-team** [comment]
@rb124559, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by kovinet** [comment]
I have the same issue. In theme that extends Luna I have to set manually @checkout-wrapper__columns to 8, else checkout looks completely broken.

**Comment by mehdichaouch** [comment]
I got the same issue with a Magento 2.4.2, custom theme extending the Magento Luma.
Fix from @kovinet work well, but this is weird bug!
