### ISSUE TITLE
Modules are not reflecting from the the new module its just reflecting from the Luma theam.

### ISSUE THREAD

**Issue by ghost** [magento/magento2#8996]
I have created the new theme with folder structure as give in the document . I have setup the new theme in the admin panel also . 

![untitled](https://cloud.githubusercontent.com/assets/19926754/24283602/d8488e20-108c-11e7-9f39-a8428d400ee2.png) 

 The problem is new theme is coming in the front-end but once i copy the module like search from  vendor to the new theme but in the front-end still coming from the vendor .

![untitled](https://cloud.githubusercontent.com/assets/19926754/24283666/31def42e-108d-11e7-8b18-d01821edc58f.png)

How to over come this any help me in this plzz..

**Comment by Ctucker9233** [comment]
@gandhiselvarj Try clearing all static caches including your browser.

**Comment by korostii** [comment]
I'll try to explain the downvotes you've received: This is a bugtracker intended to track.. well, bugs. Question of sort "how do I implement this" might be better received on the http://magento.stackexchange.com/ or at the Community Forums. Some trivial questions may even be answered by reading the http://devdocs.magento.com/

In this case, my first guess is that you might've forgotten to select this theme in your store's design config. Have you tried that yet? And yeah, clear those caches, all of them.

To reiterate, please only post here if you're fairly sure the issue you're experiencing is due to a bug in Magento 2 CE itself and is not a simple misconfiguration. If that's the case, please attempt to provide enough information for the issue to get reproduced on a clean  installation, including your custom code (if possible).

**Comment by magento-engcom-team** [comment]
@gandhiselvarj, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
