### ISSUE TITLE
Fotorama removes alt and title tags from images

### ISSUE THREAD

**Issue by cizgidekiadam** [magento/magento2#9005]
### Preconditions

1. Magento 2.1.2

### Steps to reproduce

1. Just navigate a product page which is using fotorama (default gallery).
2. Working fine

### Expected result

1. Alt and title like attributes set correctly

### Actual result

1. Removed alt tag.

I think it is time to change Fotorama behind us. Because it is very important seo mistake.

**Comment by magento-engcom-team** [comment]
@rbostan, thank you for your report.
We've created internal ticket(s) MAGETWO-81555 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @jignesh26. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by jignesh26** [comment]
Hello @rbostan 
In the version 2.3 and 2.2.5, ALT tag is working as expected, and showing the alt information from saved with each image. 

Thank you for submitting issue. Let me know if you have more information in that. I have checked the issue with saving the product and adding the images with ALT and its coming to alt tag in product page.


Thank you.
