### ISSUE TITLE
i can't click any option in the dashboard

### ISSUE THREAD

**Issue by TheKingYeison** [magento/magento2#9009]
### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by TheKingYeison** [comment]
What i can do? I click but nothing happens

**Comment by Ctucker9233** [comment]
@TheKingYeison Try clearing all your caches including your browser. If this doesn't work, please provide more information.

**Comment by pluckrose** [comment]
I've also experienced this bug, latest CE 2.1.5. The initial admin user works fine but if I create anymore, no matter what role I give them, the side links in admin don't work. Icons are also missing https://i.imgur.com/hXR0WAN.png 

If I login as admin it's fine.

Console: https://i.imgur.com/gdvz0gv.png

**Comment by TheKingYeison** [comment]
@Ctucker9233  and @pluckrose  thank you very much , with your help i started to search and i found this video where show how i can fix this issue, from the minute 6:37.
https://www.youtube.com/watch?v=v-sghNY1_P4

**Comment by Ctucker9233** [comment]
@TheKingYeison You're welcome!

**Comment by pluckrose** [comment]
not sure how I helped but glad you got it working!

**Comment by srmobile** [comment]
I just went through this myself, latest version of Magento (Magento-CE-2.2.0-2017-09-26-07-35-18.tar.gz) this is an embarrassment. First I had to hack the admin session by adding an entry  in the database (admin/security/session_lifetime) because I couldn't even login now this.   I'm just wondering what my next problem is going to be. Thanks for posting that youtube video, what I dont understand is why this hasn't been fixed since March 27th? Fresh install of Centos 7, PHP 7.1.11,  10.1.28-MariaDB
