### ISSUE TITLE
Validation on required attributes when updating a product on the REST API doesn't check the attribute set of the product.

### ISSUE THREAD

**Issue by alexgmin** [magento/magento2#9059]
### Preconditions

1. Magento 2.1.2
2. PHP 5.6
3. MySQL 5.7

### Steps to reproduce

1. Create two attribute sets.
2. Create a required attribute 
3. Assign the attribute to the first attribute set, but not the second.
4. Create two products, one for each attribute set.
5. Try to update the product on the attribute set without the required attribute with the REST API without that attribute.

### Expected result

1. The product is updated and nothing complains about the required attribute, since is not required for the attribute set of the product.

### Actual result

1. Magento doesn't check the attribute set of the product when using the API, so it throws an exception complaining about the missing attribute.
`"message": "The value of attribute \"foo"\ must be set",`

The process works normally when doing it on the backend, but on the API, it doesn't check the attribute set of the product, only the the entity_type.

**Comment by RomanKrut** [comment]
@Alexgmin Hi, thank you for your feedback. Can you add more information with body of requests and examples?

**Comment by springerin** [comment]
Having the same issue on magento 2.1.7 ( with sample data). The problem is from
`vendor/magento/module-eav/Model/Entity/AbstractEntity.php:592
public function walkAttributes($partMethod, array $args = [], $collectExceptionMessages = null)` that loads also attributes that are not part of the attribute set and so if they are required but not part of the attribute set they still give the error in the validation process.

**Comment by magento-engcom-team** [comment]
@Alexgmin, thank you for your report.
We've created internal ticket(s) MAGETWO-78227 to track progress on the issue.

**Comment by robwaug** [comment]
Hi Magento Support Team, was the bug ever fixed? I reproduced this bug in 2.1.9 build.

**Comment by tomasfejfar** [comment]
We're experiencing this on 2.1.8, but we're reluctant to go through with the whole update pipeline unless we know that the bug is fixed. Has there been any development? Would failing test help?

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii, here is your [Magento instance](https://i-9059-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-9059-2-3-0.instances.magento-community.engineering/admin](https://i-9059-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
Hi @Alexgmin! Thank you for reporting this issue. We were not able to reproduce this issue on 2.3.0.
