### ISSUE TITLE
How to import category ?

### ISSUE THREAD

**Issue by ekumar1** [magento/magento2#9064]
### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. I try try to magento 2 there is i did not see import category 

### Actual result

1. [Screenshot, logs]

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions and support. Feel free to reopen this issue if you think you have encountered a bug in Magento 2, and make sure to provide complete detail on how to reproduce and what the issue is, etc. Thanks!
