### ISSUE TITLE
If stock is bellow OutOfStock Threshold, a negative qty is displayed in Product List Page

### ISSUE THREAD

**Issue by popoviciandrei** [magento/magento2#9130]
### Preconditions

1. Magento EE v2.1.4 or CE 2.1.5

### Steps to reproduce

1. Set qty to 5 for a product, and Out of Stock threshold to 10. Save the product
2. When browsing that product in the frontend a "Only -5 left" is displayed under "Out of Stock" message.

### Expected result

1.  the qty block should not be rendered with a negative value.

### Actual result

1. <img width="625" alt="screen shot 2017-04-04 at 15 43 19" src="https://cloud.githubusercontent.com/assets/3797668/24662614/7bc8bf98-194d-11e7-8823-ccfb5a581fe1.png">

**Comment by dmitriyprime** [comment]
Hello, @popoviciandrei . An internal ticked MAGETWO-70233 was created based on Your issue. You'll be informed as the issue is fixed. Thanks for applying.

**Comment by magento-engcom-team** [comment]
@popoviciandrei, thank you for your report.
We've created internal ticket(s) MAGETWO-70233 to track progress on the issue.

**Comment by raumatbel** [comment]
The message "Only -5 left" is the result of 10-5 (qty threshold - qty product). @magento-engcom-team what is the expected result here? Don't show that message or show other? Can you assign me please?

**Comment by sebashottesimplyphp** [comment]
What happen with this issue. Is it going to be fix on 2.3 ?

**Comment by magento-engcom-team** [comment]
Hi @popoviciandrei. Thank you for your report. 
The issue has been fixed in magento/magento2#19206 by @khodu in 2.3-develop branch
Related commit(s):
 - [cc6aaa3fc8b9a5d58f14c45655926809dfb1f00c](https://github.com/magento/magento2/commit/cc6aaa3fc8b9a5d58f14c45655926809dfb1f00c)
 - [3ba9281d52bd9f77fb778778c1f57b560d60b687](https://github.com/magento/magento2/commit/3ba9281d52bd9f77fb778778c1f57b560d60b687)
 - [dd965b94a00480e71683aa67f14c87da2943e083](https://github.com/magento/magento2/commit/dd965b94a00480e71683aa67f14c87da2943e083)
 - [303698fbcaf7c6fcd519e1d92014cf567a2f310b](https://github.com/magento/magento2/commit/303698fbcaf7c6fcd519e1d92014cf567a2f310b)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @popoviciandrei. Thank you for your report. 
The issue has been fixed in magento/magento2#20206 by @saphaljha in 2.2-develop branch
Related commit(s):
 - [2b88353cf0cd24da027d90f55c2e1c86e88033b7](https://github.com/magento/magento2/commit/2b88353cf0cd24da027d90f55c2e1c86e88033b7)
 - [304e7e8dfbe3676769b42c6cf90755dadf00830b](https://github.com/magento/magento2/commit/304e7e8dfbe3676769b42c6cf90755dadf00830b)

The fix will be available with the upcoming 2.2.8 release.
