### ISSUE TITLE
REST API - invalid delete request for image returns true

### ISSUE THREAD

**Issue by ghost** [magento/magento2#9136]
### Preconditions
- linux 
- php7 
- nginx

### Steps to reproduce
1. create product
2. add images in multiple store views
3. delete image

### Expected result
1. images deleted

### Actual result
1. No error response, just a bool "true". image type got removed, image still there.

This might be because the image is on multiple store views yet the scope is global of the media gallery types.

**Comment by george-vlahakis** [comment]
I see the same issue. Even using Swagger to call the DELETE method for a product image the response is true but doing another GET on the product SKU on media returns the image again.

Tried with default and well as store id but the image is not deleted!

Im on Apache, Ubuntu and Magento 2.1.6

Need a way to delete an image from the media gallery of a product and ideally also delete the image file on the disk with associated cached images.

First:
> curl -X DELETE --header "Accept: application/json" --header "Authorization: Bearer **[code here]**" "http://**[domain]**/rest/default/V1/products/**[SKU]**/media/**[entry id]**"

Then:
> curl -X GET --header "Accept: application/json" --header "Authorization: Bearer **[code here]**" "http://**[domain]**/rest/default/V1/products/**[SKU]**/media"

returns the deleted image.

**Comment by george-vlahakis** [comment]
From the little I have looked into this, it seems that this call (DELETE) only disassociates the media gallery entry types for this product but does not effect the media entry itself and neither does it remove the product association.

I have found no other exposed REST API to actually delete the media entries and remove it from a product completely. I will try to find out how it does it on Admin site.

**Comment by george-vlahakis** [comment]
Further feedback seems to suggest that images are related to products on all store ids meaning one needs to delete them for each store id so that a reference is removed completely.

I am not 100% if this is due to my own testing code, but somehow images for products where also associated to products on store id 0 (Admin) which is a dead lock situation given you cant remove them from there (so I don't know how they got there in the first place).

Clearing my Magento instance completely and starting from scratch as way too much bloat has gathered up.

**Comment by magento-engcom-team** [comment]
@SinisterGlitch, thank you for your report.
We've created internal ticket(s) MAGETWO-82045 to track progress on the issue.

**Comment by kolonuk** [comment]
Year and a half later, still not working in a main release...  Still in 2.2.5...

**Comment by kolonuk** [comment]
@kolonuk - monitor in my issues

**Comment by Ctucker9233** [comment]
@magento-engcom-team Can we expect any progress on this issue soon?

**Comment by sly8787** [comment]
@magento-engcom-team What's the status here?

**Comment by magento-engcom-team** [comment]
Hi @SinisterGlitch. 

Thank you for your report and collaboration!

The related internal Jira ticket `MAGETWO-82045` was closed as `non-reproducible` in `2.3.x`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Comment by altdovydas** [comment]
You can't delete image if any of other store scope (your scope all is 0 store) use it as 'small_image', 'thumbnail' or 'image'.
