### ISSUE TITLE
webapi admin authentication

### ISSUE THREAD

**Issue by jaykobi** [magento/magento2#9138]
### Preconditions
magento 2.4-develop

The devdocs clearly state that authenticated admin users can access the rest api.

http://devdocs.magento.com/guides/v2.0/get-started/authentication/gs-authentication.html

> Resources for which administrators or integrators are authorized. For example, if administrators are authorized for the Magento_Customer::group resource, they can make a GET /V1/customerGroups/:id call.

But this does not work. 

### Steps to reproduce
1.  Install magento 2.1.5 from composer archive
2. Log into you new admin account
3. Open domain.com/rest/V1/customers/1 in the same browser in a new tab.

### Expected result
A response saying that this customer does not exist.

### Actual result
A response saying me I have no acccess rights.

`<response>
   <message>Consumer is not authorized to access %resources</message>
    <parameters>
      <resources>Magento_Customer::customer</resources>
    </parameters>
</response>`

**Comment by amansrivastava** [comment]
You need to provide header value to call rest API.
Try this on Postman or other tool with header value and it will work for you.

**Comment by jaykobi** [comment]
Header value in the form of an Integration (Bearer XXXX, which is what I already can do) or header value in  the form of an admin user authentication?
I need information about the current logged in user in the api.

**Comment by jaykobi** [comment]
Ok, I see, It simply does not wotk like this. I need to use a token.

**Comment by jaykobi** [comment]
No, wait. It should be possible to just use the admin session. It is also clearly stated on the link I posted above

> JavaScript widget on the Magento storefront or Magento Admin :
>Registered users use session-based authentication to log in to the Magento storefront or Magento Admin.

**Comment by amansrivastava** [comment]
Customers can access resources that are configured with `anonymous` or `self` permission in the webapi.xml configuration file.

Admins can access resources that are assigned to their Magento Admin profile.

Try `{domain.com}/rest/V1/customers/me` after login to your magento portal.

**Comment by jaykobi** [comment]
> Admins can access resources that are assigned to their Magento Admin profile.

This is exactly what I say does not work. In the example above, in a freshly installed magento 2.1.5 the admin user created on install with role "Administrators" ist not allowed to access {domain.com}/rest/V1/customers/1.

Can you please verify in your installation that you can 
1. Log into magento as admin user with role "Administrators"
2. Access rest api resources in another tab, session based

**Comment by rafaelstz** [comment]
@skymeissner I guess that these samples will help you:
https://gist.github.com/rafaelstz/ecab668b80fece4d9acdb9c5358b3173

**Comment by DrewKolstad** [comment]
@skymeissner, were you ever able to figure this out?

I am having the same issues. I also see where the documentation clearly indicates that session-based authentication works to access admin resources.

**Comment by jaykobi** [comment]
Hi @DrewK289 ,

I did not get this to work, and I don't think it's possible at the moment. I switched to token based authentication, which works fine but I don't have info about logged-in admin user.

**Comment by magento-engcom-team** [comment]
@skymeissner, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by magento-engcom-team** [comment]
Please, look http://devdocs.magento.com/guides/v2.2/get-started/authentication/gs-authentication.html "Web API clients and authentication methods" - here you can see allowed authentication methods.

**Comment by jaykobi** [comment]
@magento-engcom-team 
The behaviour is clearly stated otherwise in the documentation. In the link you posted above it reads "Each administrator or integration user can have a unique set of permissions which is configured in the Magento Admin." and "Administrator or Integration | Resources for which administrators or integrators are authorized."

![adminorinteg](https://user-images.githubusercontent.com/7371456/31498281-d2427ba2-af61-11e7-9a22-8bf2a202c311.JPG)

What refers "Administrator" to if not to a logged in admin user?

**Comment by davidwindell** [comment]
We've just hit this issue too.

**Comment by ghost** [comment]
I debugged with xdebug, and found that the user context is null and chosen user context gets set to guest instead of admin. In AdminSessionUserContext $this->_adminSession->hasUser() returns null on a request although logged in.

.../module-authorization/Model/CompositeUserContext.php
```
    protected function getUserContext()
    {
        if ($this->chosenUserContext === null) {
            /** @var UserContextInterface $userContext */
            foreach ($this->userContexts as $userContext) {
                if ($userContext->getUserType() && $userContext->getUserId() !== null) {
                    $this->chosenUserContext = $userContext;
                    break;
                }
            }
            if ($this->chosenUserContext === null) {
                $this->chosenUserContext = false;
            }
        }
        return $this->chosenUserContext;
    }
```

.../module-user/Model/Authorization/AdminSessionUserContext.php

```
    public function getUserId()
    {
        return $this->_adminSession->hasUser() ? (int)$this->_adminSession->getUser()->getId() : null;
    }
```

**Comment by ghost** [comment]
@skymeissner @davidwindell Did you find any solution/workaround?

**Comment by ghost** [comment]
Debugging further it seems like it has to do with duplicate cookies; the "PHPSESSID" cookie is used for the REST API but the "admin" cookie is used for admin. So authentication fails because the REST request reads from the wrong (PHPSESSID) session.

**Comment by maniramav** [comment]
I have **exact copy of magento 2** running on two different server.
### Server 1:
Able to receive data correctly as I requested.
![otherserver](https://user-images.githubusercontent.com/11077689/40167004-d0531b84-59b7-11e8-8f15-c3f166615556.JPG)

### Server 2:
I am getting error as:
`"message": "Consumer is not authorized to access %resources","parameters": {"resources": "Magento_Customer::customer"}`
![simpleserver](https://user-images.githubusercontent.com/11077689/40167026-de4eacee-59b7-11e8-95f0-57e3b719e1af.JPG)

**Comment by WesleyVestjens** [comment]
@magento-engcom-team 

Could someone from Magento let me know what their intentions with this issue are? I'm willing to take this one on as a community issue, however I am not 100% certain what a good fix would be.

Looking at the issue, the admin authorization is required in order to use any of the API's. Doing this from the `/rest/*` endpoint would, I think, never work, because the admin cookie is not available there.

My personal suggestion would be to create a new REST endpoint at `/<admin-url>/rest/*`which accepts the admin session as authorization, then forwards this to the default REST endpoint.

If someone from Magento could confirm to me that this would be a proper fix, I'll start on drafting a PR for this change.

**Comment by WesleyVestjens** [comment]
> @magento-engcom-team
> 
> Could someone from Magento let me know what their intentions with this issue are? I'm willing to take this one on as a community issue, however I am not 100% certain what a good fix would be.
> 
> Looking at the issue, the admin authorization is required in order to use any of the API's. Doing this from the `/rest/*` endpoint would, I think, never work, because the admin cookie is not available there.
> 
> My personal suggestion would be to create a new REST endpoint at `/<admin-url>/rest/*`which accepts the admin session as authorization, then forwards this to the default REST endpoint.
> 
> If someone from Magento could confirm to me that this would be a proper fix, I'll start on drafting a PR for this change.

I've been looking at `Magento/Backend` and `Magento/Webapi` and I'm not sure if the fix I've suggested here is possible at all, a few things I am not sure about on how to handle them are:

- Magento/Webapi handles REST requests by adding an area and a controller for handling the API requests, which is not possible from inside the admin area
- The admin features the secret key, which I do not think is compatible with making REST requests, due to this conflicting with the REST path

Will wait on @magento-engcom-team (or perhaps any other community member) to let me know what a possible vector to tackle this issue will be.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30220` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
The documentation related to this issue has been updated in https://github.com/magento/devdocs/pull/7393
It seems we can close this old report.
But if a problem still exists, please create new report with an updated description and links related to 2.4
