### ISSUE TITLE
Adding product from wishlist not adding to cart showing warning message.

### ISSUE THREAD

**Issue by KishorkumarKar** [magento/magento2#9155]
### Preconditions
Hi,
I have add a product from admin In **Magento 2 (ver. 2.1.5)**  with  Minimum Qty Allowed in Shopping Cart **(10)** .After that iI add that product to wishlist and i tried to add that product by 1 Qty it redirect to product detail page from there I wanted to add qty 10 to cart **No product added to cart**.

### Steps to reproduce

1. add a simple product from admin with Minimum Qty Allowed in Shopping Cart 10
2. login in front end
3. Add product to wishlist
4.Click on wishlist
5.Try to add product with qty 1 it will redirect to product detail page
6.try to add product with 10 qty in the same page.
 

### Expected result

1.while clicking to wishlist it should show qty 10 as a default in qty but showing 1

![image](https://cloud.githubusercontent.com/assets/24475017/24755503/2477dd08-1af8-11e7-9b85-df169548e0d0.png)

2.after redirecting to order detail page fro giving wrong minimum qty.It should add the product to car while giving qty 10 in the same page .
![image](https://cloud.githubusercontent.com/assets/24475017/24755730/e80226f2-1af8-11e7-9b6d-dc1032dae58d.png)

### Actual result
1.It is not showing wrong qty in wishlist
![image](https://cloud.githubusercontent.com/assets/24475017/24755503/2477dd08-1af8-11e7-9b85-df169548e0d0.png)

2.product not added to car giving an warning message  .
![image](https://cloud.githubusercontent.com/assets/24475017/24755730/e80226f2-1af8-11e7-9b6d-dc1032dae58d.png)

**Comment by routbiplab** [comment]
I am also facing the same issue while adding products to cart from wishlist. Please help!

**Comment by IlnitskiyArtem** [comment]
@KishorkumarKar, , Thanks for reporting this issue.
Created internal issue MAGETWO-70236 to investigate and track this issue.

**Comment by magento-engcom-team** [comment]
@KishorkumarKar, thank you for your report.
We've created internal ticket(s) MAGETWO-70236 to track progress on the issue.

**Comment by ibrahimbm** [comment]
Can any one help me? My website is Live and i am facing this issue.. how soon can this be resolved?

**Comment by PedroBlascoInteractiv4** [comment]
The qty param is send for post and in querystring. Can you assign me this issues

**Comment by vrann** [comment]
#mm17es

**Comment by magento-engcom-team** [comment]
Hi @KishorkumarKar. Thank you for your report. 
The issue has been fixed in magento/magento2#19653 by @khodu in 2.3-develop branch
Related commit(s):
 - [e2712f66dee7e4e11898a7cd31568496c9c37949](https://github.com/magento/magento2/commit/e2712f66dee7e4e11898a7cd31568496c9c37949)
 - [dec124e58dfaa5b6308b69779abd30fc7b2ef52a](https://github.com/magento/magento2/commit/dec124e58dfaa5b6308b69779abd30fc7b2ef52a)
 - [9e339a0e434408a309a94175009b8a0e6ee83fee](https://github.com/magento/magento2/commit/9e339a0e434408a309a94175009b8a0e6ee83fee)
 - [334d71368b2d7ad8b060051b7009c730825f9c4f](https://github.com/magento/magento2/commit/334d71368b2d7ad8b060051b7009c730825f9c4f)
 - [5c0525c504b3c0cf056f25d648920ab0a5e1e202](https://github.com/magento/magento2/commit/5c0525c504b3c0cf056f25d648920ab0a5e1e202)
 - [73859cd565ddf112ba003953efb523688acdfea2](https://github.com/magento/magento2/commit/73859cd565ddf112ba003953efb523688acdfea2)
 - [d30dc93b9d85480b88fc76a50b0bda90de224aa0](https://github.com/magento/magento2/commit/d30dc93b9d85480b88fc76a50b0bda90de224aa0)
 - [661817f03fa1cb34c5ad0e712d12a460a334963c](https://github.com/magento/magento2/commit/661817f03fa1cb34c5ad0e712d12a460a334963c)
 - [c90d75ed9e34445a78ecc651c79d8bb99f455199](https://github.com/magento/magento2/commit/c90d75ed9e34445a78ecc651c79d8bb99f455199)

The fix will be available with the upcoming 2.3.2 release.

**Comment by magento-engcom-team** [comment]
Hi @KishorkumarKar. Thank you for your report. 
The issue has been fixed in magento/magento2#22536 by @niravkrish in 2.2-develop branch
Related commit(s):
 - [c62ab93a45ef9f4dc6fb86d6cd03de127a9665a6](https://github.com/magento/magento2/commit/c62ab93a45ef9f4dc6fb86d6cd03de127a9665a6)
 - [44027144a61657e0dd6acf41777c17bad6ad4e54](https://github.com/magento/magento2/commit/44027144a61657e0dd6acf41777c17bad6ad4e54)

The fix will be available with the upcoming 2.2.9 release.
