### ISSUE TITLE
crontab not covered by a specific di.xml area

### ISSUE THREAD

**Issue by maderlock** [magento/magento2#9178]
### Preconditions

1. Magento 2.1.5
2. A module that provides DI coverage by setting a preference for a model in frontend/di.xml and admin/di.zml

### Steps to reproduce

1. Make use of model in a cron job

### Expected result

1. Either frontend or adminhtml version of the preference would be used

### Actual result

1. Neither is used, so the default model is used

I tried to use a crontab/di.xml but this was ignored. Also, if I tried to change the area to adminhtml this caused an error.

The answer may be that we need to tell the extension provider to use the default di.xml, but it would be good to have this cleared up as I was under the impression that each area had its own di.xml.

**Comment by maderlock** [comment]
Similarly, what do you do about events that you want to fire for adminhtml and crontab but not frontend? You could make a non-area events.xml but this would fire off for the frontend. So... create area specific events.xml for adminhtml and crontab? Oh, but crontab isn't a real area!

**Comment by magento-engcom-team** [comment]
@maderlock, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
