### ISSUE TITLE
Magento 2.1.4 - Can't Call Related Products in Static Block

### ISSUE THREAD

**Issue by Ctucker9233** [magento/magento2#9180]
### Preconditions
1. Magento 2.1.4
2. Custom Tab on Product View Page

### Steps to reproduce
1. Create a custom tab on the Product View Page
2. Create a static block to display content in that tab
3. Call related products with code {{block class="Magento\Catalog\Block\Product\ProductList\Related" name="catalog.product.related" template="Magento_Catalog::product/list/items.phtml"}}

### Expected result
1. Expected related products to be displayed

### Actual result

1. Error filtering template: Notice: Undefined variable: exist in /home/user/public_html/app/design/frontend/Mgs/cashcarry/Magento_Catalog/templates/product/list/items.phtml on line 157

**Comment by korostii** [comment]
Looking at the error you provided, it seems that you're using a custom frontend theme. 
Could you pleas double-check whether the error persists if you use the Luma theme provided with Magento out of the box? If it doesn't, the error is likely to be caused by this theme and I'd advise you to contact the provider of this 3rd-party code you're using.

**Comment by Ctucker9233** [comment]
@korostii Same error with Luma
Error filtering template: Notice: Undefined variable: exist in /home/user/public_html/vendor/magento/module-catalog/view/frontend/templates/product/list/items.phtml on line 154

**Comment by korostii** [comment]
Ah, right, you're not passing the "type" argument into the block, that's why the $type argument doesn't get populated by the switch inside the template.
Please try changing your code to `{{block class="Magento\Catalog\Block\Product\ProductList\Related" name="catalog.product.related" type="related" template="Magento_Catalog::product/list/items.phtml"}}`
If that fails, you will probably need to edit either the class or the template used. I don't think it can be called a bug though, looks like this block just wasn't supposed to be used as a widget.

If you are looking for some additional help or an advice regarding development or customization please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/). 
The GitHub issue tracker is intended for tracking technical issues (read: "bugs") only.
The issues which cannot be consistently reproduced on a clean installation of Magento 2 CE installed on a sufficient server environment aren't likely to get resolved in here.

**Comment by Ctucker9233** [comment]
@korostii Thanks for the help. Indeed, this is not a bug and I will close it. Perhaps at a future date, I will suggest this on the forums as an "improvement".
