### ISSUE TITLE
Products ordered report doesn't show simple (child) products of configurable products

### ISSUE THREAD

**Issue by NMills12** [magento/magento2#9196]
When I run the "Products Ordered" report in Magento 2, configurable products show up as a single product, where the sales of all its child products were summed up. Is there a way to change this so that only the child (simple) products are shown in the report with their sold quantities?

We are currently using version 2.0.7 community edition.

Steps to reproduce

Run products sold report

I should see how many of each simple product were sold

Actual result

Sales do not show for simple products that are ordered under a configurable product. The report only gives a summed up total of all the configurable products falling under it (example: if I sell chocolate bunnies in milk, dark and ivory I don't see sales for each of those chocolate types; I only see a total for all chocolate bunnies sold).

**Comment by vinoth-dckap** [comment]
I am working on this issue

**Comment by NMills12** [comment]
That is great news. Looking forward to this update/fix!

Nakia M. Mills
Sanders Candy
ph: 586-464-5368
SandersCandy.com<http://www.sanderscandy.com/> I Facebook<http://www.facebook.com/SandersCandy> I Twitter<http://twitter.com/#!/SandersCandy> I YouTube<http://www.youtube.com/user/Tvanhemm>
View 2017 Online Retail Catalog<https://view.publitas.com/sanders-morley-candy-makers/sanders-2017-retail-catalog/>

**Comment by vkranjith** [comment]
I am working on it.

**Comment by NMills12** [comment]
Thank you for working on this. It will be a much more useful report once the simple products are shown.

Nakia M. Mills
Sanders Candy
ph: 586-464-5368
SandersCandy.com<http://www.sanderscandy.com/> I Facebook<http://www.facebook.com/SandersCandy> I Twitter<http://twitter.com/#!/SandersCandy> I YouTube<http://www.youtube.com/user/Tvanhemm>
View 2017 Online Retail Catalog<https://view.publitas.com/sanders-morley-candy-makers/sanders-2017-retail-catalog/>

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-69913

**Comment by NMills12** [comment]
Just to be clear, does the above status change to "Done" mean this report is now updated? If so, how can I begin using this updated version of the report? Thank you.

**Comment by magento-engcom-team** [comment]
@NMills12 thank you for your report.
The fix for this issue is already available in release 2.2.0

**Comment by harout-itology** [comment]
The best solution is to create an extension for this functionality or just use mine

[https://github.com/harout-itology/Simpleproductsreport](url)

**Comment by robocrax** [comment]
Hi,

It appears this is still not resolved. I'm on version 2.3.4 and I'm only getting 1 child product (single entry) per configurable product rather than all child products (multiple entries)

**Comment by Jakub-Czech** [comment]
This issue is not solved, also on version 2.3.6.
Even if we can see from the ordered items report the SKU of the simple product it is actually wrong.
In `Magento\Reports\Model\ResourceModel\Product\Sold\Collection::addOrderedQty` in line 79 there is  following where condition: `order_items.parent_item_id IS NULL` 
order_items is actually sales_order_item table and there is problem.
In this table there are items that are assigned to orders that were placed.
If there was only one item ordered in the sales_order_item it will be saved correctly with:
- correct product_sku 
- `product_type=simple` 
- however `parent_item_id=null`
So the condition above for the 'sold reports' will work. 

This works different when order has more items. In the sales_order_item table are being saved items of type simple, but also configurable, so there are two records for each ordered item:
- CONFIGURABLE:  `product_type=configurable` , `parent_item_id=null` , `product_sku=<value of sku for the simple product>`
- SIMPLE: `product_type=simple` , `parent_item_id=<item id of configurable item>` , `product_sku=<value of sku for the simple product>`

SQL for the ordered items report is actually selecting order items of type configurable. When the order has more simple items of the same parent (configurable) it will select first configurable item (with wrong sku fo the simple product). 
In example: 
Ordered items: T-shirt (configurable), blue-t-shirt (simple), green-t-shirt (simple).
In sales_order_item will be:
- blue-t-shirt
- t-shirt (with sku of blue t-shirt)
- green-t-shirt
- t-shirt (with sku of green t-shirt)
In report grid and generated report's csv will be:
-blue-t-shirt x2

So we cannot rely on such WHERE condition (`order_items.parent_item_id IS NULL`), because it will simply select configurable items which wasnt really ordered, because you cannot order configurable product.


For those who are still looking for solution:
I changed where condition from `order_items.parent_item_id IS NULL` to `order_items.product_type='simple'`
