### ISSUE TITLE
Gallery fullscreen image just black after upgrading to 2.1.6

### ISSUE THREAD

**Issue by v0gler** [magento/magento2#9220]
### Preconditions

1. Magento Version 2.1.5

### Steps to reproduce

1. Update to Version 2.1.6
2. Clean all caches

### Expected result

1. Open fullscreen in gallery shows fullscreen image and thumbnails below

### Actual result

1. Fullscreen image just black. Thumnails are shown as intended
![magentofullscreen](https://cloud.githubusercontent.com/assets/25635896/24957973/fc6e513a-1f8d-11e7-893b-3d2933ac9c80.png)

**Comment by jordanbrauer** [comment]
I am not having this exact problem, however after upgrading from `CE 2.1.4` to `CE 2.1.6` I do experience a problem with product images.

My problem is that the front-end catalog is missing thumbnail images (404s), but will load images sort of alright on the actual product page itself (seems to be a resizing problem with thumbnails). The only fix to the 404 missing images that I can find is by running the new `catalog:images:resize` command - however this is fairly unacceptable as it takes a very very long time for any store with ~1,000+ products (I had to leave mine run over night for local dev alone...). 

__Catalog Page (404s):__
![image](https://cloud.githubusercontent.com/assets/18744334/25013238/819c1112-2038-11e7-9bab-f8deabea4ba9.png)

The 404 errors in my console (screen shot below) on the catalog page seem to indicate that there is a caching and image path problem as no amount of static asset deployment, database upgrading, manual clearing of generated content and caches does anything at all.

![image](https://cloud.githubusercontent.com/assets/18744334/25013650/145bbb1e-203a-11e7-887f-60d9573bb494.png)

__Product Page (Not resizing properly for thumbnails):__
![image](https://cloud.githubusercontent.com/assets/18744334/25013352/dd5f2cdc-2038-11e7-9bae-50a5541eafb4.png)

It seems that the upgrade to `2.1.6` causes image problems in general.

**Comment by Tonop** [comment]
Have similar problem with 2.1.6.
Catalogue product images referred to empty product/cache folder and as result we have no images. But on product page all images are correct.
How to fix?

**Comment by jordanbrauer** [comment]
@Tonop the only fix I have come across is to run the `catalog:images:resize` command and it will work afterwards - however as I mentioned above, that is not really feasible if you have more than 1,000 products (even 700+ takes a long time). Although maybe it is more feasible if your images aren't high-res.

To make matters worse, if you run this locally and deploy your application from local to staging/production, you will have to repeat this process.

**Comment by joebusby** [comment]
I have the same problem and had to restore 2.1.5

@jordanbrauer    Does catalog:images:resize fix both problems?  404's and image sizes?    I'm not sure I want the site to go down for a day and irritate customers.   (2500 products)

**Comment by jordanbrauer** [comment]
@joebusby It fixes the 404s for me, I am not sure about the full screen image issue though. You could run it over night perhaps? If it's any help too, I was able to browse the store in local dev just fine while the command was running, so you may not have to go down - just run at a very low traffic time.

__More on why it works and why I thought to try running this command:__
After upgrading to `CE 2.1.6` and having the images 404 with no amount of cache clearing working, I re-read the release notes and noticed they made some changes to the image resizing and caching. I clicked on the link to `catalog:images:resize` and scrolled the bottom to read [these reasons "where this could be necessary"](http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/themes/theme-images.html#resize-catalog-images). It mentions one of the reasons being manually deleting the image cache, which seems to be the problem with the images 404ing because their paths are stuck on old caches from before the upgrade.

So to make sure that my hunch was right, I moved my `pub/media/catalog/product/cache` directory to `pub/media/catalog/product/cache.bak` and then ran the `catalog:images:resize` command. I then started to see a new `cache/` directory begin to generate itself that slowly started to satisfy all the 404 images as I would refresh the front-end catalog.

I am not sure _exactly_ what is going on here, but there is definitely something being messed up with the images during the upgrade to `2.1.6`.

**Comment by joebusby** [comment]
@jordanbrauer   Thanks for that, I may give it a try.  If I upgrade the live site and orders come in during the "resize",  there is no going back to 2.1.5, so maybe I will block access  and run it at night.  I'm getting skittish with the upgrades.

@SirElectro   did this solve the problem for you?

**Comment by v0gler** [comment]
@joebusby Found out that my issue was a template issue. 

But in 2.1.6 i have the same thumbnail image size issue. It instant appears after upgrading from 2.1.5 
The resize image command doesn't help. This error is no template issue. Problem is on Magento Luma, too. 
So i had to downgrade to 2.1.5 again.

**Comment by jordanbrauer** [comment]
@SirElectro @joebusby This has been fixed by upgrading to `2.1.7`!

**Comment by magento-engcom-team** [comment]
@SirElectro, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
