### ISSUE TITLE
Upgrade ZF components. Zend_Feed

### ISSUE THREAD

**Issue by okorshenko** [magento/magento2#9240]
**Description**
Upgrade components from ZF1 to ZF2

As a long term goal, we would like to eliminate knowledge about 3rd party libraries from Magento code base. Magento code still can use 3rd party libraries, but they must be wrapped by Magento interfaces and classes (adapters) so that 3rd party libraries can be easily substituted by newest versions or alternative implementations.

**Acceptance Criteria**

1. Magento interfaces are defined and can be used instead of ZF1 classes in Magento code
2. Default implementations for new interfaces are defined and configured as the preferences for new interfaces
3. Client code of the ZF1 components is refactored to use Magento interfaces
4. Zend classes are used as private services in Magento adapters
5. Backward compatibility is preserved
6. ZF1 components are updated to ZF2

**List of the components**

\# | Component Name <br/> (total usages count) | Module Name | Usages Count
------------- | ------------- | ------------- | -------------
1|Zend_Feed (total: 3)|Magento\Rss|3

**Comment by ldusan84** [comment]
I would like to take this one for start please.

**Comment by peterjaap** [comment]
@okorshenko I'm looking to pick this issue up, but I'm struggling with point 5 of BC. What do you mean with BC in this regard? If we swap out the hardcoded Zend_Feed in `app/code/Magento/Rss/Model/Rss.php` with an adapter, it'll break BC in some cases.

**Comment by korosti2** [comment]
@okorshenko Thank you for report
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.

**Comment by ldusan84** [comment]
@okobchenko @korosti2 @peterjaap I find it very hard to understand what's happening here, as the pull request is waiting: https://github.com/magento/magento2/pull/9347

**Comment by magento-engcom-team** [comment]
Closing the issue. See PR details here: https://github.com/magento/magento2/pull/9347

**Comment by magento-engcom-team** [comment]
Hi @okorshenko. Thank you for your report. 
The issue has been fixed in magento/magento2#9347 by @ldusan84 in 2.3-develop branch
Related commit(s):
 - [ca9e58264092cc56b993f65789e162612a7d5c9e](https://github.com/magento/magento2/commit/ca9e58264092cc56b993f65789e162612a7d5c9e)
 - [ed33b18dccffd27391501733961b73050b1e16ab](https://github.com/magento/magento2/commit/ed33b18dccffd27391501733961b73050b1e16ab)
 - [c7ba65a1caeabbbde4a32fa57938811255f34715](https://github.com/magento/magento2/commit/c7ba65a1caeabbbde4a32fa57938811255f34715)
 - [9d0a290457df41971334906108e976b55c003651](https://github.com/magento/magento2/commit/9d0a290457df41971334906108e976b55c003651)
 - [109047fa18803a3922b0572a0aa21e6b14e9a9de](https://github.com/magento/magento2/commit/109047fa18803a3922b0572a0aa21e6b14e9a9de)
 - [4534a2e41f487352b2413d94ab825f2414eba7a7](https://github.com/magento/magento2/commit/4534a2e41f487352b2413d94ab825f2414eba7a7)
 - [c413389ffe73799d8faebbece88208c39cdf0f5c](https://github.com/magento/magento2/commit/c413389ffe73799d8faebbece88208c39cdf0f5c)
 - [caa4471aede4e4415fe4abb629f28c8e0ef6d954](https://github.com/magento/magento2/commit/caa4471aede4e4415fe4abb629f28c8e0ef6d954)
 - [66154e6e95807650591a7ad8b6e049ddd883b919](https://github.com/magento/magento2/commit/66154e6e95807650591a7ad8b6e049ddd883b919)
 - [49bcf98e7270e70bb3f5ce9d59c2bef015718489](https://github.com/magento/magento2/commit/49bcf98e7270e70bb3f5ce9d59c2bef015718489)
 - [c0b4c7a692ec32ad9b848b9ea4782c56469f90f3](https://github.com/magento/magento2/commit/c0b4c7a692ec32ad9b848b9ea4782c56469f90f3)
 - [411d0fc15bc196bab6ce8c37188c672a8501753b](https://github.com/magento/magento2/commit/411d0fc15bc196bab6ce8c37188c672a8501753b)
 - [9779ebe3b2187a970f62ab78bd84845e88cd9b2c](https://github.com/magento/magento2/commit/9779ebe3b2187a970f62ab78bd84845e88cd9b2c)
 - [eba92d0d7777b934fc5789344f3898424d19a187](https://github.com/magento/magento2/commit/eba92d0d7777b934fc5789344f3898424d19a187)
 - [983d74f74159c917564c36c4919801a968f40a3b](https://github.com/magento/magento2/commit/983d74f74159c917564c36c4919801a968f40a3b)
 - [0b51e8c67c9285df1de8c70e23ae109cc8da98f9](https://github.com/magento/magento2/commit/0b51e8c67c9285df1de8c70e23ae109cc8da98f9)
 - [74d431a08e53c0fc7e35bc185434c93a801d68b0](https://github.com/magento/magento2/commit/74d431a08e53c0fc7e35bc185434c93a801d68b0)
 - [7f73d67058718202210f95c76655dfa35f00351d](https://github.com/magento/magento2/commit/7f73d67058718202210f95c76655dfa35f00351d)
 - [2933223c683d077d81a3318f349e98863d689603](https://github.com/magento/magento2/commit/2933223c683d077d81a3318f349e98863d689603)
 - [64610d359a54c57d04e73d391a020a297aeeac4f](https://github.com/magento/magento2/commit/64610d359a54c57d04e73d391a020a297aeeac4f)
 - [d2d397a7acfe29db9bc2d55213eea2f01f393567](https://github.com/magento/magento2/commit/d2d397a7acfe29db9bc2d55213eea2f01f393567)
 - [07702273cc86b6aebea9fc37eb37cb09932968a7](https://github.com/magento/magento2/commit/07702273cc86b6aebea9fc37eb37cb09932968a7)
 - [735c840c731bf9b26e2da5723c3802fb158e54c8](https://github.com/magento/magento2/commit/735c840c731bf9b26e2da5723c3802fb158e54c8)
 - [7e17d2077a75df92afb39815bc91b0dd42a70b85](https://github.com/magento/magento2/commit/7e17d2077a75df92afb39815bc91b0dd42a70b85)
 - [46c51baf04020995a98c0c6f70e64eca6b14e1fe](https://github.com/magento/magento2/commit/46c51baf04020995a98c0c6f70e64eca6b14e1fe)
 - [3a3683f0a7244078609cd0e512ce6743af8c322b](https://github.com/magento/magento2/commit/3a3683f0a7244078609cd0e512ce6743af8c322b)
 - [6311d5cf7444436245e4326051a893f290e70bcd](https://github.com/magento/magento2/commit/6311d5cf7444436245e4326051a893f290e70bcd)
 - [4462eaf918f1e8d7362c19cba6bb6db2175efc64](https://github.com/magento/magento2/commit/4462eaf918f1e8d7362c19cba6bb6db2175efc64)

The fix will be available with the upcoming 2.3.0 release.
