### ISSUE TITLE
Microsoft Edge: Magento 2 adding product to cart nothing happens

### ISSUE THREAD

**Issue by onyxau** [magento/magento2#9269]
### Preconditions

1. No Product added to cart
2. I'm using a template Monster theme

### Steps to reproduce

1. Prodcut added to cart
2. Results: You have no items in your shopping cart
3. 

### Expected result

1. Adding product to cart

### Actual result

1. [Screenshot, logs]
![image](https://cloud.githubusercontent.com/assets/13165606/25082672/7c0f7f52-2391-11e7-8770-75ee42ae0917.png)

**Comment by korostii** [comment]
If you are looking for some help or an advice regarding setup or development please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/). 
The GitHub issue tracker is intended for tracking technical issues (read: "bugs") only.
The issues which cannot be consistently reproduced on a clean installation of Magento 2 CE aren't likely to get resolved in here.
Thus if you are, in fact, reporting a technical issue, please try add as much information as possible, including the environment you use, 3rd party themes and modules installed, preconditions, exact steps to follow, screenshots and stack trace from browser console and even the custom code you're using. These raise the chances of the bug getting reproduced and acknowledged. 
If you don't provide enough information, it is likely that the issue will receive a "needs update" label and will get closed in a couple weeks.

**Comment by onyxau** [comment]
Hi Korostii,

The same problems appears if I perform a clean installation of  Magento 2 CE. 
Mozilla Firefox works fine but when it comes to Microsoft Edge or IE when I add a product to cart magento redirects to the page saying "You have no items in your shopping cart".
I face the same technical problems if I install clean Magento 2 CE on a live host

**Comment by korostii** [comment]
Could you please specify in detail what environment do you have? Which server OS you use, web server, database, additional caching layers(if any, such as varnish, redis, etc.), which versions of those?
Which exact version of Magento are you on? Are you in production or development mode?

I have a instances of Magento CE at version 2.1.3 and 2.1.5 up, using IE11 to add a product to cart works just fine on both of them. Here's a snapshot: http://take.ms/50QL1
Which means, there are either some preconditions or steps missing from your bug report. I would kindly suggest that you check your browser console for errors whilst adding the product to cart using IE and Edge. If there are some, please post them here. Additionally, you could check the Network tab to see the request sent and the response from the server.
I would also suggest checking the exception.log for any relevant error messages.

**Comment by onyxau** [comment]
Ok. I am using Magento 2.1.6 CE on localhost Xampp v7.0.13, PHP Version 7.0.13, Windows 10 Pro and I am in production mode. Anyhow I have managed to fix the issue simply using 127.0.0.1 insetead of localhost in the address bar of Edge and no matter which theme I am using the product has been added to cart.

However now I have another problem after I have fixed that one: when I am clicking on the cart, viewing it nothing appears, the shopping cart is blank, it is wrtitten only Shopping Cart and Summary.

I have seearched for any solutions unfortunately I couldn't find any. I was using Magento 2.0.6 CE and it was working as a charm but when I have decided to update Magento I have some issues.

**Comment by korostii** [comment]
Magento does not support the operating system you've listed. Please confirm that you can reproduce this issue on a supported platform. For an overview of supported technologies, see [System Requirements](http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-tech.html).

Additionally, please use separate threads for reporting multiple unrelated issues, otherwise the secondary issues might get misunderstood and/or lost in discussion.

**Comment by onyxau** [comment]
Ok sorry my mistake for posting another issue in this thread, my apology.

Anyway, as far as I can tell you Magento 2 CE is working fine with Win 10, only the upgrade has caused me problems.

**Comment by korostii** [comment]
Yes, ipso facto it worked just fine on Windows up until 2.1.6 (where some issues with image resize have appeared - see #9212). 
Nevertheless, no official support was ever declared by Magento Inc. - and they happen to be the ones who set the rules out here. I've seen multiple issues get dismissed for the very reason that they were discovered on Windows.

If the reported issue got solved for you, I'd also suggest that you close the issue.

**Comment by onyxau** [comment]
Thanks

**Comment by afavata** [comment]
Enviroment: PHP 7.0.15-0ubuntu0.16.04.4
Same issue after upgraded to Magento 2.1.6. Product added to shopping cart does not show in mini cart. No increment and no way to check out as minicart show 0 product added.
Sometime redirects to the page saying "You have no items in your shopping cart".

**Comment by korostii** [comment]
@afavata, please read the thread above (which includes: some hints on how to debug such issues, where to look for help, etc.)
What you're experiencing isn't likely a to be a Magento's bug and no-one could help you based on the limited information you provide.

**Comment by afavata** [comment]
@korosti, thank you for your prompt reply.
I did some test... and found out that this issue is probabily coused by a SEO Extension
Looking to Chrome Console I found the following errors:

`
jquery-migrate.js:41 JQMIGRATE: jQuery.parseJSON requires a valid JSON string
migrateWarn	@	jquery-migrate.js:41
jQuery.parseJSON	@	jquery-migrate.js:232
ajaxConvert	@	jquery.js:8843
done	@	jquery.js:9260
callback	@	jquery.js:9720

jquery-migrate.js:43 console.trace
migrateWarn @ jquery-migrate.js:43
jQuery.parseJSON @ jquery-migrate.js:232
ajaxConvert @ jquery.js:8843
done @ jquery.js:9260
callback @ jquery.js:9720

customer-data.js:86 Uncaught Error: [object Object]
    at Object.<anonymous> (customer-data.js:86)
    at fire (jquery.js:3099)
    at Object.fireWith [as rejectWith] (jquery.js:3211)
    at done (jquery.js:9312)
    at XMLHttpRequest.callback (jquery.js:9720)`

Any tips to resolve this issue is well appreciated

Thanks

**Comment by korostii** [comment]
No problem, would be glad if I can help you resolve your issue. That being said, I would generally advise to go to the StackExchange. A lot more people read it and you'll probably be more likely to get a fast helpful response there (rather than here: unfortunately, some issue reports on Magento's github drag on for months unanswered).

> this issue is probabily coused by a SEO Extension

I would try to check whether the issue disappears after disabling said extension. If that is so, I'd contact the vendor (module creator) then, maybe have an update or will be available to produce a fix.

Other than that, the error itself seems to be caused by an invalid ajax response. I would suggest to hit F12 for the Inspector and try to look for red (having code other than 200) XHR requests on the Network tab ( http://take.ms/oBO1y ). If there are any, clicking on them and selecting Response tab http://take.ms/ZKfrO might provide the error information sent by the server.
