### ISSUE TITLE
Translate from DI does not seem to work

### ISSUE THREAD

**Issue by romainruaud** [magento/magento2#9411]
### Preconditions

1. Magento CE 2.1.6
2. 

### Steps to reproduce

1. I have a module defining this : 
```
class MyClass extends \Magento\Framework\View\Element\Template
{
    /**
     * @var array
     */
    private $rendererList;

    /**
     * Constructor.
     *
     * @param \Magento\Framework\View\Element\Template\Context $context      Block context
     * @param array                                            $data         The data
     * @param array                                            $rendererList The renderers used for autocomplete rendering
     */
    public function __construct(
        \Magento\Framework\View\Element\Template\Context $context,
        array $data,
        array $rendererList = []
    ) {
        $this->rendererList = $rendererList;

        parent::__construct($context, $data);
    }
```

and the DI : 

```
    <type name="Vendor\Block\XXXXX\MyClass">
        <arguments>
            <argument name="rendererList" xsi:type="array">
                <item name="term" xsi:type="array">
                    <item name="title" xsi:type="string" translate="true">Search terms</item>
                </item>
            </argument>
        </arguments>
    </type>
```

Notice the ```translate="true"``` for the title.

2. I add a log to the $rendererList variable
3. I add a translation for "Search terms" string into "Terms de recherche"
4. My front is properly configured with the proper locale

### Expected result

1. 
```
(
    [term] => Array
        (
            [title] => Termes de recherche
        )
)
```
I was expecting to see the translated string.

### Actual result

1. 

```
(
    [term] => Array
        (
            [title] => Search terms
        )
)
```

So for me the ```translate="true"``` in the DI is getting ignored, or maybe am I using it wrongly ?

**Comment by magento-engcom-team** [comment]
@romainruaud Thanks for reporting this issue. 
Di.xml used for Object Manager configuration to create objects. It should not be used for translation of any kind. Therefore since Magento 2.2.0 attribute 'translate' was removed from di.xml.
Logic for translation should be on presentation layer, not configuration one. So, if You want translation occur, You should move translation logic in template - some_template_for_your_block.phtml for instance. 
If you'd like to update it, please reopen the issue.
