### ISSUE TITLE
Failure Dashboard Magento 2.1.5

### ISSUE THREAD

**Issue by lojasmarques** [magento/magento2#9418]
### Preconditions

1. I did the manual instalation by the FTP, after complete all the process, when I open the Dashboard in Magento 2.1.5 i see this bugs and I do not know how to solve this problem for use this applicattion;
2. If someone can help me in Portuguese, step-by-step, i am Available in cell phone (55 53 981426029 -whatsApp) 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, [logs]](https://support.hostinger.io/scripts/file.php?view=Y&file=94ecea6040a8c4ff92f064b4bfd2ca12&S=59b04ca7566705c6d8f8842b80e81b84)

**Comment by JDavidVR** [comment]
this kind of questions should be asked in magento forums or stack overflow,
https://community.magento.com/
http://magento.stackexchange.com/

answering your question, you have to access to server and use magento cli to deploy themes:

php -f bin/magento setup:static-content:deploy en_US pt_PT depends on language you've configured your installation

**Comment by magento-engcom-team** [comment]
@lojasmarques, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
