### ISSUE TITLE
update "tubalmartin/cssmin" to make CSS minifying compatible with calc()

### ISSUE THREAD

**Issue by frenky2334** [magento/magento2#9447]
Hi!
I tried update composer to update "tubalmartin/cssmin" module. But in update progress i get the next one message which you can see at the attached screenshot. 
![cssminify](https://cloud.githubusercontent.com/assets/26610655/25530461/fdb6229a-2c2e-11e7-92c6-7a377aa89420.png)
The composer looks like this:
![composer](https://cloud.githubusercontent.com/assets/26610655/25530468/0222e7c8-2c2f-11e7-9763-fd8b076522c6.png)
Please, help me!

**Comment by hostep** [comment]
Remove `tubalmartin/cssmin` from your `composer.json` file, Magento already includes an older version, so it will cause conflicts.

Also: next time, use the [community forum](https://community.magento.com/) or https://magento.stackexchange.com/ or something like that, because this isn't really a bug :)

**Comment by frenky2334** [comment]
But i need newer version of this module because in new versions the bug with the calc() property is fixed

**Comment by sambolek** [comment]
Hi @frenky2334
this pull request updates cssmin and fixes css calc() issues https://github.com/magento/magento2/pull/9027#event-1049557767

**Comment by korostii** [comment]
>this isn't really a bug :)

I'm sorry, how exactly an outdated dependency "isn't really a bug"? 
Is that idea written somewhere in the guidelines? Should [all those "update ZF dependencies" issues](https://github.com/magento/magento2/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20Upgrade%20ZF%20components) get closed? Maybe let's also drop [the issue about updating the composer](https://github.com/magento/magento2/issues/4359) as well while we're at it?

It might be "not a priority", but it's still a valid technical issue.

**Comment by sambolek** [comment]
Current M2 releases are made to work with previous versions. 

As CSSmin maintainer changed the way the library is called, you cannot simply update the library version and hope everything will work. That's why version in composer.json is set to a specific one.

The library was updated in the pull request I linked above. You might be able to create a patch and apply it or wait for a new M2 release where it'll probably be merged.

**Comment by frenky2334** [comment]
Hi @sambolek 

Thanks for the answer.
I look at pull request which you recommended me. I have one question. Where can I get the updated library files?

**Comment by sambolek** [comment]
Incorporate all changes from pull request (including composer.json) and run "composer install" or "composer update tubalmartin/cssmin".

**Comment by frenky2334** [comment]
@sambolek 
In your pull request you use 2.2.0-dev version, but in our production is 2.1.6
The difference in versions will not lead to the breakdown of the site? 
Or better not risk for update this module and wait the official update magento?

**Comment by sambolek** [comment]
If you want to be 100% sure, wait for next release :)

**Comment by frenky2334** [comment]
@sambolek 
Thanks )

**Comment by korostii** [comment]
> If you want to be 100% sure, wait for next release :)

Just a heads up: there is no guarantee it will appear in the next 2.1.x release (or any of the 2.1.x releases at all, for that matter), and timelines for the future releases aren't provided by Magento, Inc.
So, potentially, you might need to wait for months until it gets released in 2.2.
Also, making an extra pull request targeting 2.1-develop should somewhat speed up that process (as explained [here](https://community.magento.com/t5/Magento-DevBlog/Pull-Requests-for-2-1-x-Patch-Releases/ba-p/65630) by a Magento employee).

**Comment by magento-engcom-team** [comment]
@frenky2334 Closing this issue as it is not a Magento bug, `tubalmartin/cssmin` is already bundled with magento version 4.1.0.

Thank you.

**Comment by korostii** [comment]
> Closing this issue as it is not a Magento bug

I beg your pardon? By using 3rd-party code inside Magento, you effectively start owning the 3rd-party issues as well. It's just the same with bundling the fotorama.js into Magento: you add some bugs by doing that, and fixing them (if, say, that 3rd-party code isn't maintained any more) might require to either your own fork of said code (as it was done with zend framework 1) or replacing such a library altogether.

But it sure _is_ a Magento bug, albeit it is already fixed by a @sambolek on the `2.2.x` branch (many thanks to him for that). IMHO we're also lucky this is one of those issues where updating the bundled library (and fixing a few lines of code invoking it as well as couple tests - in this particular case) is enough to fix a bug.

> tubalmartin/cssmin is already bundled with magento version 4.1.0

For whomever seeing this issue in their installations: yes, `tubalmartin/cssmin` of version 4.x is currently bundled, but only on the `2.2.x` releases. 

UPD.: `2.1.x` branch received the fix in version 2.1.15, "tubalmartin/cssmin" got updated to "3.0.0".
