### ISSUE TITLE
Reopened: '?SID' in URL even if disabled

### ISSUE THREAD

**Issue by hostep** [magento/magento2#9453]
This is a duplicate of https://github.com/magento/magento2/issues/5517, but after waiting for several weeks for that ticket to be reopened, I'm creating a new ticket

### Preconditions
- Magento CE 2.1.5
- PHP 7.0.16
- Apache 2.2.32

### Steps to reproduce
1. Install Magento CE 2.1.5 using composer
2. During the installation, set the base url to: https://www.m2.dev/
3. In your Apache configuration, set up a VirtualHost with 2 domains, one with 'www' and the other without 'www', something like this:
```apacheconf
<VirtualHost *:443>
    SSLEngine On
    SSLCertificateFile "/opt/local/apache2/conf/server.crt"
    SSLCertificateKeyFile "/opt/local/apache2/conf/server.key"

    ServerName m2.dev
    ServerAlias www.m2.dev

    DocumentRoot "/path/to/magento2/pub"
    
    <Directory "/path/to/magento2/pub">
      Options Indexes FollowSymLinks ExecCGI
      AllowOverride All
      Order allow,deny
      Allow from all
    </Directory>
</VirtualHost>
```
4. After the installation, do this:
```bash
$ curl -I --insecure https://www.m2.dev/
HTTP/1.1 200 OK
# good, is expected!

$ curl -I --insecure https://m2.dev/
HTTP/1.1 302 Found
Location: https://www.m2.dev/?SID=abcdef...
# good, is expected!
```
5. Now change the Magento setting: General => Web => Session Validation Settings => Use SID on Storefront => No
6. Flush your caches
7. Execute the same thing as above:
```bash
$ curl -I --insecure https://www.m2.dev/
HTTP/1.1 200 OK
# good, is expected!

$ curl -I --insecure https://m2.dev/
HTTP/1.1 302 Found
Location: https://www.m2.dev/?SID=abcdef...
# NOT good, there should be NO ?SID in the url!
```

**Comment by coresh** [comment]
If the website with multi-store views:
after the request to one of store view URL => redirected to default store URL

Example:

    # store view URL: https://m-store-view-ru-ru.com/

    $ curl -I --insecure https://m-store-view-ru-ru.com/

    HTTP/1.1 302 Found

    Location: https://m-store-view-default.com/?SID=62c3347d2aa7c5e59ee874f1a78c8881

    # NOT good, there should be opened: https://m-store-view-ru-ru.com/

**Comment by vityakopin** [comment]
Internal ticket MAGETWO-70322 was created.

**Comment by magento-engcom-team** [comment]
@hostep, thank you for your report.
We've created internal ticket(s) MAGETWO-70322 to track progress on the issue.

**Comment by strell** [comment]
#mageconf

**Comment by magento-engcom-team** [comment]
@strell thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by okorshenko** [comment]
Hi @hostep 
The issue has been fixed and delivered in 2.2-develop branch. Will be available with upcoming patch release.
Fixed in magento/magento2#12743 by @strell in 2.2-develop branch
   Related commits:
     1. 38720ea

**Comment by okorshenko** [comment]
Hi @hostep. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1298 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - 54301a8ea63134b961d6b7b9891c31bc2798f8dc
 - 402b719168fc8b17ebc099c12b85f629cf90303b
 - 3837f2780b32112b7f70a9d3074158ee2336b1b7
 - 031e23e93ffaa258a39dfed5c5edb0e873ab0aa8
 - aa267f462f7eb964226a9c89d20c04b718406337
 - 934818dbee0bd36ec5eae7b3b7230c4d8a70b481
 - 6bed7d475bff5e98e27b8fdcaa998438bc31ed05
 - 72b2794043afd0012f9a8d5f6fc04df07acad3af
 - 4e64c415e26845826b527c17008eda00d3808591
 - d3feb280ed621c5ffe2dc3a2b7ac30abb25d9c22
 - 7aeccea46d2336a1322811a9d60d52432108c8e3
 - b857c022ae1cdb7975cf5c3d79cd679843c72a3b
 - a75bf2391dfc6e7c8a1283490f5de7551de42bbe
 - ab2e5798e529633f770c3970a0df999c11764e06
 - d904690443d43322c5dd2c58d075944eae867316
 - a821c7a3c17eb06983f421c47a7cc0fe99983a38
 - 68ac4c0bd6cae6b5b62e683c23f49293ee41d797
 - 93fe4d14faba635cc7c668b2d931e7595567cda9
 - f43fd4b98c55e1f498d060aeb245e4c969bdcb13
 - 2c52a8fd15cff7af7245573e2f26be6d601acb08

The fix will be available with the upcoming 2.3.0 release.

**Comment by hostep** [comment]
Thanks @okorshenko, unfortunately I can't acces the `magento-engcom/magento2ce` repo, also, it would surprise me if all these commits you posted are linked to this one issue, would be great if you can narrow it down to which commit is actually the fix, thanks! :)

(_update_: I just noticed the second to last post where the single commit is mentioned, it looks like this fix is going to be included in 2.2.4, nice!)

**Comment by Kist221** [comment]
We are currently running 2.2.4 and it is not fixed @hostep

**Comment by lano-vargas** [comment]
@Kist221  I've applied the fix to my Magento2.2.2 as per okorshenko https://github.com/magento/magento2/issues/9453#issuecomment-353555032

It has worked as a treat!
