### ISSUE TITLE
URL key for specified store already exists. While adding new product with same name as of older product.

### ISSUE THREAD

**Issue by pankajkherwal** [magento/magento2#9465]
### Preconditions

1.  Magento 2.1.6
2.  PHP 5.6.25
3.  Single Store & single website

### Steps to reproduce

1. Add a product.
2. Add another product with same name, same category, same attributes BUT Different SKU

### Expected result

1. URL key for specified store already exists.

**Comment by korostii** [comment]
First of all, GitHub has a useful feature called search. If you'd used it, you might've know the answer already and wouldn't need to create a duplicate number forty-something of the same common [complaint](https://github.com/magento/magento2/search?q=URL+key+for+specified+store+already+exists&type=Issues). Googling it would've had a similar effect.

Not every error message you see is symptomatic of a bug. The exception you mention is in particular considered to be "expected behavior" if the URL key you're trying to save is in conflict with a different one. Basically, it just means "try another one".

Therefore, if you are looking for some help or an advice regarding setup or development please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/).
The GitHub issue tracker is intended for tracking technical issues (read: "bugs") only.

**Comment by JacobDrummond** [comment]
@korostii 

> First of all, GitHub has a useful feature called search...

I understand your frustration, but I don't think there's any need to be rude to @pankajkherwal. This is the [only Magento2 issue he's opened](/magento/magento2/issues?q=author%3Apankajkherwal), hardly a repeat-offender.

> The exception you mention is in particular considered to be "expected behavior" if the URL key you're trying to save is in conflict with a different one.

It doesn't sound like @pankajkherwal input a URL key manually. If Magento is generating a URL key, surely it should be able to create a unique one by incrementing a numerical suffix, like Magento 1?

**Comment by korostii** [comment]
> I don't think there's any need to be rude

Hi, @JacobDrummond.
I am very sorry if my comment seems rude to you, no offense was intended.
I do know that if you read something obvious(obvious for you, that is) in your head, using Hugh Laurie's voice, it might of course sound a bit sarcastic. Such an obvious advice shouldn't be taken as an offense: pointing out the obvious solution first rather then going into the rare and complex ones is the responsible thing to do, and saves a lot of time to all the parties involved. It is often easy to overlook something obvious and it is often better to get a pointer in the right direction rather than the "ah this is so trivial he can figure it out himself" or "why should I bother with this" silence of the passing-byers. Doesn't cover all the cases, but it's a good start.
Have you seen this one from the "IT Crowd"? A real life-saver.
![4463d682735d1cb300ce7e5032c9128e3dd4a553f5a2fc44273e07f8a3ae07bd](https://cloud.githubusercontent.com/assets/24894168/25712514/8bcf9a8c-30fa-11e7-9e93-14b72cfdc1ae.jpg)



> If Magento is generating a URL key, surely it should be able to create a unique one by incrementing a numerical suffix, like Magento 1?

Of course it is able to do that. AFAIK It _chooses_ not to, expecting the decision to be made by the user instead, not unlike how git leaves the conflict resolution up to user. Point being, such an auto-generation might be a nice feature to have, maybe switchable somewhere in configs, but it is not something mandatory and certainly not a magical one-size-fits-all solution. 

Maybe you or I would've implemented it differently, but in scope of Magento 2 CE that's exactly the behavior expected and changes you described would probably go into the "suggested improvements box". In other words, chances of this behavior getting changed anytime soon are extremely thin.

I just wish this behavior would be explained somewhere in documentation and would appear as the number one result when googling this error message. That would certainly help to avoid a lot of confusion.

**Comment by orlangur** [comment]
System works as expected with the steps described.

Error message was improved on Magento 2.2.0 branch to give more information to merchant what exactly needs to be changed.
