### ISSUE TITLE
Bad customer experience regarding async widgets / banners (5+ sec delay)

### ISSUE THREAD

**Issue by timhofman** [magento/magento2#9478]
### Preconditions

1. All Magento 2.x Enterprise Edition versions

### Steps to reproduce

1. Any page that uses widgets to  display banners  (async /banner/ajax/load/?sections=)

### Expected result

1. Only load the widgets/banners for the current page. Do not load all widgets a once, and don't split this data into 2 calls (current page, the rest) as a new solution. Lots of data is being fetched from the DB while it isn't even used by the visitor session.

### Actual result

1. Currently all widgets / bannerrs for the active storeview are loaded through an AJAX call. Since all of them are loaded during this call, sites that have lots of content rich pages suffer a big delay in visual experience. We have calls in our New Relic that go up to 5+ seconds to fetch all the data. Apart from the experience, lots of data is loaded for i.e corporate pages, which aren't even visited for like 95% of the traffic.

**Comment by veloraven** [comment]
@timhofman thank you for your feedback.
Given this issue is reported against Enterprise edition, please report via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level.
We can not treat issues in EE functionality via GiHub
