### ISSUE TITLE
M2.1.6 EE, admin user permessions not checked correctly on catalog->product

### ISSUE THREAD

**Issue by fballiano** [magento/magento2#9510]
1. create a website/store/storeview
2. create a user role to just be able to work on this new website/store/storeview
3. create a user with this new role

You should now be able to create/edit products using the catalog/product backend mask but ONLY IN YOUR website/store/storeview.

Instead it seems the system doesn't check the permission and allows the new user to change product's attributes also for "global".

**Comment by veloraven** [comment]
@fballiano thank you for your report.
Given this issue is reported against Enterprise edition, please report via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level

**Comment by fballiano** [comment]
@veloraven I understand, but it's really unclear cause there's no documentation on how to report an EE bug.

Anyway, I opened the ticket in the support portal, internal ID 578818.

Thanks

**Comment by korostii** [comment]
@fballiano is quite right: the [guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) don't even mention Enterprise Edition. 
At the same time, it probably has [the link to GitHub in admin footer](http://take.ms/31tXF) (same as in CE), hasn't it? That's a bit confusing.

**Comment by fballiano** [comment]
exactly, in the backend footer the "report bugs" points to this github repo.

**Comment by magento-engcom-team** [comment]
@fballiano thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

**Comment by korostii** [comment]
Hey @magento-engcom-team, the question of whether an EE issue belongs to this repository comes up in comments to various issues all the time.

Would you be kind enough to consider providing this info (which you've just posted) into the [repository's guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)? That way, some people will be able to get this info prior to posting and you'll be able to reference it whenever needed (instead of copy-pasting a big boilerplate message)

Best regards & Have a nice day!
