### ISSUE TITLE
Validation for "Schedule Update From" fields is absent 

### ISSUE THREAD

**Issue by kozhemyakin** [magento/magento2#9521]
Steps:
1. Log in to Admin
2. Go to Products -> Categories
3. Input any text in "Category Name" field
4. Click "Schedule Design Update" -> Input any numbers in " Schedule Update From/To" fields
5. Click "Save"

Actual result: blank page, error in log 
> "Invalid input datetime format of value 'Invalid date'";i:1;s:5854:"#0 /var/www/kozhemyakin/store_216ce/vendor/magento/zendframework1/library/Zend/Filter.php(114): Magento\Framework\Stdlib\DateTime\Filter\DateTime->filter('Invalid date')
Expected resullt: "Invalid input date format" message appears

Best wishes.

**Comment by veloraven** [comment]
@kozhemyakin thank you for your report.
Given this issue is reported against Enterprise edition, please report via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level
I'm closing this issue as it refers to EE functionality and so we can not treat it as GitHub issue.
