### ISSUE TITLE
"From","To" fields are absent on "Cart Price Rule" page on Magento 2.1.6 EE

### ISSUE THREAD

**Issue by kozhemyakin** [magento/magento2#9523]
Magento 2.1.6 EE

Steps:
1. Log in to Admin
2. Go to Marketing -> Cart Price Rules -> Click "Add new" button
3. Check "From", "To" fields on the page

Actual result: "From","To" fields are absent
Expected result: "From","To" fields are on it

Best wishes.

**Comment by veloraven** [comment]
@kozhemyakin thank you for your report.
Given this issue is reported against Enterprise edition, please report via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level
