### ISSUE TITLE
The value of attribute "second_image" must be set - Error when creating a category or sub category

### ISSUE THREAD

**Issue by qmigroup** [magento/magento2#9527]
I had upgraded my Magento 2.1.3 to 2.1.5 and everything worked fine except that I am not able to create any category or subcategory. I get this error:
The value of attribute "second_image" must be set 

I have reindexed, cleared cache, deployed static content etc, but the error still persists.

Any idea what might be causing this?
Thank You

### Preconditions

1. Apache 2.1.4
2. PHP 7.0

1. [Screenshot, logs]
![untitled](https://cloud.githubusercontent.com/assets/28442514/25746001/6f21c0a2-316f-11e7-83fa-7826279f1f49.png)

**Comment by korostii** [comment]
Catalog categories in Magento 2.1.5 out of the box only provide a single image attribute called "image" and upload for any additional image attributes with different attribute codes is not implemented. That's gonna change in future versions (see #5978 for details), but not just yet.

You seem to have some 3rd-party or custom code which attempts to provide a second image attribute for the category entity called "second_image" and doesn't handle the upload properly. I would suggest that you contact the vendor if that's a part of some 3rd-party extension (or the developer who authored this code if it's your own customization) in order to fix the issue.

Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/) if you need some additional help or advice regarding setup or development. 
The GitHub issue tracker is intended for tracking technical issues (read: "bugs") only.
The issues which cannot be consistently reproduced on a clean installation of Magento 2 CE aren't likely to get resolved in here.

**Comment by qmigroup** [comment]
Yes you seems to be correct. I have added some custom modules which might be creating this problem.

Thank You for your suggestions.
