### ISSUE TITLE
Fedex Freight Not Showing Rate

### ISSUE THREAD

**Issue by TenzinNKhando** [magento/magento2#9534]
Currently on our site, we have products that are over weight. For those products we want to use Fedex Freight quotes but the quote for Fedex Ground is showing up. I've contacted Fedex and they are instructing that we need to send company account # and freight account #. However, Fedex configuration in the admin panel only has one field for account number.

### Preconditions

1.  Magento 2.1.5
2. PHP 7.0.15
3. SM Market Theme

### Steps to reproduce

1. Log into Admin
2. Stores->configuration -> Sales -> Shipping Settings
3. Enter Origin Info
4. Stores->configuration -> Sales -> Shipping Methods
3. Expand 'Fedex'
4. Select 'Freight' and 'Ground' in **Allow Methods**

### Expected result

1. To see Freight Rate and Ground at checkout

### Actual result

1. Only seeing Ground rate
![image](https://cloud.githubusercontent.com/assets/13293090/25765988/b6cfa1b4-31a4-11e7-9417-242a3687aaf9.png)
![image](https://cloud.githubusercontent.com/assets/13293090/25766002/c943e256-31a4-11e7-9bad-8f68bf78c9c5.png)

**Comment by haneef-faisal** [comment]
@TenzinNKhando I had the same issue on CE 1.x; mostly you have got wrong config info for the FedEx account (Account ID, Meter Number, Key, Password). Re-Check and try again.

BTW, as far as I can remember, the native FedEx option will only show rates for Air Freight and not for Ground Freight. You might want to search for an extension that can do Ground Freight.

Do update this with your findings so that others can save time :)

**Comment by birchestx** [comment]
Should be closed, is config.

**Comment by magento-engcom-team** [comment]
@TenzinNKhando, thank you for your report.
We've created internal ticket(s) MAGETWO-80720 to track progress on the issue.

**Comment by ishakhsuvarov** [comment]
Hi @TenzinNKhando
Looks like this is not a bug but misconfiguration. Please check other comments with suggestions.
Closing this ticket for now. Please reopen if you think this is a core Magento issue.
