### ISSUE TITLE
Editor option is missing on magento 2 admin

### ISSUE THREAD

**Issue by antofebin2636** [magento/magento2#9550]
![bug](https://cloud.githubusercontent.com/assets/15243707/25806677/eda1cb46-33fb-11e7-970d-b534c63bc6d8.png)

Editor is missing 
Magento Version 2.0.13

**Comment by korostii** [comment]
Possible duplicate of #3601, #4828 or #7834.

Could you please check your Magento's logs for errors? (read [here](https://mage2.pro/t/topic/307) on how to find those)
If browser console contains some errors, please provide a copy or a screenshot of those as well.

**Comment by antofebin2636** [comment]
No console errors http://prntscr.com/f5qx2l & it diseppar last week all of a sudden because i can see the data on website http://prntscr.com/f5r0yw can ypu please help

**Comment by korostii** [comment]
Could you please also check your Magento's own logs for errors? (read [here](https://mage2.pro/t/topic/307) on how to find those)

**Comment by antofebin2636** [comment]
What will be the errror type.

**Comment by antofebin2636** [comment]
is it ok to send u the log file

**Comment by korostii** [comment]
> is it ok to send u the log file

Ideally it's better to have all the info here instead (in case someone else recognizes the error and thus will be able to step in and help you), it's hard to guess what went wrong otherwise. 
I could suggest uploading your log to https://pastebin.com/ (or other similar service) and providing a link to it instead.

**Comment by antofebin2636** [comment]
https://ufile.io/vs1o4 - System Log

https://ufile.io/odm4v - Excepion Log

**Comment by korostii** [comment]
I think, this is the one you should look at:
`[2017-05-10 07:45:39] main.CRITICAL: Invalid template file: 'Magento_Cms::page/edit/form/renderer/content.html' in module: 'Magento_Backend' block's name: 'widget\form\renderer\fieldset\element_0' [] []`

Do you, by any chance, have any 3rd-party or customized code that extends `\Magento\Cms\Block\Adminhtml\Page\Edit\Tab\Content` class or maybe you've had `Magento_Cms::page/edit/form/renderer/content.phtml` removed for whatever reason? 
It seems that this error should not appear on a Magento2.0 instance out of the box. The issues which cannot be consistently reproduced on a clean installation of Magento 2 CE aren't likely to get resolved in here.

Good luck with your further findings & please close the issue if you manage to resolve the issue yourself.

**Comment by antofebin2636** [comment]
my site is already on complete stage if i do a reinstall the magento 2 can i link to same database

**Comment by korostii** [comment]
What I write below is pure guesswork, because I don't know what is your setup, thus proceed with caution. It is advised to backup valuable information before performing destructive operations.

But, if you suspect that core files might've been corrupted, you can simply open a terminal, point it at your Magento2 installation directory and then perform the following commands:
- clean the `vendor` directory by invoking `rm -rf vendor/*` 
- reinstall all external modules (including Magento2 CE ) by invoking `composer install` 
- clean caches: `php bin/magento cache:flush` 

The database will remain intact if you do that.

**Comment by antofebin2636** [comment]
can i clean vendor directory only using this command rm -rf vendor/* without reinstall any other external module if so  does it effect my custome theme

**Comment by korostii** [comment]
I am sorry, but, first of all, I need to clarify something: this is not a help desk, and I am no representative of Magento.
I could help you clarify a description of a bug in Magento's core as a gesture of good will. However, I do not have time to solve all of the issues you encounter. That goes for pretty much everyone monitoring these issues on Magento's GitHub.
If it's not a bug in Magento itself, but some issue with your own local instance (which I have no access to), you're largely on your own.

If you can't handle that yourself, my advice is to hire someone who can, or reach out for help [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/).
Have a nice day.

**Comment by magento-engcom-team** [comment]
@antofebin2636 please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
