### ISSUE TITLE
Magento 2 is often idea rich but vs the time spent function poor

### ISSUE THREAD

**Issue by ghost** [magento/magento2#9554]
This is constructive criticism of my experience as a Magento 2 developer coming from other ecommerce systems.

I expect a learning curve with any software change, however as a developer of 11 years Magento 2 has been an extremely frustrating experience and I will attempt to articulate why to you.  I checked for a feedback forum in the forums but there wasn't one so seeing posts like this: https://github.com/magento/magento2/issues/5906  I figured it could go here.

As a small business owner of a web development company my clients are very concerned with time spent to result obtained why I've stayed successful as a business owner for over 8 years is because I can deliver on that to them.  They feel they get good value and good quality for the time I spent.  CS Cart for example was messy but very easy to modify with any code I desired and it worked for over 6 years for one of my clients.  Magento 2 comes extremely well recommended though so he pushed to go with that.  And so we are but I want to give constructive feedback to you if I will be married to this software for years to come.

The biggest concern I have is it is very hard to be productive with Magento 2's framework.  It is layered more densely than an onion and every layer has some ideology behind why it was designed that way.  The problem is, it leads to architecture that is ideologically rich and functionally poor.  It defies the oldest rule of programming which is KISS (Keep It Simple Stupid).  Simplicity is beauty and harder to achieve, brevity is harder to achieve than this rant for example and would take me 10x longer to write and rewrite still convey what I wish to say.

When there is more ideology than functional purpose to code it obscures the function and purpose of the code to the point it becomes hard to work on it or achieve anything without hours of looking up examples.  Object Oriented Programming in general has been on this trend for quite some time, becoming more and more about grand ideas and less and less about actual algorithms, procedures, or code that does the actual work.  This shifts the focus from what matters to what I personally feel is things developers tell each other to feel good about themselves or come up with ideas to fulfill some personal need rather than solve a problem simply and beautifully.  Complexity is expected but to be combated not fully embraced and then poorly documented in a way that mostly spouts ideology rather than useful information.

This iteration of programming is idea rich and function poor when I can achieve the same results in other frameworks and ecommerce systems in 1/6th the time even accounting for Magento 2 being new to me there's not something just a bit wrong but an entire foundational belief system that created it.  Even reading guides on how to achieve certain tasks people will often comment at the end "wow that was a lot of work and really complicated but if you copy it exactly it should work for you".  Like.. that isn't even close to the goal a framework should wish to achieve.

Magento 2 has a very good result as an end store in terms of features, it isn't functionally poor in it's delivery it is functionally poor in it's development because you are jumping through hoops constantly to appease the architects I'm half convinced wish me to either suffer or perhaps this was all designed to keep small devs out of the business entirely by making it extremely hard to break into.  And really neither of those are feelings I should harbor when using a top end framework.  I should marvel at the simplicity and how easy it is to get so much done so quickly not feel like I need to hire 5 more developers to do the same work I used to do as one person.

**Comment by erfanimani** [comment]
Magento development being six times slower than other ecommerce systems is still pretty good, considering Magento 2 has got a tons of caching layers, indexing, materialised views, support for Varnish/ESI, extension/plugin system that prevents (in theory) module conflicts, an EAV engine, XML layout engine, more features than any other cart, and so on.

While I think your expectations weren't set 100% right from the beginning, I do agree with a lot of what you say. uiComponents magic is incredibly tough to understand for example, and while it provides a nice abstraction, abstractions only work when don't have to understand how the underlying concept works. But ask me in about a month and maybe I will have changed my mind.

**Comment by gsomoza** [comment]
@atrixtech Magento 2 is certainly not a KISS framework, you're right about that: it's not a framework for merchants that have very simple functional needs and don't need much in regards of flexibility or scalability; there are other frameworks that may be more appropriate for those merchants, both in the PHP world and outside.

But I do find the Magento architecture extremely useful for many of the challenges I came across in my company, and I cannot understate that enough. We currently leverage a very wide range of Magento features for the better good of our clients, and wouldn't have been able to deliver them as efficiently without a framework like Magento's. Over time, I realised that the pieces of code I thought were over-engineered only seemed so because I didn't need them for that particular project. I'm not saying there's nothing over-engineered in Magento, cause maybe there is: all I'm saying is that in the long run that factor mattered less to me than I thought it would. And the only cases I felt unproductive, slow, or that Magento was fighting "against me" where with projects where Magento was ultimately NOT a good fit.

Our experiences seem different then - but that's perfectly fine: Magento isn't for everyone (nor is WooCommerce, PrestaShop, etc). I believe the true catalyst for an efficient/successful Ecommerce project is the ability to choose not only the solution that best fits the client's needs, but also the team's capabilities.

**Comment by ghost** [comment]
@gsmoza KISS to my knowledge isn't a type of framework it's a general principal applied to everything from music creation to programming.  My client doesn't have simple functional needs either, he often has me program custom solutions to tailor fit his business needs because software for it doesn't exist or doesn't work how he'd like.  So for any ecommerce platform I will have to add custom features that are so specific they will not be bundled with any ecommerce system as they revolve around his business process.  

I find the architecture to get in the way of not only adding this functionality into Magento 2 itself but even performing what I'd consider a simple task on other platforms becomes something involving 3-12 files and hours of reading and that isn't really good design no matter how I look at it.  Simple tasks should be simple, let the complicated tasks be complicated.  Something as simple as modifying the categories page with a custom chooser that would then filter the products would take me 45 mins, but it ended up taking 7 hours and the gross majority of that wasn't programming the feature it was jumping through magento 2's hoops.

The core features are a good fit for his needs in terms of Magento 2, developing for it is however frustrating not due to its lack of fit to my client or my capabilities or because it is over engineered, it simply is not easy to use, alter, add to, or perform simple tasks because every task is multi step, multi file, sometimes multi-layer, and requires comprehending not only how Magento 2 works despite it's "abstraction" but how it all fits together and to top it off there is a lack of documentation that actually tells you in simple terms how to achieve simple tasks instead you are encouraged to read the source code for examples or barring that looking for blogs or stackexchange posts for people that had the same troubles as you.  This is all bad.  I eventually get what  is needed done but the amount of work to the amount of actual functional usable features I am able to produce on Magento 2 is very bad and the thing I can point easily to as the source of that is Magento 2 itself.  It's cumbersome to code for.  If you're using native features designed into it sure they work good but if you're adding your own custom features the thing is a nightmare.

@erfanimani I don't really feel that's a fair trade off :/  I've made even cscart support varnish, it came with indexing and caching layers, it has an addon/plugin system, I actually hate the xml layout system of magento 2 and I find EAV overcomplicated attributes but it works.  I mean the reason we picked it is because it supposedly does those same things better and scalable solutions for it exist and done often.  The main thing we were interested in though was a bigger community so there'd be more high quality plugins available.  Given that plugins are so hard to create for it though it doesn't seem odd to me there isn't a ton of plugins for Magento 2 even though it's been out a while now.  We've got vested interest in it but that is why I made these posts, in hopes of the feedback hitting ears of some of the architects.  A framework should be easy to use, perfect frameworks would be intuitive to use and not to the architect themselves but to people new to the platform.  A tall order for sure, but this is so far removed from anything like that it's ridiculous.

**Comment by gsomoza** [comment]
Here's a recent article that I think is relevant to this discussion because it provides a different perspective / experience about Magento's flexible architecture:  [We Lanuched a Magento Site in 10 Days](https://magento.com/blog/customer-stories/we-launched-magento-site-10-days)

**Comment by ghost** [comment]
Ok here's my comments on that link:
1) "This was the project that Yitz had been preparing for since the launch of Magento 2. For a whole year, he and his 35-person team had learned the platform from the ground up."  -- This is pretty ridiculous not just the 35 person team but preparing an entire year how many man hours and money did that cost?

2) "Essentially, Web Solutions NYC had built a ready-made car, with a working engine. They just needed to add the bodywork."  So basically they imported products and reskinned the luma theme in a week.  That sounds ok for Magento2, until you realize that it was a 35 person team, their schedule was hectic, and they barely got it done, that's ridiculous :(

Let's say the average cost of a man hour for the project was $45 an hour, 35 people working a what 50 hour week?  That's a $78,750 reskin and product import for one week, though the project was 10 days.  Then you have the additional year of training which they don't specify how much time that took...  it only solidifies my points in my view.

I doubt we'll end up coming to a consensus but nothing I've seen here or elsewhere has done much but solidify my view.

**Comment by hostep** [comment]
~@gsomoza, sorry for this not being on topic, but checking the html code of http://www.jomashop.com/, I see a Magento 1 shop, not a Magento 2 shop. Maybe the client decided after 10 days that the M2 version wasn't stable enough and reverted to their old shop? :p (sorry, just thought this was funny to share).~

If you want some more realistic numbers:
- We launched 5 Magento 2 shops in a timeframe of around 10 months.
- The quickest one was done in about 26 days, the longest was done in about 152 days (only development, and these aren't working days, just subtracted the date we started developing from the going live date)
- We worked with about 14 - 18 people (of which 5 - 8 are developers)
- Before starting work on the first real Magento 2 shop, we spend about 13 months of doing research into M2

Just saying :)

**Comment by gsomoza** [comment]
@hostep the website that was built was https://www.worldofwatches.com. The numbers you shared look good too: every project is different.

@atrixtech I'm happy just offering my perspective, I don't expect to reach a concensus.

**Comment by erfanimani** [comment]
Although launching a project in 10 days isn't by any means a good thing. Clearly they were under pressure and their SEO tanked after launch:

![image](https://cloud.githubusercontent.com/assets/930470/26252765/bbf6a8f0-3ce3-11e7-8e0f-2fe7ccc02990.png)

**Comment by aj45f36gf** [comment]
If you find Magneto too hard, try Shopify.

Seriously could someone delete this thread? 

After 20 years of using and contributing to open source projects there is inevitably some people that whine and complain because the project is "too hard" for them. Maybe you should try going back to school or spend some more time learning the project and **CONTRIBUTE.**

There are plenty of companies that offer a EZ solution for eCommerce. Don't come here and post "Oh its too hard, please make it easier for me to charge clueless customers for features."

Please delete this thread, its taking up space.


P.S. Fix your website, its horrible. No wonder Magento is "hard" for you, you need to hire someone to build you a website.

**Comment by korostii** [comment]
@aj45f36gf, well, hello to you, too.
> Seriously could someone delete this thread?
> Please delete this thread, its taking up space.

Oh wow, you're actually suggesting censorship because you cannot comprehend people having a discussion? If that's the case, please delete your comment along with your GitHub account, its also taking up some precious invaluable space and now it's even taking my time.

It's not whining if you're expressing valid concerns. 
Let's be clear about that: Magento2 still has is complicated. It's months since its release, and there's still a plenty of unresolved issues present. More than 2000 of those, clearly http://take.ms/bAk4Q
Of course, sometimes it's people who have issues with Magento, but either way: an issue is an issue. You'd be a fool to deny that. And if you don't like valid concerns, just move along and be done with it.

Nevertheless, if you'd pay any attention to the comments above yours, you'd see that precisely zero people called Magento "too hard" in this thread, just "hard". Which is also a good point, and it's only helpful to know that in order to set realistic targets when working with Magento and spending proper time learning it. Ain't nothing wrong about that.

> and CONTRIBUTE

Oh, would you look at that, you don't have the word "Contributor" written near your username neither. Surprising, eh?

P.S. For someone with such a horrible attitude like that, You'd better be accurate with your spelling: http://take.ms/TDWDL 
It's called "Magento", not "Magneto". Repeat after me: "M-A-G-E-N-T-O".
Maybe it's you who needs to "go to school or spend some more time learning the project".

**Comment by aj45f36gf** [comment]
> Let's be clear about that: Magento2 still has is complicated.

Not so clear.

**Comment by maksek** [comment]
Appreciate the feedback, locking and closing the issue, as not related to any functionality. Please keep giving your feedback on our forum.
