### ISSUE TITLE
Status label is wrong in admin

### ISSUE THREAD

**Issue by darkogoles1** [magento/magento2#9566]
### Preconditions
1. Magento version 2.1.3, 2.1.6

### Steps to reproduce
1. Create Order status labels for default frontend store: http://collabshot.com/show/MVB4Tl
2. Original status labels (for admin store should be in this table: http://collabshot.com/show/21mPgT

### Expected result
When an order is created in the frontend, order status should have e.g. "erp_uploaded" code.
Label in frontend should be Processing, as we added store specific label "Processing" to "sales_order_status_label" table

But label in admin store should be the original label from "sales_order_status" table, which is not the case. 

### Actual result
In the file: /vendor/magento/module-sales/Model/Order/Status.php:145, the method "getStoreLabel" is trying to fetch a label for current admin store, but always returns the label for "Default" frontend store (which is id=1 in my case).

The reason is because Magento is not loading ADMIN store id but always returns default store id, even inside adminhtml area: 
http://collabshot.com/show/Q8KvAK

"$this->_storeManager->getStore($store);" always returns store id=1 instead of store id=0

This makes status labels usage useless either in the frontend, either in admin, this is how above sample statuses look like in admin: 

- On sales grid it looks ok: http://collabshot.com/show/jruSTa
- but inside order details screen it looks like this as having frontend label instead of admin store label: http://collabshot.com/show/APuCyI

So, finally, even the source model that is trying to fetch status label is showing Frontend label instead of original admin status label - all because of wrong store id (Default instead of admin) loaded in backend. 

### Best way to reproduce:
1. Create order
2. Open edit order page in admin and note "Order Status"
3. Go to Admin: Stores>Settings>Order Status and edit row with status that has order
5. Change label for Default Store View = "Processing on store view"
6. Refresh order edit form
### Expected result
Status = "Processing"
### Actual result
Status = "Processing on store view"

**Comment by magento-engcom-team** [comment]
We updated description:

### Best way to reproduce:
1. Create order
2. Open edit order page in admin and note "Order Status"
3. Go to Admin: Stores>Settings>Order Status and edit row with status that has order
5. Change label for Default Store View = "Processing on store view"
6. Refresh order edit form
### Expected result
Status = "Processing"
### Actual result
Status = "Processing on store view"

**Comment by magento-engcom-team** [comment]
@darkogoles1, thank you for your report.
We've created internal ticket(s) MAGETWO-80333 to track progress on the issue.

**Comment by okorshenko** [comment]
The issue has been fixed and delivered to 2.2-develop branch. Will be available with 2.2.2 release

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-81786

**Comment by magento-engcom-team** [comment]
Hi @darkogoles1. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1285 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - ad6c0af7dddbe2855a336acd3fd55994851e6d26
 - 6d3d70a72f08cba36c3aef6b59eea8db40eb4071
 - 6b0c02c5fd00d7a4237c4e1fae40dc265e3e43c3
 - c8abb139f8006826989fe4231dabc21fd4a02fd0
 - c6a9b5f7b13554958b547f387637c4288eb60b0b
 - c867b81af936e01a3d8ba8baa7128de06a5b7cd5
 - 88a3ad00d3ca97da847531c86bf64055dc1d790b
 - d87e316a2d6ee55debe2e712359adba8cb70fdb2
 - c76b04c9acde117c1021270500c8ded6954f6f05
 - 5ae21099aaa19699525c798f9ac0ef10db47b311
 - 931133abf574f1db96450f11f5980ef359d32967
 - 4c927a0585f11921c5e422b7e4a15b787e6338bd
 - 060a8f9f2b08ed97b31667eb76cace1dc0e642be
 - 4da2a7d2657b0da67f8be43bffc85f04b5b7144e
 - 008ef5583892d73c04628f003a2ce3d97fe0ed72
 - d3642e88d26a9240a1a4d648d37d984a785672a9
 - d37ce089d56c230f5896d5d7e922bd928b3726e6
 - b22b232563359f9cbcbf09709e63a87be7e81446
 - 6c02a2d3a272e872d549881d91ed6d5235a33f77
 - f2ec2ea175469636acec0bf9f65f0601854f89a2

The fix will be available with the upcoming patch release.
