### ISSUE TITLE
Category not showing all products

### ISSUE THREAD

**Issue by Joe-Whitehead** [magento/magento2#9568]
### Preconditions

1.  Magento 2.1.6

### Steps to reproduce

1. Assign products to category
2. Visit category page on front end

### Expected result

1. See grid of all products in the category

### Actual result

1. Only about half of the products show in the category

Only about 25 out of 40 products are showing in a category page - all of the products have exactly the same settings: 
1. Set to in stock
2. Set to be view able in the category
3. Enabled
4. Set in the correct category (all products are in the same category showing & non-showing)

I have tried re-indexing, clearing the cache, regenerating static content.

I can view the product if I navigate directly to it's URL, the interesting thing here is the breadcrumbs are different, so for a product that is showing on the category page the breadcrumbs are: 
`Website > Category > Product`
with the URL structure of `domain.com/category/product`

and the breadcrumbs for a product not showing in the category is:
`Website > Product`
with the URL structure of `domain.com/category/product`

Does anyone else have this problem?

**Comment by gsomoza** [comment]
I haven't payed much attention to how breadcrumbs work in M2 so I may be wrong, but I'd imagine the breadcrumbs are probably related to "how" you got to that product page rather than which category the product belongs to. Under that assumption it would make sense that you don't see a category on the breadcrumbs for a product that you didn't access through a category. 

The issue of product visibility in that category remains though. A few more questions that hopefully help lead in the right direction:
1. Are all the products identical? If not, could you point out any other differences that might be relevant (such as price, product type, etc)?
2. Can you duplicate in a vanilla Magento installation using the same category and product data? Just to discard any possible issues with 3rd party extensions.

**Comment by Joe-Whitehead** [comment]
Hi, thanks for your suggestions. 

1. All the products are identical, I made sure to look in detail at every option as I know how temperamental Magento can be.

2. This will have to be a next step in investigating, thanks.

I am using the same URL structure as those accessed going through the category, and when I do the same (directly typing the URL) on a product that is showing the breadcrumbs still show the full category structure.

**Comment by ghost** [comment]
I have seen this issue multiple times and saving the category makes them show up again then the products somehow disappear again.

**Comment by gsomoza** [comment]
> This will have to be a next step in investigating, thanks.

Let me know how that goes. If I have time I'll try to do it myself as well, but it might take a while.

**Comment by segeer** [comment]
Have similar problems in 2.1.6, where products added via the csv import process do not appear, but one added manually shows up in the default category.   Still experimenting.

**Comment by psapoznik** [comment]
same problem, bug very important! , please magento team!

**Comment by kunzi** [comment]
We have this problem too after upgrading to 2.1.6. Saving category has no effect. Not all migrated or new products are listed in frontend in certain categories. This might be a problem for the migrated categories only, but not sure.

**Comment by gsomoza** [comment]
I'll try to reproduce this on a clean env as soon as I get a couple of hours to spare (hopefully someone beats me to it though cause it could take a few weeks).

**Comment by Nissaelf** [comment]
I am having this issue as well on all of my product only a fraction of it is showing up. Also running version 2.1.6.

I am running a module that pulls my product from Amazon and loads it into my website. I can search for the product it shows up but it does not show up in the category search itself in the website. I have to search in All categories for the product to even show up. So I know that it is entered in correctly.

In my module I have to assign the category for product I know it is moving it correctly I see the product under the appropriate category in the backend it just does not show up i the front end not matter what I do. I tried updating the database, reindexing, and even clearing cache.

I have over 5000 products only 175 shows up. The product were all configured the same and loaded the same. Product that I enter in by hand is also having the same problem.

**Comment by ngz82** [comment]
I've also noted this problem with some of our categories.

In our case, all manually added products to the Category (small number, say 29 configurable products, possibly 1-2 simple),  exact same setup/settings as other categories which have no problems.  
For this example, only 4-5 products show up in the category, the only way to get them to show up again is the "Save" the category again.
As part of our deployment process we execute "bin/magento index:reindex" (runnign magento in Production mode) , and whenever that is run, the products disappear from the category again. 

Steps to reproduce (m2.1.6)
- Products -> Categories
- Select Category
- Select "Save" - Products all appear on site.
- run command "bin/magento index:reindex" 
- Products removed/ do not show up on Category page. - in our case only 4 products remain showing up.
Repeat the Save category and they show up again.

**Comment by magento-engcom-team** [comment]
@Joe-Whitehead, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by mritu19** [comment]
Hi @magento-engcom-team 

I am working on M2.2.0 and have successfully migrated M1.9.1.0 data. But Unfortunately I have the same Problem, I am not able to see any product under category. However, I am able to search the all migrated products and respected product detail page.

I have around 84.5K products and the product is configurable and simple.

The Problem is below :: 
1) I am not able to see any product under category (product listing page)
2) Another Major problem is ::: Configurable product's price is missing. and catalog_product_price indexing is processing from last 2 days.

[Note: I have tried to save 2-3 products thereafter i am able to see those products in respected category in Frontend. but it is not feasible to save 84.5k Products manually again one by one.

 I Have also followed all necessary steps which is suggested under community support (Like cache, reindexing, isRangingNeeded()->false)....

Can you please help me regarding the same. Any solution ?

**Comment by caciobanita** [comment]
Can you please help me regarding the same probleme. In my case only one category is afected. 
After import i neeed to change tha name for that category and save.
Any solution ?
