### ISSUE TITLE
Tax calculation

### ISSUE THREAD

**Issue by ghost** [magento/magento2#9593]
### Preconditions

1. Magento CE 2.1.x
2. Php7

### Steps to reproduce

1.  Add several Products excluding taxes with following prices
2. Add a Tax rate of 19%
3. Create an Order with those given Products

### Expected result

1. The taxes are applied correctly Independent of the given qty.

### Actual result

1. Tax is calculated wrong because of precision

In Magento my Products are excluded taxes and the calculation is based on the total. So included taxes my Product has a price , let's say 15. My taxrate is 19%

So excluding taxes I have 15 / 1,19 = 12.6050. Since Magento is rounding these prices I added a price (excl Tax) of 12.61 to the Product. When calculating the taxes this results in 15.01 because of the rounding thing. When using 12.60 I still have the issue because the result is 14,99.

From what I can the the priceCurrency method already performs a round($price, 4) which should work. As far I figured out this was an issue in Magento 1.x.

How can I get 15€ including Tax, with a taxrate of 19%?

Same goes for a price like 45€. and it gets even more frustrating when a product is bought in a greater quantity

**Comment by choukalos** [comment]
Hi @xhallix you need to load the catalog with prices including tax to ensure you'll always see the exact price you want in this case.  Note too that you need to set shipping origin to the same location as your default store location for Magento to recognize the right tax rate for the catalog prices including tax.  

Please note that's because the tax algorithm in Magento 'locks' and ensures all prices are consistent/add up correctly based what it views as the 'gold' price.  The catalog price (include/excludes) tax setting is what controls that behavior.  So when you set it to include tax it makes sure that all prices including tax don't have extra pennies due to rounding and tucks all those in the excluding tax amounts.

Let me know if that addresses your issue.

**Comment by ghost** [comment]
Yep I changed it, so know my product prices are included with tax in the catalog. But in addition I had to adjust price currency rounding to precision of 4.

Regarding your explanation, is this written down somewhere in documentation? If not would it Make sense to add this?

Thanks for your help

**Comment by choukalos** [comment]
Yes, I've asked our documentation team to add it as part of their work to port the M1 tax configuration guide to M2.

**Comment by ghost** [comment]
Thanks that is great. I would also offer a pr for documentation if that will be of any help
