### ISSUE TITLE
M2.1.6 upgrade images no longer visible in categories

### ISSUE THREAD

**Issue by bondimedical3** [magento/magento2#9659]
After upgrading 2.1.5 to 2.1.6 product images are no longer visible on category pages however they are visible on the product page?
The console log says the image is 404 not found?
![magento](https://cloud.githubusercontent.com/assets/10808588/26142072/4967b99a-3b22-11e7-8aec-ae4b345b7a5c.jpg)

**Comment by hostep** [comment]
This is expected behavior (unfortunately).

This is also a duplicate of https://github.com/magento/magento2/issues/9275 & https://github.com/magento/magento2/issues/9276 

Please see this for more info and a possible workaround to be executed *before you upgrade* (highly experimental): https://github.com/baldwin-agency/magento2-module-magento-216-image-resize-migration-helper

**Comment by bondimedical3** [comment]
I have run the command:

magento catalog:images:resize

and the images have appeared.
You can close this.

**Comment by hostep** [comment]
@bondimedical3: please close yourself, I can't do that for you. (I'm not a Magento employee :))

**Comment by bondimedical3** [comment]
Thank you for your valuable assistance.
