### ISSUE TITLE
Pull request reviewing priority

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#9663]
Hi,
Right now I see that you trying to process faster new pull requests, they appearing in todo column at the top, hovewer older pull requests are waiting for a long time, and it's not meaning that these pull requests are less important. As good examples:
https://github.com/magento/magento2/pull/6324 - created in April 2016
https://github.com/magento/magento2/pull/7330 - created in November 2016
https://github.com/magento/magento2/pull/6473 - created in September 2016

Isn't it a bad practice to do not process these requests? Is there any reason why they are not processed? What we can do for faster processing?

**Comment by korostii** [comment]
This may come as a shock, but issues get processed even slower than that.
Maybe you also need to create a pull request in order to bring any attention to the issue...

Update: just noticed that there's a milestone set for the PRs you've mentioned: http://take.ms/OA0Gl
So it's not unreasonable to expect all of these to get processed in the next couple of weeks.

**Comment by ihor-sviziev** [comment]
Looks like pull requests started processing really good. I'm closing this issue as not relevant anymore
