### ISSUE TITLE
Magento 2.1.6 - Invoice PDF doesn't support Thai

### ISSUE THREAD

**Issue by jsdupuis** [magento/magento2#9666]
### Preconditions
1. Magento CE 2.1.6

### Steps to reproduce
1. In the admin, go to Sales > Orders
2. Select one 'completed' order and select the action 'Print Invoices' (any of the Print... actions actually)

### Expected result
1. Be able to read Thai names and Thai adresses in Thai alphabet

### Actual result
1. Thai letters are replaced by squares. Thai baht currency symbol is also unreadable.
[invoice2017-05-17_11-19-09.pdf](https://github.com/magento/magento2/files/1007500/invoice2017-05-17_11-19-09.pdf)

**Comment by 1408sheva** [comment]
Internal ticket MAGETWO-70209 was created;

**Comment by jsdupuis** [comment]
Any suggestion for a temporary fix?

**Comment by natawut-ch** [comment]
@jsdupuis 

Here is very dirty workaround / backup all file before doing these steps. ->
1. Get Thai font and upload to /lib/web/fonts (Font-version must be table v3, since the library can't parse table v4 font.)
2. Change font-location to uploaded fonts' location in **/vendor/magento/module-sales/Model/Order/Pdf/AbstractPdf.php**
```
   function _setFontRegular
   function _setFontBold
   function _setFontItalic
```
** you might need to adjust font size according to your font, finding "setFontSize"

3. Modify $drawingString in same file :: **/vendor/magento/module-sales/Model/Order/Pdf/AbstractPdf.php**
```
        $drawingString = '"libiconv"' == ICONV_IMPL ? iconv(
            'UTF-8',
            'UTF-16BE//IGNORE',
            $string
        ) : @iconv(
            'UTF-8',
            'UTF-16BE',
            $string
        );
```
to
```
        $drawingString = mb_convert_encoding($string, "UTF-16BE", "UTF-8");
```

If you get the error about cannot convert MacRoman. then you might have to edit **/vendor/magento/zendframework1/library/Zend/Pdf/FileParser.php** and look for 
```
function readStringMacRoman
```

replace 
```
return iconv('MacRoman', $characterSet, $bytes);
```
with 
```
return mb_convert_encoding($bytes, $characterSet, 'UTF-8');
```



PS. This is not appropriate way to deal with this issue. However LinLibertineFont contains no Thai-characters , and iconv lib can't properly convert MacRoman to UTF16BE (Used in thai font like TH Sarabun)

PS.2. This is very dirty fix. If your store is in EN/TH then it might work. But this might raise some errors if dealing with other char-encoding.

-------- BTW, Thai-font issue is in magento since 1.xx

**Comment by kp-drc** [comment]
I am using Magento 2.1.7 and facing same character issue when printing invoice of arabic order. Any update for solution ?
![screenshot from 2017-09-14 11 48 14](https://user-images.githubusercontent.com/20552286/30415326-36f01ea2-9945-11e7-90fe-3fab2aa23bad.png)

**Comment by magento-engcom-team** [comment]
@jsdupuis, thank you for your report.
We've created internal ticket(s) MAGETWO-70209 to track progress on the issue.

**Comment by kp-drc** [comment]
@magento-engcom-team  Please check same for arabic too as I am facing same issue.

**Comment by magento-engcom-team** [comment]
Hi @jsdupuis. Thank you for your report. 
The issue has been fixed in magento/magento2#13016 by @rossmc in 2.2-develop branch
Related commit(s):
 - [e44c91fbc0da0b36575b4eaef25bbc7b6fba112b](https://github.com/magento/magento2/commit/e44c91fbc0da0b36575b4eaef25bbc7b6fba112b)
 - [b38976b5341781fe72dcf41f421cd61abab453cf](https://github.com/magento/magento2/commit/b38976b5341781fe72dcf41f421cd61abab453cf)
 - [a5b685e77b0f39d72805495db6ccdac3eada35e0](https://github.com/magento/magento2/commit/a5b685e77b0f39d72805495db6ccdac3eada35e0)

The fix will be available with the upcoming 2.2.5 release.

**Comment by tmleeek** [comment]
great news , thanks every one

**Comment by magento-engcom-team** [comment]
Hi @jsdupuis. Thank you for your report. 
The issue has been fixed in magento/magento2#14711 by @rossmc in 2.1-develop branch
Related commit(s):
 - [6165e36c8d77640b0c3cab875afba978967266da](https://github.com/magento/magento2/commit/6165e36c8d77640b0c3cab875afba978967266da)

The fix will be available with the upcoming 2.1.15 release.

**Comment by magento-engcom-team** [comment]
Hi @jsdupuis. Thank you for your report. 
The issue has been fixed in magento/magento2#14710 by @rossmc in 2.3-develop branch
Related commit(s):
 - [abd7be087cebeae8109f8d998d24361cedb2d554](https://github.com/magento/magento2/commit/abd7be087cebeae8109f8d998d24361cedb2d554)

The fix will be available with the upcoming 2.3.0 release.

**Comment by o0mohammed0o** [comment]
@magento-engcom-team 
Hello, 
[https://github.com/magento/magento2/commit/abd7be087cebeae8109f8d998d24361cedb2d554](url)

this fix is not enough to fix the problem. the characters become supported but. still the letters are not connected together.

![letters not connected](https://user-images.githubusercontent.com/33866307/39110875-82f2ea8e-46db-11e8-9b10-423d46cfac36.png)

**Comment by o0mohammed0o** [comment]
After long investigation I found that zend pdf library doesn't support arabic language.
the solution for this is to use extension use another pdf library.
i found this extension uses another library and support arabic. you have to pay for it sorry didn't found free one. https://www.vnecoms.com/magento2-extensions/magento2-pdf-invoice-pro.html

**Comment by msliman** [comment]
@o0mohammed0o I  have this error, did you suggest any solution except this one 
https://www.vnecoms.com/magento2-extensions/magento2-pdf-invoice-pro.html

**Comment by ecombluesand** [comment]
i am getting same font issues in order invoice print out from admin panel.
from customer panel  its working perfectly. if any solution please put it here.

**Comment by mohit724** [comment]
If anyone found solution for Arabic. Please let me know
