### ISSUE TITLE
tax_class_id - update issue

### ISSUE THREAD

**Issue by Bullparts** [magento/magento2#9669]
On a fresh install under magento 2.1.6, 
it is impossible to update the tax_class_id attribute. for example if I have to change any data - front-end visible from yes to no, magento is unable to update the tax_class_id attribute - no message error display , ???
I have any issue with the other attribute.

**Comment by nikolaybaychenko** [comment]
I have the same problem here. Tested on Magento 2.1.6 and 2.1.7. tax_class_id attribute doesn't update from the backend, when you try to save it page just goes into bootloop. 

In addition, there are problems with saving tax_class_id when you create a product programmatically. I tried to debug it and it seems like it sets the value but after I save the product it loses it.
```
$product->setTaxClassId(4);
$taxId = $product->getTaxClassId(); // Returns 4
$product->save();
$taxId = $product->getTaxClassId(); // Returns null
```

Confirmed that this is a version related problem, works on Magento 2.1.2. Not sure from which version it started, didn't check other versions between 2.1.2 and 2.1.6. Was tested on different machines as well, all run apache2, php7.0 on Ubuntu 16.04.2 LTS. 

UPDATE: I realized what I wrote might be misleading. Problem with the saving tax_class_id attribute itself is version related, from 2.1.7, 2.1.6 and 2.1.2 it was working only in 2.1.2. Problem with saving value of tax_class_id in a product most likely not version related because it didn't work on any version.

**Comment by korostii** [comment]
Have you tried using `ProductRepository`'s `save()` instead? I believe `Product::save()` is deprecated.

**Comment by nikolaybaychenko** [comment]
@korostii I am not sure how well it is to create a product via ProductRepository, but tried to use ProductFactory and I am encountering the same problem with it.
```
$product = $this->productFactory->create();
...
$product->setTaxClassId(4);
$transactionSave = $this->transactionFactory->create(); // tax_class_id = 4
$transactionSave
    ->addObject($product)
    ->save();
$taxId = $product->getTaxClassId(); // tax_class_id = null
```

**Comment by korostii** [comment]
Yep you're supposed to use the factory in order to create the product and then repository in order to save it. Factories and Repositories used are specific to the closs of the model you're working with. For example, in order to handle product you'll need to inject `Magento\Catalog\Model\ProductFactory` and `Magento\Catalog\Api\ProductRepositoryInterface`.

To which class does your `$this->transactionFactory` belong?

**Comment by nikolaybaychenko** [comment]
@korostii $this->transactionFactory belongs to Magento\Framework\DB\TransactionFactory.
I tried to use ProductRepository to save a product, but that didn't change tax_class_id either.
```
$product = $this->productFactory->create();
...
$product->setTaxClassId(4);
$this->productRepository->save($product);
```

**Comment by veloraven** [comment]
Internal ticket was created - MAGETWO-69716

**Comment by veloraven** [comment]
I'm closing this issue as duplicate of #9153 as those issue has more general description - not about only one attribute but addresses more global problem.
However this issue is still mentioned in the internal ticket so when it is fixed you should see correspoding commits here as well.

**Comment by roobware** [comment]
I had the same 'thinked' issue on 2.1.8 OpenSource Edition.

I wrote an Data-Importer to create products for 'All Store Views'.
After updating the 'tax_class_id' i wondered me, why is the Data not updated?

I saw it, was updated on 'Store Default View'.
I fixed this, with '->setStoreId(0)', and this is working.

I hope, this will help you or any others :)

**Comment by yvvibhute** [comment]
> I had the same 'thinked' issue on 2.1.8 OpenSource Edition.
> 
> I wrote an Data-Importer to create products for 'All Store Views'.
> After updating the 'tax_class_id' i wondered me, why is the Data not updated?
> 
> I saw it, was updated on 'Store Default View'.
> I fixed this, with '->setStoreId(0)', and this is working.
> 
> I hope, this will help you or any others :)
File path?
