### ISSUE TITLE
Translation for layered navigation attribute option not working

### ISSUE THREAD

**Issue by popatkaran** [magento/magento2#9679]
I am using Magento CE 2.1.6 and having multilingual structure of website. When I switch the store to Arabic language all text getting translated  but only attribute options in layered navigation is not translating.

### Preconditions
1. Magento CE 2.1.6 
2. php 7.0.x 

### Steps to reproduce
1. Open website with default store.
2. Switch website with store switcher or paste direct url of another store
3. Check layered navigation

### Expected result
1. All the text should be translated to applied language to relevant store. 

### Actual result
1. All other text in website getting translated properly but attribute option name is not getting translated.
- Working well with English store.
![m216en](https://cloud.githubusercontent.com/assets/5829021/26188792/e0360704-3bbe-11e7-9098-29afc8a18388.png)
- Not working with Arabic one.
![m216ar](https://cloud.githubusercontent.com/assets/5829021/26188793/e036a2b8-3bbe-11e7-890b-f42c2b6c9101.png)

**Comment by tsifra** [comment]
Hello, did you translate it in backend - store - attributes - [attr name]?
If not - please read docs. And close the issue.

**Comment by popatkaran** [comment]
@tsifra  yes, I have already put translated text for the same.

I have found that if I flush cache using command after switching store translation works but, If i move back to English store attribute options remains in Arabic instead of English. This happens only for Layered navigation.

**Comment by tsifra** [comment]
My bad. Actually i didn't understand your problem right way. And translation of attribute was "hardcoded" by me to [atttribute] - Manage labels. Because i use only one language. Have no idea how to make different attribute labels for different languages. Maybe you have to create different stores with different labels and default languages? Please check [atttribute] - Properties tab. There are Admin and store columns for each attr value.

**Comment by popatkaran** [comment]
Yes, I have multiple store which having different language as default. Store change and other front-end area are translating well but only layered navigation is causing an issue.

**Comment by hostep** [comment]
We ran into the same problem today after upgrading from Magento 2.1.5 to 2.1.6.
This is a new bug introduced in 2.1.6 by this commit: 67b5ff7

It's because the wrong `storeId` is being used in the `cacheKey`, because the `storeResolver->getCurrentStoreId()` isn't always returning the current store id.

I'm currently working on a PR which will fix this.

**Comment by okorshenko** [comment]
The fix was delivered to 2.1-develop and develop branch. Thank you @hostep for your contribution!

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-69543

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-69728
