### ISSUE TITLE
Product reviews list template paging issue.

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#970]
In the file `/app/code/Magento/Review/view/frontend/templates/review.phtml` there is a js function called `processReviews` that (from what I understood) transforms makes the pager use ajax.  
but there is a problem with the `<a>` tag selector for the paging.  
Right now the selector looks like this:  `$('.pages a')` on line 

    $('.pages a').each(function(index, element) {

This works with a default install, but if I add other `<a>` elements anywhere in the page that match this selector, clicking on them will trigger an ajax request. This is may not be the desired effect.  
I think that the DOM selector should be `$('#product-review-container .pages a')` to limit the selected elements to the reviews paging.

PS: I know I can do a pull request, but I prefer to let you fix this in case I'm wrong.

**Comment by ihor-sviziev** [comment]
In this place really ugly js code, I think it should be rewrited

**Comment by verklov** [comment]
@tzyganu, we created a ticket in the internal tracker: MAGETWO-32939. We will update you once we have any news on the resolution and fix availability time. Thank you!

**Comment by vpelipenko** [comment]
@tzyganu, this issue is fixed and already available on public. Please, check it again.

**Comment by tzyganu** [comment]
@vpelipenko Thanks for the fix. Seams to be working nice.

**Comment by magento-engcom-team** [comment]
Hi @tzyganu. Thank you for your report. 
The issue has been fixed in magento/graphql-ce#1013 by @lenaorobei in 2.3-develop branch
Related commit(s):
 - [a18b0e194ba8520d1898ebb0827d0bee5a188290](https://github.com/magento/graphql-ce/commit/a18b0e194ba8520d1898ebb0827d0bee5a188290)
 - [39042ac2e2afa306730134d35bde9a4c33e12340](https://github.com/magento/graphql-ce/commit/39042ac2e2afa306730134d35bde9a4c33e12340)

The fix will be available with the upcoming 2.3.4 release.
