### ISSUE TITLE
Pub/Static directory is empty

### ISSUE THREAD

**Issue by mrugeshrocks** [magento/magento2#972]
I did a fresh install it went successful after a lot of tries. 

Both front-end and admin wont load CSS/JS/ files are not created in pub/static directory & as one directory _requireJs

Also frontend and adminhtml directories do not exist in pub/static.

**Comment by mrugeshrocks** [comment]
For further info, i was installing it with sample data.

**Comment by buskamuza** [comment]
Is Apache `mode_rewrite` enabled and its configuration is allowed from `.htaccess` files of your web-site?

**Comment by mrugeshrocks** [comment]
@buskamuza .htaccess was not allowed. I allowed .htacess and magento showed up the theme. 

Could you put some light on this behavior of magento?

Thanks for the help. :)

**Comment by mazhalai** [comment]
More documentation about this behavior [here](http://devdocs.magento.com/guides/v1.0/architecture/view/static-process.html)

**Comment by buskamuza** [comment]
Additionally to the big documentation @mazhalai pointed to, here is how static view files are related to `mod_rewrite`.
1. Browser requests a file
2. It's not found, as it doesn't exist by default
3. Rewrite rule in `pub/static/.htaccess` discovers it and redirects to `pub/static.php`
4. `pub/static.php` searches for the requested file using fallback mechanism described in the article mentioned by @mazhalai 
5. If the file is found, it's published somewhere to `pub/static/` folder (e.g., `pub/static/frontend/Magento/blank/css/file.css`)
6. On the next request, the file already exists, so it's just returned as a static content w/o involving `mod_rewrite`

This is default behavior (when `default` application mode is used).
In `developer` mode the file is not even published to `pub/static` folder. It goes through `pub/static.php` entry point every time.
In `production` mode it's expected that all files are published to `pub/static` folder, so `pub/static.php` should not be involved at all. If it is, it just returns 404 error. There is a tool for deploying static view files and it should be used to make `production` mode work (`dev/tools/Magento/Tools/View/deploy.php`)

**Comment by verklov** [comment]
@mrugeshrocks, are there other questions remaining that you'd like to ask related to your original question?

**Comment by mrugeshrocks** [comment]
Thanks @buskamuza & @mazhalai 

With this im closing the issue.

**Comment by bucha** [comment]
Just as a side note…
I had to add `RewriteBase /pub/static/` when using a `VirtualDocumentRoot`.

**Comment by magento-engcom-team** [comment]
Hi @mrugeshrocks. Thank you for your report. 
The issue has been fixed in magento/graphql-ce#973 by @VitaliyBoyko in 2.3-develop branch
Related commit(s):
 - [3489da5cf2cb98ad9ff758b3a3c8f6783339436b](https://github.com/magento/graphql-ce/commit/3489da5cf2cb98ad9ff758b3a3c8f6783339436b)
 - [63bd2327cdaba3f75b9d6e955e181f2c4a18a13c](https://github.com/magento/graphql-ce/commit/63bd2327cdaba3f75b9d6e955e181f2c4a18a13c)
 - [b64a485793d81b0734539e27a0c049b765186991](https://github.com/magento/graphql-ce/commit/b64a485793d81b0734539e27a0c049b765186991)

The fix will be available with the upcoming 2.3.4 release.

**Comment by magento-engcom-team** [comment]
Hi @mrugeshrocks. Thank you for your report. 
The issue has been fixed in magento/magento2#28366 by @Nazar65 in 2.4-develop branch
Related commit(s):
 - [8bfc104948ce65e0f98e78f34aeffacdc2f8f276](https://github.com/magento/magento2/commit/8bfc104948ce65e0f98e78f34aeffacdc2f8f276)
 - [a5a13fb40f7656dfa79cecec9c0b921d30cdd52f](https://github.com/magento/magento2/commit/a5a13fb40f7656dfa79cecec9c0b921d30cdd52f)
 - [5667714ced2b982a14b5b18b6591d34fbf287028](https://github.com/magento/magento2/commit/5667714ced2b982a14b5b18b6591d34fbf287028)
 - [a867d70f9809e95c75e3d4aa6dc0d2808620605f](https://github.com/magento/magento2/commit/a867d70f9809e95c75e3d4aa6dc0d2808620605f)
 - [1d0316d756987e4453c38bb432eee03153a7fec0](https://github.com/magento/magento2/commit/1d0316d756987e4453c38bb432eee03153a7fec0)
 - [d06fd27fbdaa2633c81e9f5babff6aa28b56ffed](https://github.com/magento/magento2/commit/d06fd27fbdaa2633c81e9f5babff6aa28b56ffed)
 - [f953f3545453fecfc5d47e2b23411a13aa39b6be](https://github.com/magento/magento2/commit/f953f3545453fecfc5d47e2b23411a13aa39b6be)
 - [a0ed711a5235f06cb6d36a308293f0257b93c256](https://github.com/magento/magento2/commit/a0ed711a5235f06cb6d36a308293f0257b93c256)
 - [a63e68113f978ce0c24b1a2221a314b0fdbcbebe](https://github.com/magento/magento2/commit/a63e68113f978ce0c24b1a2221a314b0fdbcbebe)
 - [2133abce671bb6b09a835eec80e265568f9b3960](https://github.com/magento/magento2/commit/2133abce671bb6b09a835eec80e265568f9b3960)
 - [5032914621d42df37977acea17e06d98c94b748e](https://github.com/magento/magento2/commit/5032914621d42df37977acea17e06d98c94b748e)
 - [a54886350a90a3c944af90c5cd88d4dbbc0b0881](https://github.com/magento/magento2/commit/a54886350a90a3c944af90c5cd88d4dbbc0b0881)
 - [6e8c990ba95ad754dfe6a617bff77e428f2c6bc4](https://github.com/magento/magento2/commit/6e8c990ba95ad754dfe6a617bff77e428f2c6bc4)
 - [aef54e3e1697e1fb513c2ba35d81a6fb665cb6b2](https://github.com/magento/magento2/commit/aef54e3e1697e1fb513c2ba35d81a6fb665cb6b2)

The fix will be available with the upcoming 2.4.1 release.
