### ISSUE TITLE
The requested component ("frontend-input") is not found. Before using, you must add the implementation.

### ISSUE THREAD

**Issue by yogendrabmishra** [magento/magento2#9734]
We have migrated our Magento 1 EE1.14.2.4 database to M2 EE 2.1.6. In M1 EE, we are having custom Frontend Input type  as miles and I have created the same in M2 EE2.1.6. Also I have added the type to adminhtml ui-component. But still I am getting the exception. 
### Preconditions

1. Magento EE 2.1.6
2. PHP 7
3. Mysql 5.6
### Steps to reproduce

1. Create custom frontend input type in M1 EE and create some products with that. 
2. Migrate the database to M2 EE. Catalog import without problem. 
3. When you try to view the product, it throws exception. 
### Expected result

1. We should be able to view and edit the product in admin panel.

### Actual result

1. [Screenshot, logs]
<img width="1609" alt="screen shot 2017-05-23 at 11 23 45" src="https://cloud.githubusercontent.com/assets/1279893/26347590/542dd788-3faa-11e7-9799-1fbbd6f1b209.png">

**Comment by veloraven** [comment]
@yogendrabmishra thank you for your report.
Given this issue is reported against Enterprise edition, please report via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level
