### ISSUE TITLE
Default welcome message returns after being deleted

### ISSUE THREAD

**Issue by robgt** [magento/magento2#9742]
Default welcome message returns after being deleted

### Preconditions

1. Magento 2.1.6
2. PHP 7

### Steps to reproduce

1. Go to Content > Configuration > Click Edit on theme being used
2. Expand Header section to reveal "Welcome Text" field
3. Field will be populated with "Default welcome msg!"
4. Delete the text, and click save (or save and continue edit)
5. Repeat steps 1 to 3.
6. Examine same form field - contents will reappear (seemingly not deleted, although front end at this stage will not display it).
7. Click save again
8 Welcome text has been saved to default value again and will reappear on the website.

### Expected result

1. Default value, once deleted, should not reappear.

### Actual result

1. Default value reappears, and is applied next time you click save.
2. Same thing happens with the Footer default copyright notice.

**Comment by Stas94** [comment]
@robgt Thanks for reporting this issue. We've created internal ticket MAGETWO-70166 to address this issue.

**Comment by magento-engcom-team** [comment]
@robgt, thank you for your report.
We've created internal ticket(s) MAGETWO-70166 to track progress on the issue.

**Comment by okorshenko** [comment]
The issue has been fixed and delivered to 2.2-develop branch. Will be available with upcoming patch release

**Comment by magento-engcom-team** [comment]
Hi @robgt. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1296 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - aefd089d3b29023d4ec09036f5ae836a97fe549b
 - 0c799d2defa8341b7eb23bd5c92717b5f64138e7
 - 0a282955d6ec5b8e8f8fc6cf94d1a813adebb285
 - d0d8d03982dde84fb119636492d3272b54bd59e0
 - 1623007dc26f1953b10893304f3d9b7efa8db805
 - 64f63b3cf56fe03ae78a0154133d27f05749be4a
 - eceb5eb5d31608ef96403dbd7857e8178acb5dc6
 - e1db353d9fd9ed508846160a3cdb16228c09b60a
 - 7b12d50d92e1503f959219a5c8f05ecbef1cc423
 - 60285c4011fa4ccabe6548ace2b6aefc0cc65c8f
 - 2d910df07653f1a3fac8fbf3688b57ce5e3869e7
 - 57c355a802a3e2ff21b7cf7312c203ab735cd2bd
 - 4f9f40e54207c31a2c5e8460c85a042ad39cfa66
 - ebd663b8dde32c49d9f147bd2bbe3b438a2f415e
 - bdb62bb6c6c8326b31c83fc4c6343ee4017b84e6
 - 76f6eed85e282be7df18766868f03a5e1aa4109c
 - cd5c72ee83a89fe3c6632ddf9b6aeabf512503fc
 - b03566074756b7264155e10e2d68845d5000df29
 - 6217c009f7565b72fe8bd24ca2e862131f3d8dee
 - e07d040a33324bae14961ccc629604738854684b
 - 47ea3188264a42f735d12c6c6ebe208135eefb69

The fix will be available with the upcoming patch release.
