### ISSUE TITLE
Missing applied_taxes from Webservice API

### ISSUE THREAD

**Issue by keiant25** [magento/magento2#9746]
When calling REST or SOAP the segments: applied_taxes, item_applied_taxes, converting_from_quote attributes are missing from the SOAP response.

In order to reproduce just call the REST API function "{{host}}}/rest/V1/orders/{{order_id}}"

### Expected result
It should return the taxes details.

Thank you!

**Comment by YevSent** [comment]
Hi, @keiant25, thanks for reporting. I've created the internal ticket (`MAGETWO-69504`) for the investigation.

**Comment by magento-engcom-team** [comment]
@keiant25, thank you for your report.
We've created internal ticket(s) MAGETWO-69504, MAGETWO-73287 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @keiant25

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@keiant25 thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
