### ISSUE TITLE
Paypal Express failed same order number of last order

### ISSUE THREAD

**Issue by puples** [magento/magento2#9761]
Hello,

I have a problem with magento 2.1.4

When some users return to the site and repaid with paypal express checkout. The payment attempts to be made on the same order number as the last time.

It pays with paypal its first order, it creates an order 10000001. it returns 3 months later the orders are at the 10000199 it should have had the 10000200 and it t always to pay on the 10000001 and the system block it. Know or it's coming ? It's pretty annoying, suddenly this user can no longer pay ... but the others yes. 

thank you in advance

**Comment by YevSent** [comment]
Hi, @puples, please, provide transaction details from debug log, information about specific extensions, etc.

**Comment by tomasinchoo** [comment]
This problem happens when quote.is_active = 1 and there is sales_order.increment_id = quote.reserved_id.
For some reason I only noticed this issue with PayPal express.
It is, very hard to reproduce and that makes this issue dangerous: In short -  You will notice it when you get some amount of orders on production site. Until this is fixed, your best bet is to make a cron job which would delete those (yes, it is ugly solution).

**Comment by puples** [comment]
@tomasinchoo thanks, i go to see that. you think i just make a cron job to do quote.is_active=0 ? 

Thanks

**Comment by magento-engcom-team** [comment]
Hi @puples 
We are not able to reproduce the issue on 2.1.9 and 2.2.0
It would be great if you can provide precise steps to reproduce or video recording how we can reproduce this issue. We can not change core code if we can not reproduce the issue on our side.
