### ISSUE TITLE
Cart Price Rules - Fixed amount discount for whole cart 

### ISSUE THREAD

**Issue by inelukipg** [magento/magento2#9775]
### Preconditions

1. Magento 2.1.6

### Steps to reproduce

1. Create a new Cart Price Rules with settings:
* Coupon: Specific Coupon
* Apply: Fixed amount discount for whole cart
* Discount Amount: 50
* No rules

### Expected result

Te discout amount should not split up and should not be shown for each ordered product.
Just show the total discount under Order Totals.

### Actual result

The discount amount (50) is split up between the order rows. (26,8 resp. 23,20)
The discount amount (50) is shown under Order Totals.

1. [Screenshot, logs]
![github](https://cloud.githubusercontent.com/assets/23335844/26548021/4003b8fa-4472-11e7-8dce-8d4288186bd4.jpg)

**Comment by korostii** [comment]
> discount amount should not split up

Why not? This is exactly the expected behavior. It's been working like that since the good old times of Magento 1.

**Comment by magento-engcom-team** [comment]
@inelukipg, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by inelukipg** [comment]
@korostii I never developed in Magento1 only pre Magento1 (Good Old OsCommerce). 

I think the expected behavior is strange. If I go to the local store and use a discount coupon (lets call it Fixed amount discount for whole cart) I would be suprised if the store would split up the discount insted of sum all groceries up and then subtract the discount.

@magento-engcom-team Ok thank you. Maybe I'll submit a pull request for changing the name from "Fixed amount discount for whole cart" to "Fixed amount discount for whole cart per row"

**Comment by luccasmaso** [comment]
As matter of this behavior, is there some explanation/use case where is important to have discounts for entire cart splitted proportionally through cart items? Why not save the total discount amount per order at database level instead of order_item in that case? Thanks!

**Comment by versdivers** [comment]
I will tell you where this is wrong.
![image](https://user-images.githubusercontent.com/18028151/42640405-861dabb2-85f2-11e8-89ce-cafe4d171034.png)

As you can see i have a discount and a shipping cost. To make it easy they are the same. As you can see the TAX is 32.01. But it should be 31.99!

Here an example with no discount and no discount 
![image](https://user-images.githubusercontent.com/18028151/42640536-ce67c5ec-85f2-11e8-8fbb-9053d3ea58bf.png)

Here the Tax is good. So applying a discount to whole cart results in having bad roundings...
It should not influence the TAX. To be honnest it should not be a discount for each item. This is NOT a correct behaviour regardless of its past. I dont want to have a discount / Item. I dont want it to show like that on the invoice nor the Order because it is not what i selected.

AND not only is it not correct to have that / item it also creates bugs like this. Why make it complicated?
FYI : I calculate my tax like this:
![image](https://user-images.githubusercontent.com/18028151/42640679-1db54502-85f3-11e8-99e8-5a84164cab7c.png)

**Comment by versdivers** [comment]
AND because it shows the Discount amount in the subtotal AND within the products this is just confusing and wrong. Administration at my clients are so confused. Synchronize this with any accountant software and you have differences
