### ISSUE TITLE
Uncaught TypeError after upgrade to 2.1.7

### ISSUE THREAD

**Issue by ooples** [magento/magento2#9845]
I'm getting these exceptions each time the cron runs and I don't know how to fix them

PHP Fatal error:  Uncaught TypeError: Argument 3 passed to Zend_Mail_Protocol_Smtp::__construct() must be of the type array, null given, called in /var/www/html/vendor/magento/zendframework1/library/Zend/Mail/Transport/Smtp.php on line 198 and defined in /var/www/html/vendor/magento/zendframework1/library/Zend/Mail/Protocol/Smtp.php:123
Stack trace:
#0 /var/www/html/vendor/magento/zendframework1/library/Zend/Mail/Transport/Smtp.php(198): Zend_Mail_Protocol_Smtp->__construct(NULL, NULL, NULL)
#1 /var/www/html/var/generation/SendGrid/EmailDeliverySimplified/Model/Transport/Interceptor.php(76): Zend_Mail_Transport_Smtp->_sendMail()
#2 /var/www/html/vendor/magento/zendframework1/library/Zend/Mail/Transport/Abstract.php(348): SendGrid\EmailDeliverySimplified\Model\Transport\Interceptor->_sendMail()
#3 /var/www/html/var/generation/SendGrid/EmailDeliverySimplified/Model/Transport/Interceptor.php(89): Zend_Mail_Transport_Abstract->send(Object(Magento\Framework\Mail\Message))
#4 /var/www/html/vendor/magento/zendframework1/library/Zend/ in /var/www/html/vendor/magento/zendframework1/library/Zend/Mail/Protocol/Smtp.php on line 123

**Comment by hostep** [comment]
@ooples: I see you are using a third party extension: SendGrid_EmailDeliverySimplified which is most likely responsible for this exception. At a first glance between the code of Magento 2.1.6 and 2.1.7, nothing seems to have changed regarding the Zend_Mail library, so it would highly surprise me if this is a Magento bug.
Maybe contact that particular third party vendor first? It feels to me that the bug is in their extension and not in core Magento.

Please close this issue, unless you can prove the issue exists in a clean Magento 2.1.7 without third party extensions, and if that's the case, you can then reopen the issue. Thanks! :)
