### ISSUE TITLE
Animation images are not showing animation on frontend product details page.

### ISSUE THREAD

**Issue by vagvala-suresh** [magento/magento2#9857]
I have upload a gif image for a product that is showing 360 view of product, after uploading it is working in backend.
![c2081ba2-d104-11e6-8df5-354455e489c0](https://cloud.githubusercontent.com/assets/29228425/26827221/e504d5e2-4ad9-11e7-9b46-45509eac79be.png)

When I go to frontend on product details page it is not working I mean it is not showing its animated view.

![c20b147e-d104-11e6-8de4-149e50cd1116](https://cloud.githubusercontent.com/assets/29228425/26827265/0d483b16-4ada-11e7-93ca-ccd98560e6df.png)

please suggest me..how can i do it

**Comment by korostii** [comment]
If you are looking for an advice please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/). 
The GitHub issue tracker is intended for tracking technical issues (read: "bugs") only.

**Comment by vagvala-suresh** [comment]
ok thank you korostii

**Comment by veloraven** [comment]
@suresh-vagvala thank you for your feedback.
If you want to report an issue please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
If you are looking for an advice or discussion please use forums specified above.

**Comment by magento-engcom-team** [comment]
@suresh-vagvala thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more details regarding your environment, or try to reproduce this issue on a clean installation.

**Comment by aaronware** [comment]
I'm not sure why this would be considered closed. It's easily reproducible. When you upload an animated.gif file to the admin area it will show the animation properly. That is because the image while smaller more than likely hasn't actually be resized by the magento image caching. It's just scaled to fit the parent container.

If you view the product details page for the image you uploaded or view the image directly, only the first frame of the .gif is displayed. No animation continues, that is because the all other frames have been stripped from the the newly generated image.

**Comment by vagvala-suresh** [comment]
yes, aaronware.
do you have any idea on this? without loading entire media for the product is there any alternative solution. please let me know.

**Comment by olivianicholls** [comment]
Hi there, I am also experiencing this issue. Magento ver. 2.3.0 is installed. Locally there is no issue, the GIFs loop as expected. The issue occurs in either a staging or a live environment. As @aaronware stated above, this issue is very easily reproducible. Please find steps to reproduce below.

**Steps to Reproduce:**
1. Log in to either staging or live environment's backend
1. Add GIF to product's images. The image will appear to be animated as expected.
3. Save Product.
2. Navigate to said product's product page on the storefront.

**Expected result:**
Image is animated as it appears in the backend.
**Actual result:**
The image is not animated in either the thumbnail, or the main image. Both appear only as the first frame of the GIF.

The only way we've gotten this to work is to FTP onto the server and replace all relative image files on the server with your GIF. This is not only tedious, but gets undone when the cache is flushed and is therefore not a stable or reliable workaround. Please could you provide assistance or alternative solutions to this issue.

Many thanks

**Comment by Techytt** [comment]
Any update on this issue?

**Comment by olivianicholls** [comment]
I figured out a work around for this issue, if anyone else is also experiencing this issue. It might be a bit hacky but it's better than having to reupload every GIF every time the cache is flushed.

What I had to do was override Magento\Catalog\Model\View\Asset\Image, copy everything from that file, and change just getUrl() from:

```
public function getUrl()
    {
        return $this->context->getBaseUrl() . DIRECTORY_SEPARATOR . $this->getImageInfo();
    }
```

To:
```
public function getUrl()
    {
        $file = $this->getFilePath();
        $pathEnding = substr($file, strpos($file, ".") + 1); 
        if ($pathEnding == "gif" || $pathEnding == "GIF") {
            $path = substr($file, strpos($file, "/") + 1);
            return $this->context->getBaseUrl() . DIRECTORY_SEPARATOR . $path;
        } else {
            return $this->context->getBaseUrl() . DIRECTORY_SEPARATOR . $this->getImageInfo();
        }
    }
```

This retrieves the GIF that appears in the backend that works and doesn't get cached or stripped. If the image is not a GIF, then it continues to retrieve images as usual.

Not sure if this was the best way to go about this, but as it doesn't look like this issue is going to be resolved any time soon, it was necessary and works. I implemented this about a month ago now and have seen no issues since.

**Comment by rav-redchamps** [comment]
Animated GIF images don't work in native Magento 2system. You should try this Magento 2 extension https://redchamps.com/product-animated-gif-images-magento-2-extension.html
