### ISSUE TITLE
no TYPE_ENUM in _ddlColumnTypes of Magento\Framework\DB\Adapter\Pdo\Mysql

### ISSUE THREAD

**Issue by irinikp** [magento/magento2#9883]
In Magento 2, there is no TYPE_ENUM supported by class Magento\Framework\DB\Adapter\Pdo\Mysql
Is this something that could be supported in the future?

**Comment by irinikp** [comment]
Shouldn't someone add a label here, or ask any questions?

**Comment by korostii** [comment]
Hello there. Eventually, yes.
However, things move rather slow around here and most of the workforce is overloaded by polishing of 2.2 release candidate. Thus, it might be while until your issue get proper attention.

In the meantime, feel free to format your issue according to the [issue template](https://github.com/magento/magento2/blob/62667cb65d69cd6028c9038dda0087684a3df834/ISSUE_TEMPLATE.md) otherwise it might get a `needs update` label.
Please also make sure it's formulated as a bug report (e.g. specify expected behavior and explain why the current behavior is incorrect) because technical questions technically should be posted to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/) instead (and if you post a question here it might be closed eventually rather than answered).

Have a nice day!

**Comment by magento-engcom-team** [comment]
@irinikp thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result
If you'd like to update it, please reopen the issue.

**Comment by orlangur** [comment]
Hi @irinikp, it is absent intentionally, please check https://magento.stackexchange.com/a/98966/40869 for more details.

GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions.
