### ISSUE TITLE
Admin Dashboard Broken 

### ISSUE THREAD

**Issue by vitormfs** [magento/magento2#9898]
I installed it on a local host for testing and it's not working. Using the 2.1.7 version with no sample, i got from de donwload page.
All the buttons has no icons and the pages do not open.
You can see how my dashboard in the attachment
![magento dashboard](https://user-images.githubusercontent.com/29312090/26988747-e48c9664-4d26-11e7-9fa8-e2e445bcec66.PNG)

 Did I installed something wrong?

Thanks

**Comment by veloraven** [comment]
@vitormfs thank you for your feedback.
Please format this issue according to template: with exact and detailed steps about your installation process, actual result, and expected result. Beside the rules it is much easier to understand what is the actual problem is when issue is described by template.
Please also specify your environment: OS, versions of PHP, MySQL and web-server.
Please also specify if it was clear install or upgrade from some previous version.

**Comment by rderwish** [comment]
Hey i have the same problem. 
I use the magento version 2.1.7 on localhost.
Php Version: 5.6.30
MySQL data base
Apache Server

I have the same problem with the Magento Home page images too.

**Comment by magento-engcom-team** [comment]
Hi @vitormfs could you please try the latest release? We can not reproduce the issue on our side.
