### ISSUE TITLE
"No payment information required" - Email not sent by cronjob

### ISSUE THREAD

**Issue by lfritsche** [magento/magento2#9907]
### Preconditions

1. Magento 2.1.6 (issue since 2.0.4)
2. PHP 5.6 & 7.0

### Steps to reproduce

1. If order mails are triggered within a cronjob-run process, every Magento standard payment method (PayPal, checkmo, bank transfer payment, ...) proceeds as excepted and an order mail is sent, expect on payment method "no payment information required".
2. Trying to send an order-mail of an order placed with payment method: "no payment info required", does not succeed. I do have to manually (re-)send the email in the backend.
3. I'm facing this issue also using popular third party extensions with own cronjob processes, sending (order) mails. 

### Expected result

1. Order email is sent on orders using payment method "no payment information required"

### Actual result

1. No email is sent.
2. Manually sending the mail via Backend works as expected.

**Comment by veloraven** [comment]
@lfritsche thank you for your report.
Please describe steps in format of actions, not general description. So that when someone reproduces the issue he can just reproduce number of actions like "open", "click", "add", etc. It's hard to understand what exactly should be done when steps are written in form of discussion. 
Also it's not clear if you face the issue only with 3rd party extensions or with native Magento functionality as well.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
