### ISSUE TITLE
Updating single category meta info, invalidates all FPC

### ISSUE THREAD

**Issue by cizgidekiadam** [magento/magento2#9909]
### Preconditions

1. Magento 2.1.2
2. PHP 7.0.18
3. Varnish for FPC

### Steps to reproduce

1. Be sure for FPC enabled and content cached
2. Update a category meta info
3. Save
4. Visit page

### Expected result

1. Saved category and updated FPC for just that category related pages

### Actual result

1. All FPC cleared.

**Comment by 1408sheva** [comment]
Thanks for reporting this issue. 
We've created internal ticket MAGETWO-70429 to address this issue.

**Comment by magento-engcom-team** [comment]
@rbostan, thank you for your report.
We've created internal ticket(s) MAGETWO-70429 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @rbostan

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@rbostan thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
