### ISSUE TITLE
Upgrading to 2.1.7 changed dropdown attributes to swatches

### ISSUE THREAD

**Issue by roseofgold** [magento/magento2#9923]
Preconditions
1. Magento 2.1.7
2. PHP 7.0.17
3. mySQL 5.6.35-80.0

Steps to reproduce
1. Installed Magento 2.1.2 with custom products
2. Used Web Setup Wizard to Upgrade System to 2.1.7

Expected result
1. Size options show on front end as dropdown list. Code is placed in `<div class="field configurable required">`
![image](https://user-images.githubusercontent.com/14198652/27053913-f06db798-4f73-11e7-91c4-88e13099d5f6.png)

Actual result
1. Size options do not show on front end. Code shows as swatch. `<div class="swatch-opt" data-role="swatch-options">`
![image](https://user-images.githubusercontent.com/14198652/27053894-dd0d50a0-4f73-11e7-8577-4e0b5543f7de.png)

**Comment by korostii** [comment]
Whis seems to be a duplicate of #9832. 

Please check if you have uses of `isProductHasSwatchAttribute` in your customized code as per [this comment](https://github.com/magento/magento2/issues/9832#issuecomment-306027785) and update those. That should resolve your issue.

**Comment by antboiko** [comment]
Hi @roseofgold, thank you for your report. We checked the opposite case (swatch attributes being converted to dropdowns) within #9832 and we couldn't reproduce the issue. 
Can you please check the suggestion provided by @korostii and let us know if the issue is still reproducible.

**Comment by roseofgold** [comment]
@korostii it is very similar to #9832. It is the opposite case as @antboiko said.

I have not extended the swatches module. I have checked the vendor files (`vendor/magento/module-swatches/Block/Product/Renderer/`) and the getRendererTemplate fuction does have `$this->isProductHasSwatchAttribute()` in it.

Is there somewhere else I should check? **Novice Magento coder here**

**Comment by korostii** [comment]
I'd start in `app` folder if you have any local customizations and also I would check all of 3-rd party modules\themes you happen to have.

`vendor/magento` folder is _expected_ to be okay, in this case it's probably your other code that got outdated and needs to be adjusted. 

Any chance you could find amore experienced colleague to lend you a hand and help you find the issue? 
Magento StackExchange might also be helpful in such cases (if you're able\allowed to disclose the source code).

**Comment by roseofgold** [comment]
I will see if I can find some help on StackExchange or through my PHP groups.

**Comment by roseofgold** [comment]
I have searched through my files. The only place that isProdustHasSwatchAttribute or getRendererTemplate shows up is in the vendor files.

**Comment by korostii** [comment]
Ok, so. I had this reproduced on 2.1.7 CE.

**Steps to reproduce:** save the configurable attribute with frontend input "Text Swatch", then switch back to dropdown and save again.
Actual result: select won't appear on the product page anymore (only the label shows up). 

In contrast, an attribute created before upgrade from 2.1.5 to 2.1.7 shows up okay.

Additional considerations: As far as I can tell the issue is introduced in 2.1.6 and remains in 2.1.7
It seems that the check performed by the `isProductHasSwatchAttribute()` method depends on whether 
the attribute has corresponding entries in `eav_attribute_option_swatch` table.
Apparently, those records don't get flushed when you switch the frontend_input type to "dropdown". Cleaning them up manually seems to fix the attribute and the dropdown appears as expected.

"Well-tested, backwards-compatible, non-breaking patch releases." Yeah, right.

**Comment by roseofgold** [comment]
@korostii Thank you for tracking that down. However that still didn't work for me. I did have NULL entries for the attribute in that table. I deleted those line, flushed cache and it still doesn't show up. Is there another table that I should be looking in as well?

I'm about ready to recreate the option to not have to deal with it anymore. Thankfully this is an option for me at this time.

**Comment by korostii** [comment]
> Is there another table that I should be looking in as well?

Not that I know of, unfortunately. Flushing `eav_attribute_option_swatch` entries corresponding to the attribute (all of them, not just specific to single product or option) worked for me.
Hope you're able to resolve your issue, good luck with your findings!

P.S. I wish the Magento guys would be able to catch this before the release. I think some thorough code review might've spotted this bug.

**Comment by koenner01** [comment]
Why is this issue marked as 'needs update'. This is clearly still an open issue and has been described perfectly to standards

**Comment by OZZlE** [comment]
It's fixed in 2.1.8 but if you don't want to upgrade then you can patch this in: https://github.com/magento/magento2/commit/b84fe279c2306d74441354899900dc9f124437b6

**Comment by GuidoHub** [comment]
I had color swatch but after the update from 2.1.7 to 2.1.8 it became dropdown and I cannot turn it back to swatch.

**Comment by GuidoHub** [comment]
@OZZlE the fix in file vendor\magento\module-swatches\view\adminhtml\templates\catalog\product\attribute\text.phtml breaks my excisting Text swatch. I suddenly have an extra column Description. After replacing the file with a copy of 2.1.7 it solved. Can you explain why this file has been changed and why the extra column is there?

First image is with file 2.1.8, second with 2.1.7

![swatch-1](https://user-images.githubusercontent.com/22280971/29892334-85753b66-8dce-11e7-8101-22d2ed8d2184.jpg)
 
![swatch-2](https://user-images.githubusercontent.com/22280971/29892619-84bbcdf6-8dcf-11e7-9b2d-e6327f10f9e8.jpg)

**Comment by OZZlE** [comment]
@GuidoHub as far as I an tell both the columns "Swatch" & "Description" are required where "Swatch" is the actual text the buttons get and the "Description" is the title text.

In 2.1.7 it lacks the "Swatch" column and only shows the "Description" column (without any hint). So what you are saving then is essentially NULL on the "Swatch" and then things start to go wrong. I did not investigate it further than that but saw in the table that `eav_attribute_option_swatch` everything was null. After Truncating this table as mentioned in a previous comment (not by me) and using the 2.1.8 template and saving again all my Text Swatches started to work properly for me.

I do **not** work at Magento so I cannot say why.

**Comment by shreyap26** [comment]
Hi @roseofgold! I had the same bug. After upgrading from 2.1.2 to 2.1.8, Size attribute which was dropdown was used as Swatch on Configurable Product Pages. I had Null values for the attribute option_ids in `eav_attribute_option_swatch` table. I deleted those rows from the table but the Size attribute was still treated as a Swatch. This was because the swatch attribute_ids were retrieved from CacheInterface.
writing $this->cache->clean() in module-swatches/Model/SwatchAttributeCodes getCodes() solved the issue. I removed this line after loading the product page once.

**Comment by eugene-shab** [comment]
Closed because duplicate #12695

**Comment by sidolov** [comment]
Hi @roseofgold. Thank you for your report. 
The issue has been fixed in magento/magento2#12771 by @eugene-shab in 2.2-develop branch
Related commit(s):
 - [39b1ef3a5b5a4741a0c664135b13944c4e7c7b61](https://github.com/magento/magento2/commit/39b1ef3a5b5a4741a0c664135b13944c4e7c7b61)
 - [94539b755992f120927a4760c06c624a0ced07c7](https://github.com/magento/magento2/commit/94539b755992f120927a4760c06c624a0ced07c7)
 - [3d76096a752ff234843890d7a072cd1d64e8c1c2](https://github.com/magento/magento2/commit/3d76096a752ff234843890d7a072cd1d64e8c1c2)
 - [0b079e05ab2e12c004fb1e81bda57817e5f0f14f](https://github.com/magento/magento2/commit/0b079e05ab2e12c004fb1e81bda57817e5f0f14f)
 - [71d30b7c521fd5143a4cfd3252fa5c7c2c4fdd79](https://github.com/magento/magento2/commit/71d30b7c521fd5143a4cfd3252fa5c7c2c4fdd79)
 - [47b2f4841ae27fa7bde0124e8860493e79c62a92](https://github.com/magento/magento2/commit/47b2f4841ae27fa7bde0124e8860493e79c62a92)
 - [707f1cd34f0f4c905b07658849984d0eb825d6d7](https://github.com/magento/magento2/commit/707f1cd34f0f4c905b07658849984d0eb825d6d7)
 - [9153fe221d7ce9e65a3b082ab9d79c26245f1e0b](https://github.com/magento/magento2/commit/9153fe221d7ce9e65a3b082ab9d79c26245f1e0b)
 - [1bd4acfee8a58b035eef561aaebe94f97990a4a2](https://github.com/magento/magento2/commit/1bd4acfee8a58b035eef561aaebe94f97990a4a2)
 - [f4990277bf9f20227402f4b76e57499873b170ad](https://github.com/magento/magento2/commit/f4990277bf9f20227402f4b76e57499873b170ad)
 - [3fa9ed2485a97972133ddb1f7d7e775f784fe6e4](https://github.com/magento/magento2/commit/3fa9ed2485a97972133ddb1f7d7e775f784fe6e4)
 - [8fa792a1444670e60fe6052c77e7b35684549906](https://github.com/magento/magento2/commit/8fa792a1444670e60fe6052c77e7b35684549906)
 - [7cd7adecf598dd6f9fe6ecd4369208869442387d](https://github.com/magento/magento2/commit/7cd7adecf598dd6f9fe6ecd4369208869442387d)
 - [54ad76c1f48eafbfe16a4e8e3c7669145a190627](https://github.com/magento/magento2/commit/54ad76c1f48eafbfe16a4e8e3c7669145a190627)
 - [bd126512cfe4f139a10ada9136495c1a617df158](https://github.com/magento/magento2/commit/bd126512cfe4f139a10ada9136495c1a617df158)
 - [cb6975c3f57739946cb65acebaf62300def1fa99](https://github.com/magento/magento2/commit/cb6975c3f57739946cb65acebaf62300def1fa99)

The fix will be available with the upcoming 2.2.6 release.

**Comment by ishakhsuvarov** [comment]
Hi @roseofgold. Thank you for your report. 
The issue has been fixed in magento/magento2#17750 by @nmalevanec in 2.3-develop branch
Related commit(s):
 - [0f28b61565c3108281ef24c5f846ba2034e9ba9c](https://github.com/magento/magento2/commit/0f28b61565c3108281ef24c5f846ba2034e9ba9c)
 - [d159921f79c68e9aec489192c223ce5535ff47d9](https://github.com/magento/magento2/commit/d159921f79c68e9aec489192c223ce5535ff47d9)

The fix will be available with the upcoming 2.3.0 release.
