### ISSUE TITLE
Groupprice does not exist

### ISSUE THREAD

**Issue by newbie1** [magento/magento2#993]
In Linux system I get following error when I go to product page. In windows it works, because it doesn't care about casing.

Class Magento\Catalog\Model\Product\Attribute\Backend\Groupprice does not exist

Error is happening because actual file name is GroupPrice and not Groupprice.

**Comment by Sanuch** [comment]
This issue was fixed in PR #943, you should update your code to last revision and recheck it

**Comment by kandy** [comment]
Please note that if you installed application before the upgrade, you need to reinstall it or change  model name in the database

**Comment by choukalos** [comment]
Closing issue as it's addressed in PR #943; and is now in mainline.

**Comment by magento-engcom-team** [comment]
Hi @newbie1. Thank you for your report. 
The issue has been fixed in magento/graphql-ce#994 by @TomashKhamlai in 2.3-develop branch
Related commit(s):
 - [95f2c640402c7cec553c9563272a11633fa97524](https://github.com/magento/graphql-ce/commit/95f2c640402c7cec553c9563272a11633fa97524)
 - [b52c14e601dedc4ece9512d64ad6741c3f3089cc](https://github.com/magento/graphql-ce/commit/b52c14e601dedc4ece9512d64ad6741c3f3089cc)
 - [6da7a67a2ccc9c763b288e42bfa4767cc44ccbbb](https://github.com/magento/graphql-ce/commit/6da7a67a2ccc9c763b288e42bfa4767cc44ccbbb)
 - [54fe800ad3662af633ab6bde9bb6bc484b93b8a0](https://github.com/magento/graphql-ce/commit/54fe800ad3662af633ab6bde9bb6bc484b93b8a0)

The fix will be available with the upcoming 2.3.4 release.
