### ISSUE TITLE
checkout with credit card issue (sorry but something went wrong message when checkout with credit card (Authorize.net)

### ISSUE THREAD

**Issue by PKRAY007** [magento/magento2#9954]
### Issue:
Problem when checkout with credit card (Authorize.net)
### Version:
Magento ver. 2.1.2

Hi there, 
Some of our customer complain that they can't checkout with Credit Card (Authorize.net). A sorry message "**sorry but something went wrong**" showing when checkout. I have checked the issue also found the problem using credit card (testing mode). Another thing that it showing the order state Pending into the order section.

![sorry checkout using card](https://user-images.githubusercontent.com/10021677/27173247-d7241c7e-51d9-11e7-8f7b-ff52a94140bf.png)

### Theme Support Replied:
Also I have contacted with the theme (Porto) support section, but they replied that "payment method integration is core functionality of Magento default, not theme related". So, they are are unable to help about this issue. 

### Request:
Please check this issue and let me know your observation about the problem ad suggest what to do.

Regards,
Prodip Ray

**Comment by korostii** [comment]
You might be surprised, but such an error message may appear for a multitude of reasons. 

You'll need to dig deeper: please check both Magento's logs at `<Magento installation root dir>var/log` and server response using browser's inspector: look for the response to the transact.dll ajax request on the Network tab when you experience the error.

The underlying issue is most likely a misconfiguration of some sort. If that's the case, you should eventually be able to resolve it yourself.

**Comment by PKRAY007** [comment]
Hi @korostii 
Thanks for your response. I have checked the `<Magento installation root dir>var/log/debug.log` only showing the below response, 
`[2017-06-16 10:30:45] main.DEBUG: per product type 5.9500 simple {"is_exception":false} `[]
`[2017-06-16 10:30:45] main.DEBUG: per product type 5.9500 simple {"is_exception":false} []`
`[2017-06-16 10:30:50] main.DEBUG: cache_invalidate:  {"method":"POST","url":"https://fbms.com/authorizenet/directpost_payment/place/","invalidateInfo":{"tags":["catalog_product_1376","FPC"],"mode":"matchingTag"},"is_exception":false} []`

no other issue in `system.log` or `exception.log`
And I also checked the server response using browser's inspector for the response of the `transact.dll`, given below.
```
< HTML >
< BODY >
< TABLE >
< TR >< TD >An error occurred while trying to report this transaction to the merchant. 
An e-mail has been sent to the merchant informing them of the error. 
The following is the result of the attempt to charge your credit card. 
< BR >< BR >This transaction has been approved.< BR >
< P >It is advisable for you to contact the merchant to verify 
that you will receive the product or service.< BR ></ TD ></ TR >
</ TABLE >
</ BODY >
</ HTML >
```

Please see the network tab response in below screenshot,

![network response](https://user-images.githubusercontent.com/10021677/27224130-5a38b88c-52b5-11e7-9452-c35a1d33edf9.JPG)

Also please check the console issue,

![console](https://user-images.githubusercontent.com/10021677/27224160-74453016-52b5-11e7-9f39-d7a0f7a243a6.JPG)
Another think that may help you that, the problem happening in some days, in old order section that there was many completed order using Credit Card Direct Post (Authorize.net). 

Regards,

**Comment by PKRAY007** [comment]
Someone says that, this error generally comes when server connection timeout of api has been expired. For authorize.net it is 45 second. For that I have increased the expire time to 60 second, but no luck, 

in `vendor/magento/module-authorizenet/Model/TransactionService.‌​php` const `CONNECTION_TIMEOUT = 60;`

**Comment by korostii** [comment]
> Another think that may help you that

As harsh as it is, I don't really care about your issue. I am just passing by, I am not a representative of Magento, Inc. 
I might help you with some pointers, but ultimately it's up to you and no-one else.

Oh, and read the error you've just found!
`An error occurred while trying to report this transaction to the merchant. An e-mail has been sent to the merchant informing them of the error.`
Did you check your inbox? :)

Anyway, the error is easy to [google](https://stackoverflow.com/questions/20741240/how-to-use-relay-response-url-in-authorize-net-payment-gateway): you might need to check Relay Response URL in your Authorize.net backend as explained [here](https://support.authorize.net/authkb/index?page=content&id=A558)

>https://fbms.com/

Is that the domain you use? if it's just made up and written down in your hosts file on local machine, that'll never work. Authorize.net won't be able to find it in order to give you back the transaction result.

**Comment by PKRAY007** [comment]
@korostii, My mistake, I am so sorry and apologize for using the sentence. I am very grateful for your kindness, for helping to resolve my problem. 

Currently, I am checking all the issue that you mentioned here. I will update here if the problem solve or not.

Again, I am apologize for my mistake.

Regards,

**Comment by korostii** [comment]
Sure, no problem :)

Just wanted to make sure you understand that there's a limit to the help one might expect out here.
This is first and foremost a bug tracker.

Best regards & good luck with your findings.

**Comment by PKRAY007** [comment]
@korostii 
Thanks for your help. Finally the problem is fixed. The problem was in script timed out when Authorize.net trying to post transaction results to it.
I am very grateful to you for finding the issue. :+1:  :1st_place_medal: 

Regards,

**Comment by magento-engcom-team** [comment]
Closing, as problem seems to be resolved.
Thank you @korostii

**Comment by aniruddhadeshpande** [comment]
@PKRAY007, Could you tell me how you have fixed this issue? I'm facing same problem on multi website store of version -  Magento 2.1.9

**Comment by PKRAY007** [comment]
@aniruddhadeshpande, Please check your .htaccess rules. I believe there are some rules applied that blocked some core resources which is necessary for payment transaction. You need to remove that rules (you may switch to default .htaccess of magento Magento 2.1.9). Think your problem will solve.

Regards,

**Comment by aniruddhadeshpande** [comment]
@PKRAY007, Thanks for reply, i'm using Nginx i will check its configuration.

**Comment by topranavp** [comment]
I am having the same issue and using the default magento2 htaccess, but still I am getting the same error.

**Comment by gfxguru** [comment]
How did you all get around this issue? Same issue here Magento 2.2.7

**Comment by gfxguru** [comment]
How did you all get around this issue? Same issue here Magento 2.2.7
